-- Snapshot of the approved 78-row balance table. Source: Goc_NOVA/artifacts/pham-nhan-affix-balance/data.js
-- Goc_NOVA is a build-time reference only; this module has no runtime dependency on it.
local M = { MAX_SLOTS = 5, by_code = {}, rows = {}, families = {}, by_family = {} }

local rows = {
    { code = "equip_speed_i", name = "Nhanh Nhẹn I", family = "Nhanh Nhẹn", tier = "I", slot = "Vũ khí", effect_key = "addSpeedPercent", image_id = "N01", min = 1, max = 5, step = 1, scale = 1, unit = "%", fixed = false, fixed_value = 0, display = "1-5%", exclusive_group = "move_speed", cap = "Tổng từ đá 60%", source = "scripts/enums/hh_enchant.lua + scripts/enums/hh_effects.lua" },
    { code = "equip_speed_ii", name = "Nhanh Nhẹn II", family = "Nhanh Nhẹn", tier = "II", slot = "Vũ khí", effect_key = "addSpeedPercent", image_id = "N02", min = 4, max = 10, step = 1, scale = 1, unit = "%", fixed = false, fixed_value = 0, display = "4-10%", exclusive_group = "move_speed", cap = "Tổng từ đá 60%", source = "scripts/enums/hh_enchant.lua + scripts/enums/hh_effects.lua" },
    { code = "equip_speed_iii", name = "Nhanh Nhẹn III", family = "Nhanh Nhẹn", tier = "III", slot = "Vũ khí", effect_key = "addSpeedPercent", image_id = "N03", min = 8, max = 15, step = 1, scale = 1, unit = "%", fixed = false, fixed_value = 0, display = "8-15%", exclusive_group = "move_speed", cap = "Tổng từ đá 60%", source = "scripts/enums/hh_enchant.lua + scripts/enums/hh_effects.lua" },
    { code = "equip_speed_iv", name = "Nhanh Nhẹn IV", family = "Nhanh Nhẹn", tier = "IV", slot = "Vũ khí", effect_key = "addSpeedPercent", image_id = "N04", min = 12, max = 20, step = 1, scale = 1, unit = "%", fixed = false, fixed_value = 0, display = "12-20%", exclusive_group = "move_speed", cap = "Tổng từ đá 60%", source = "scripts/enums/hh_enchant.lua + scripts/enums/hh_effects.lua" },
    { code = "equip_speed_v", name = "Nhanh Nhẹn V", family = "Nhanh Nhẹn", tier = "V", slot = "Vũ khí", effect_key = "addSpeedPercent", image_id = "N05", min = 16, max = 30, step = 1, scale = 1, unit = "%", fixed = false, fixed_value = 0, display = "16-30%", exclusive_group = "move_speed", cap = "Tổng từ đá 60%", source = "scripts/enums/hh_enchant.lua + scripts/enums/hh_effects.lua" },
    { code = "add_max_use_small", name = "Bền Bỉ I", family = "Bền Bỉ", tier = "I", slot = "Trang bị có độ bền", effect_key = "add_max_use", image_id = "BB01", min = 20, max = 100, step = 20, scale = 1, unit = "độ bền", fixed = false, fixed_value = 0, display = "+20-100 độ bền", exclusive_group = "", cap = "Chỉ 1 viên Bền Bỉ", source = "scripts/enums/hh_enchant.lua" },
    { code = "add_max_use_big", name = "Bền Bỉ II", family = "Bền Bỉ", tier = "II", slot = "Trang bị có độ bền", effect_key = "add_max_use", image_id = "BB02", min = 80, max = 200, step = 20, scale = 1, unit = "độ bền", fixed = false, fixed_value = 0, display = "+80-200 độ bền", exclusive_group = "", cap = "Chỉ 1 viên Bền Bỉ", source = "scripts/enums/hh_enchant.lua" },
    { code = "add_max_use_tier_iii", name = "Bền Bỉ III", family = "Bền Bỉ", tier = "III", slot = "Trang bị có độ bền", effect_key = "add_max_use", image_id = "BB03", min = 160, max = 320, step = 20, scale = 1, unit = "độ bền", fixed = false, fixed_value = 0, display = "+160-320 độ bền", exclusive_group = "durability_capacity", cap = "Chỉ 1 viên Bền Bỉ", source = "scripts/enums/hh_enchant.lua" },
    { code = "add_max_use_tier_iv", name = "Bền Bỉ IV", family = "Bền Bỉ", tier = "IV", slot = "Trang bị có độ bền", effect_key = "add_max_use", image_id = "BB04", min = 260, max = 480, step = 20, scale = 1, unit = "độ bền", fixed = false, fixed_value = 0, display = "+260-480 độ bền", exclusive_group = "durability_capacity", cap = "Chỉ 1 viên Bền Bỉ", source = "scripts/enums/hh_enchant.lua" },
    { code = "add_max_use_tier_v", name = "Bền Bỉ V", family = "Bền Bỉ", tier = "V", slot = "Trang bị có độ bền", effect_key = "add_max_use", image_id = "BB05", min = 400, max = 640, step = 20, scale = 1, unit = "độ bền", fixed = false, fixed_value = 0, display = "+400-640 độ bền", exclusive_group = "durability_capacity", cap = "Chỉ 1 viên Bền Bỉ", source = "scripts/enums/hh_enchant.lua" },
    { code = "equip_attack_speed_i", name = "Xạ Kích I", family = "Xạ Kích", tier = "I", slot = "Vũ khí", effect_key = "atk_speed", image_id = "XK01", min = 2, max = 10, step = 2, scale = 1, unit = "%", fixed = false, fixed_value = 0, display = "+2-10% tốc đánh", exclusive_group = "attack_speed", cap = "Tổng từ đá 160%; mỗi viên tối đa 50%", source = "scripts/enums/hh_enchant.lua + scripts/enums/hh_effects.lua" },
    { code = "equip_attack_speed_ii", name = "Xạ Kích II", family = "Xạ Kích", tier = "II", slot = "Vũ khí", effect_key = "atk_speed", image_id = "XK02", min = 8, max = 20, step = 2, scale = 1, unit = "%", fixed = false, fixed_value = 0, display = "+8-20% tốc đánh", exclusive_group = "attack_speed", cap = "Tổng từ đá 160%; mỗi viên tối đa 50%", source = "scripts/enums/hh_enchant.lua + scripts/enums/hh_effects.lua" },
    { code = "equip_attack_speed_iii", name = "Xạ Kích III", family = "Xạ Kích", tier = "III", slot = "Vũ khí", effect_key = "atk_speed", image_id = "XK03", min = 16, max = 30, step = 2, scale = 1, unit = "%", fixed = false, fixed_value = 0, display = "+16-30% tốc đánh", exclusive_group = "attack_speed", cap = "Tổng từ đá 160%; mỗi viên tối đa 50%", source = "scripts/enums/hh_enchant.lua + scripts/enums/hh_effects.lua" },
    { code = "equip_attack_speed_iv", name = "Xạ Kích IV", family = "Xạ Kích", tier = "IV", slot = "Vũ khí", effect_key = "atk_speed", image_id = "XK04", min = 24, max = 40, step = 2, scale = 1, unit = "%", fixed = false, fixed_value = 0, display = "+24-40% tốc đánh", exclusive_group = "attack_speed", cap = "Tổng từ đá 160%; mỗi viên tối đa 50%", source = "scripts/enums/hh_enchant.lua + scripts/enums/hh_effects.lua" },
    { code = "equip_attack_speed_v", name = "Xạ Kích V", family = "Xạ Kích", tier = "V", slot = "Vũ khí", effect_key = "atk_speed", image_id = "XK05", min = 32, max = 50, step = 2, scale = 1, unit = "%", fixed = false, fixed_value = 0, display = "+32-50% tốc đánh", exclusive_group = "attack_speed", cap = "Tổng từ đá 160%; mỗi viên tối đa 50%", source = "scripts/enums/hh_enchant.lua + scripts/enums/hh_effects.lua" },
    { code = "restore_use_10s_1use", name = "Gia Trì I", family = "Gia Trì", tier = "I", slot = "Trang bị có độ bền", effect_key = "durabilityRegen", image_id = "GT01", min = 0, max = 0, step = 0, scale = 1, unit = "%", fixed = true, fixed_value = 0, display = "Hồi 1 độ bền mỗi 10 giây", exclusive_group = "", cap = "Chỉ 1 viên Gia Trì", source = "scripts/enums/hh_enchant.lua" },
    { code = "restore_use_5s_1use", name = "Gia Trì II", family = "Gia Trì", tier = "II", slot = "Trang bị có độ bền", effect_key = "durabilityRegen", image_id = "GT02", min = 0, max = 0, step = 0, scale = 1, unit = "%", fixed = true, fixed_value = 0, display = "Hồi 1 độ bền mỗi 5 giây", exclusive_group = "", cap = "Chỉ 1 viên Gia Trì", source = "scripts/enums/hh_enchant.lua" },
    { code = "restore_use_1s_1use", name = "Gia Trì III", family = "Gia Trì", tier = "III", slot = "Trang bị có độ bền", effect_key = "durabilityRegen", image_id = "GT03", min = 0, max = 0, step = 0, scale = 1, unit = "%", fixed = true, fixed_value = 0, display = "Hồi 1 độ bền mỗi giây", exclusive_group = "", cap = "Chỉ 1 viên Gia Trì", source = "scripts/enums/hh_enchant.lua" },
    { code = "restore_use_1s_2_percent", name = "Gia Trì IV", family = "Gia Trì", tier = "IV", slot = "Trang bị có độ bền", effect_key = "durabilityRegen", image_id = "GT04", min = 0, max = 0, step = 0, scale = 1, unit = "%", fixed = true, fixed_value = 0, display = "Hồi 2% độ bền mỗi giây", exclusive_group = "", cap = "Chỉ 1 viên Gia Trì", source = "scripts/enums/hh_enchant.lua" },
    { code = "durability_immune_amount", name = "Gia Trì V", family = "Gia Trì", tier = "V", slot = "Trang bị có độ bền", effect_key = "durabilityImmune", image_id = "GT05", min = 0, max = 0, step = 0, scale = 1, unit = "%", fixed = true, fixed_value = 0, display = "Đồ không mất độ bền", exclusive_group = "durability_regen", cap = "Chỉ 1 viên Gia Trì", source = "scripts/enums/hh_enchant.lua" },
    { code = "add_max_use_armor_01", name = "Hộ Giáp I", family = "Hộ Giáp", tier = "I", slot = "Giáp", effect_key = "armorDurability", image_id = "HG01", min = 200, max = 500, step = 100, scale = 1, unit = "độ bền", fixed = false, fixed_value = 0, display = "+200-500 độ bền giáp", exclusive_group = "", cap = "Chỉ 1 viên Hộ Giáp", source = "scripts/enums/hh_enchant.lua" },
    { code = "add_max_use_armor_02", name = "Hộ Giáp II", family = "Hộ Giáp", tier = "II", slot = "Giáp", effect_key = "armorDurability", image_id = "HG02", min = 400, max = 1000, step = 100, scale = 1, unit = "độ bền", fixed = false, fixed_value = 0, display = "+400-1000 độ bền giáp", exclusive_group = "", cap = "Chỉ 1 viên Hộ Giáp", source = "scripts/enums/hh_enchant.lua" },
    { code = "add_max_use_armor_03", name = "Hộ Giáp III", family = "Hộ Giáp", tier = "III", slot = "Giáp", effect_key = "armorDurability", image_id = "HG03", min = 800, max = 2500, step = 100, scale = 1, unit = "độ bền", fixed = false, fixed_value = 0, display = "+800-2500 độ bền giáp", exclusive_group = "", cap = "Chỉ 1 viên Hộ Giáp", source = "scripts/enums/hh_enchant.lua" },
    { code = "add_max_use_armor_04", name = "Hộ Giáp IV", family = "Hộ Giáp", tier = "IV", slot = "Giáp", effect_key = "armorDurability", image_id = "HG04", min = 2000, max = 5000, step = 100, scale = 1, unit = "độ bền", fixed = false, fixed_value = 0, display = "+2000-5000 độ bền giáp", exclusive_group = "armor_durability", cap = "Chỉ 1 viên Hộ Giáp", source = "scripts/enums/hh_enchant.lua" },
    { code = "armor_immune_amount", name = "Hộ Giáp V", family = "Hộ Giáp", tier = "V", slot = "Giáp", effect_key = "armorDurability", image_id = "HG05", min = 0, max = 0, step = 0, scale = 1, unit = "độ bền", fixed = true, fixed_value = 0, display = "Giáp không mất độ bền", exclusive_group = "armor_durability", cap = "Chỉ 1 viên Hộ Giáp", source = "scripts/enums/hh_enchant.lua" },
    { code = "true_damage_small", name = "Xuyên Giáp I", family = "Xuyên Giáp", tier = "I", slot = "Vũ khí", effect_key = "trueDamageNum", image_id = "XG01", min = 1, max = 5, step = 1, scale = 1, unit = "%", fixed = false, fixed_value = 0, display = "1-5% ST đòn chính bỏ qua giáp", exclusive_group = "armor_pierce", cap = "Tổng 40%", source = "scripts/enums/hh_enchant.lua" },
    { code = "true_damage_med", name = "Xuyên Giáp II", family = "Xuyên Giáp", tier = "II", slot = "Vũ khí", effect_key = "trueDamageNum", image_id = "XG02", min = 4, max = 10, step = 1, scale = 1, unit = "%", fixed = false, fixed_value = 0, display = "4-10% ST đòn chính bỏ qua giáp", exclusive_group = "armor_pierce", cap = "Tổng 40%", source = "scripts/enums/hh_enchant.lua" },
    { code = "true_damage_big", name = "Xuyên Giáp III", family = "Xuyên Giáp", tier = "III", slot = "Vũ khí", effect_key = "trueDamageNum", image_id = "XG03", min = 8, max = 15, step = 1, scale = 1, unit = "%", fixed = false, fixed_value = 0, display = "8-15% ST đòn chính bỏ qua giáp", exclusive_group = "armor_pierce", cap = "Tổng 40%", source = "scripts/enums/hh_enchant.lua" },
    { code = "true_damage_special", name = "Xuyên Giáp IV", family = "Xuyên Giáp", tier = "IV", slot = "Vũ khí", effect_key = "trueDamageNum", image_id = "XG04", min = 12, max = 20, step = 1, scale = 1, unit = "%", fixed = false, fixed_value = 0, display = "12-20% ST đòn chính bỏ qua giáp", exclusive_group = "armor_pierce", cap = "Tổng 40%", source = "scripts/enums/hh_enchant.lua" },
    { code = "true_damage_tier_v", name = "Xuyên Giáp V", family = "Xuyên Giáp", tier = "V", slot = "Vũ khí", effect_key = "trueDamageNum", image_id = "XG05", min = 16, max = 25, step = 1, scale = 1, unit = "%", fixed = false, fixed_value = 0, display = "16-25% ST đòn chính bỏ qua giáp", exclusive_group = "armor_pierce", cap = "Tổng 40%", source = "scripts/enums/hh_enchant.lua" },
    { code = "blood_outburst", name = "Nghịch Cảnh-Huyết Chiến", family = "Nghịch Cảnh", tier = "UTILITY", slot = "Vũ khí", effect_key = "bloodOutburst", image_id = "U01", min = 0, max = 0, step = 0, scale = 1, unit = "%", fixed = true, fixed_value = 0, display = "Tối đa 50%", exclusive_group = "adversity", cap = "Chỉ 1 loại Nghịch Cảnh", source = "scripts/enums/hh_enchant.lua" },
    { code = "spirit_fade", name = "Nghịch Cảnh-Tinh Thần", family = "Nghịch Cảnh", tier = "UTILITY", slot = "Vũ khí", effect_key = "spiritFade", image_id = "U03", min = 0, max = 0, step = 0, scale = 1, unit = "%", fixed = true, fixed_value = 0, display = "Tối đa 50%", exclusive_group = "adversity", cap = "Chỉ 1 loại Nghịch Cảnh", source = "scripts/enums/hh_enchant.lua" },
    { code = "hunger_assault", name = "Nghịch Cảnh-Đoạn Cốc", family = "Nghịch Cảnh", tier = "UTILITY", slot = "Vũ khí", effect_key = "hungerAssault", image_id = "U02", min = 0, max = 0, step = 0, scale = 1, unit = "%", fixed = true, fixed_value = 0, display = "Tối đa 50%", exclusive_group = "adversity", cap = "Chỉ 1 loại Nghịch Cảnh", source = "scripts/enums/hh_enchant.lua" },
    { code = "add_immune_cold", name = "Huyền Vũ-Hàn", family = "Huyền Vũ", tier = "II", slot = "Mọi trang bị", effect_key = "immuneCold", image_id = "HV05", min = 0, max = 0, step = 0, scale = 1, unit = "%", fixed = true, fixed_value = 0, display = "Miễn lạnh cóng", exclusive_group = "", cap = "", source = "scripts/enums/hh_enchant.lua" },
    { code = "add_immune_hot", name = "Huyền Vũ-Hỏa", family = "Huyền Vũ", tier = "II", slot = "Mọi trang bị", effect_key = "immuneHot", image_id = "HV03", min = 0, max = 0, step = 0, scale = 1, unit = "%", fixed = true, fixed_value = 0, display = "Miễn quá nhiệt", exclusive_group = "", cap = "", source = "scripts/enums/hh_enchant.lua" },
    { code = "add_immune_poison", name = "Huyền Vũ-Độc", family = "Huyền Vũ", tier = "II", slot = "Mọi trang bị", effect_key = "immunePoison", image_id = "HV06", min = 0, max = 0, step = 0, scale = 1, unit = "%", fixed = true, fixed_value = 0, display = "Miễn trúng độc", exclusive_group = "", cap = "", source = "scripts/enums/hh_enchant.lua" },
    { code = "add_immune_freeze", name = "Huyền Vũ-Băng", family = "Huyền Vũ", tier = "II", slot = "Mọi trang bị", effect_key = "immuneFreeze", image_id = "HV01", min = 0, max = 0, step = 0, scale = 1, unit = "%", fixed = true, fixed_value = 0, display = "Miễn đóng băng", exclusive_group = "", cap = "", source = "scripts/enums/hh_enchant.lua" },
    { code = "immunity_moisture", name = "Huyền Vũ-Thủy", family = "Huyền Vũ", tier = "II", slot = "Mọi trang bị", effect_key = "immunityMoisture", image_id = "HV07", min = 0, max = 0, step = 0, scale = 1, unit = "%", fixed = true, fixed_value = 0, display = "Miễn ẩm ướt", exclusive_group = "", cap = "", source = "scripts/enums/hh_enchant.lua" },
    { code = "immunity_reduce_speed", name = "Huyền Vũ-Hành", family = "Huyền Vũ", tier = "II", slot = "Mọi trang bị", effect_key = "immuneReduceSpeed + porter", image_id = "HV02", min = 0, max = 0, step = 0, scale = 1, unit = "%", fixed = true, fixed_value = 0, display = "Miễn làm chậm", exclusive_group = "", cap = "", source = "scripts/enums/hh_enchant.lua" },
    { code = "immune_sleep", name = "Huyền Vũ-Thần", family = "Huyền Vũ", tier = "II", slot = "Mọi trang bị", effect_key = "immunitySleep", image_id = "HV04", min = 0, max = 0, step = 0, scale = 1, unit = "%", fixed = true, fixed_value = 0, display = "Miễn ru ngủ", exclusive_group = "", cap = "", source = "scripts/enums/hh_enchant.lua" },
    { code = "immune_debuff", name = "Huyền Vũ-Tam Tai", family = "Huyền Vũ", tier = "III", slot = "Mọi trang bị", effect_key = "immuneHot + immuneCold + immunityMoisture", image_id = "B03", min = 0, max = 0, step = 0, scale = 1, unit = "%", fixed = true, fixed_value = 0, display = "Miễn nóng, lạnh và ướt", exclusive_group = "", cap = "", source = "scripts/enums/hh_enchant.lua" },
    { code = "immune_debuff_2", name = "Huyền Vũ-Tứ Ách", family = "Huyền Vũ", tier = "III", slot = "Mọi trang bị", effect_key = "immuneFreeze + immunePoison + immuneReduceSpeed + immunitySleep", image_id = "B05", min = 0, max = 0, step = 0, scale = 1, unit = "%", fixed = true, fixed_value = 0, display = "Miễn băng, độc, chậm và ngủ", exclusive_group = "", cap = "", source = "scripts/enums/hh_enchant.lua" },
    { code = "special_zqrf", name = "Huyền Vũ-Vạn Pháp", family = "Huyền Vũ", tier = "IV", slot = "Mọi trang bị", effect_key = "allStatusImmunity", image_id = "B16", min = 0, max = 0, step = 0, scale = 1, unit = "%", fixed = true, fixed_value = 0, display = "Giữ nguyên", exclusive_group = "", cap = "", source = "scripts/enums/hh_enchant.lua" },
    { code = "equip_burn_i", name = "Phần Thiên I", family = "Phần Thiên", tier = "I", slot = "Vũ khí", effect_key = "burnMaxHealthPercent", image_id = "PT01", min = 1, max = 5, step = 1, scale = 10, unit = "%", fixed = false, fixed_value = 0, display = "0,1-0,5% máu tối đa/giây", exclusive_group = "burn", cap = "Không cộng tầng; duy trì 3 giây", source = "scripts/enums/hh_enchant.lua + scripts/combat/hh_combat_status.lua" },
    { code = "equip_burn_ii", name = "Phần Thiên II", family = "Phần Thiên", tier = "II", slot = "Vũ khí", effect_key = "burnMaxHealthPercent", image_id = "PT02", min = 4, max = 10, step = 1, scale = 10, unit = "%", fixed = false, fixed_value = 0, display = "0,4-1% máu tối đa/giây", exclusive_group = "burn", cap = "Không cộng tầng; duy trì 3 giây", source = "scripts/enums/hh_enchant.lua + scripts/combat/hh_combat_status.lua" },
    { code = "equip_burn_iii", name = "Phần Thiên III", family = "Phần Thiên", tier = "III", slot = "Vũ khí", effect_key = "burnMaxHealthPercent", image_id = "PT03", min = 8, max = 15, step = 1, scale = 10, unit = "%", fixed = false, fixed_value = 0, display = "0,8-1,5% máu tối đa/giây", exclusive_group = "burn", cap = "Không cộng tầng; duy trì 3 giây", source = "scripts/enums/hh_enchant.lua + scripts/combat/hh_combat_status.lua" },
    { code = "equip_burn_iv", name = "Phần Thiên IV", family = "Phần Thiên", tier = "IV", slot = "Vũ khí", effect_key = "burnMaxHealthPercent", image_id = "PT04", min = 12, max = 25, step = 1, scale = 10, unit = "%", fixed = false, fixed_value = 0, display = "1,2-2,5% máu tối đa/giây", exclusive_group = "burn", cap = "Không cộng tầng; duy trì 3 giây", source = "scripts/enums/hh_enchant.lua + scripts/combat/hh_combat_status.lua" },
    { code = "equip_burn_v", name = "Phần Thiên V", family = "Phần Thiên", tier = "V", slot = "Vũ khí", effect_key = "burnMaxHealthPercent", image_id = "PT05", min = 20, max = 40, step = 1, scale = 10, unit = "%", fixed = false, fixed_value = 0, display = "2-4% máu tối đa/giây", exclusive_group = "burn", cap = "Không cộng tầng; duy trì 3 giây", source = "scripts/enums/hh_enchant.lua + scripts/combat/hh_combat_status.lua" },
    { code = "atk_add_poison_small", name = "Vạn Độc I", family = "Vạn Độc", tier = "I", slot = "Vũ khí", effect_key = "atkAddPoisonChance", image_id = "VD01", min = 5, max = 10, step = 1, scale = 1, unit = "%", fixed = false, fixed_value = 0, display = "5-10% xác suất", exclusive_group = "poison", cap = "Tổng xác suất từ đá 80%", source = "scripts/enums/hh_enchant.lua" },
    { code = "atk_add_poison_med", name = "Vạn Độc II", family = "Vạn Độc", tier = "II", slot = "Vũ khí", effect_key = "atkAddPoisonChance", image_id = "VD02", min = 8, max = 20, step = 1, scale = 1, unit = "%", fixed = false, fixed_value = 0, display = "8-20% xác suất", exclusive_group = "poison", cap = "Tổng xác suất từ đá 80%", source = "scripts/enums/hh_enchant.lua" },
    { code = "atk_add_poison_big", name = "Vạn Độc III", family = "Vạn Độc", tier = "III", slot = "Vũ khí", effect_key = "atkAddPoisonChance", image_id = "VD03", min = 16, max = 30, step = 1, scale = 1, unit = "%", fixed = false, fixed_value = 0, display = "16-30% xác suất", exclusive_group = "poison", cap = "Tổng xác suất từ đá 80%", source = "scripts/enums/hh_enchant.lua" },
    { code = "atk_add_poison_special", name = "Vạn Độc IV", family = "Vạn Độc", tier = "IV", slot = "Vũ khí", effect_key = "atkAddPoisonChance", image_id = "VD04", min = 24, max = 40, step = 1, scale = 1, unit = "%", fixed = false, fixed_value = 0, display = "24-40% xác suất", exclusive_group = "poison", cap = "Tổng xác suất từ đá 80%", source = "scripts/enums/hh_enchant.lua" },
    { code = "atk_add_poison_tier_v", name = "Vạn Độc V", family = "Vạn Độc", tier = "V", slot = "Vũ khí", effect_key = "atkAddPoisonChance", image_id = "VD05", min = 32, max = 50, step = 1, scale = 1, unit = "%", fixed = false, fixed_value = 0, display = "32-50% xác suất", exclusive_group = "poison", cap = "Tổng xác suất từ đá 80%", source = "scripts/enums/hh_enchant.lua" },
    { code = "atk_add_freeze_small", name = "Huyền Băng I", family = "Huyền Băng", tier = "I", slot = "Vũ khí", effect_key = "atkChanceAddFreeze", image_id = "HB01", min = 1, max = 5, step = 1, scale = 1, unit = "%", fixed = false, fixed_value = 0, display = "1-5% xác suất", exclusive_group = "freeze", cap = "Tổng xác suất từ đá 40%", source = "scripts/enums/hh_enchant.lua" },
    { code = "atk_add_freeze_med", name = "Huyền Băng II", family = "Huyền Băng", tier = "II", slot = "Vũ khí", effect_key = "atkChanceAddFreeze", image_id = "HB02", min = 4, max = 10, step = 1, scale = 1, unit = "%", fixed = false, fixed_value = 0, display = "4-10% xác suất", exclusive_group = "freeze", cap = "Tổng xác suất từ đá 40%", source = "scripts/enums/hh_enchant.lua" },
    { code = "atk_add_freeze_big", name = "Huyền Băng III", family = "Huyền Băng", tier = "III", slot = "Vũ khí", effect_key = "atkChanceAddFreeze", image_id = "HB03", min = 8, max = 15, step = 1, scale = 1, unit = "%", fixed = false, fixed_value = 0, display = "8-15% xác suất", exclusive_group = "freeze", cap = "Tổng xác suất từ đá 40%", source = "scripts/enums/hh_enchant.lua" },
    { code = "atk_add_freeze_special", name = "Huyền Băng IV", family = "Huyền Băng", tier = "IV", slot = "Vũ khí", effect_key = "atkChanceAddFreeze", image_id = "HB04", min = 12, max = 20, step = 1, scale = 1, unit = "%", fixed = false, fixed_value = 0, display = "12-20% xác suất", exclusive_group = "freeze", cap = "Tổng xác suất từ đá 40%", source = "scripts/enums/hh_enchant.lua" },
    { code = "atk_add_freeze_tier_v", name = "Huyền Băng V", family = "Huyền Băng", tier = "V", slot = "Vũ khí", effect_key = "atkChanceAddFreeze", image_id = "HB05", min = 16, max = 25, step = 1, scale = 1, unit = "%", fixed = false, fixed_value = 0, display = "16-25% xác suất", exclusive_group = "freeze", cap = "Tổng xác suất từ đá 40%", source = "scripts/enums/hh_enchant.lua" },
    { code = "equip_max_health_i", name = "Sinh Mệnh I", family = "Sinh Mệnh", tier = "I", slot = "Giáp hoặc phụ kiện", effect_key = "equipMaxHealthPercent", image_id = "SM01", min = 1, max = 7, step = 2, scale = 1, unit = "%", fixed = false, fixed_value = 0, display = "+1-7% máu tối đa", exclusive_group = "max_health", cap = "Tổng 80%", source = "scripts/components/hh_dungeon_effects.lua" },
    { code = "equip_max_health_ii", name = "Sinh Mệnh II", family = "Sinh Mệnh", tier = "II", slot = "Giáp hoặc phụ kiện", effect_key = "equipMaxHealthPercent", image_id = "SM02", min = 5, max = 15, step = 2, scale = 1, unit = "%", fixed = false, fixed_value = 0, display = "+5-15% máu tối đa", exclusive_group = "max_health", cap = "Tổng 80%", source = "scripts/components/hh_dungeon_effects.lua" },
    { code = "equip_max_health_iii", name = "Sinh Mệnh III", family = "Sinh Mệnh", tier = "III", slot = "Giáp hoặc phụ kiện", effect_key = "equipMaxHealthPercent", image_id = "SM03", min = 11, max = 21, step = 2, scale = 1, unit = "%", fixed = false, fixed_value = 0, display = "+11-21% máu tối đa", exclusive_group = "max_health", cap = "Tổng 80%", source = "scripts/components/hh_dungeon_effects.lua" },
    { code = "equip_max_health_iv", name = "Sinh Mệnh IV", family = "Sinh Mệnh", tier = "IV", slot = "Giáp hoặc phụ kiện", effect_key = "equipMaxHealthPercent", image_id = "SM04", min = 17, max = 29, step = 2, scale = 1, unit = "%", fixed = false, fixed_value = 0, display = "+17-29% máu tối đa", exclusive_group = "max_health", cap = "Tổng 80%", source = "scripts/components/hh_dungeon_effects.lua" },
    { code = "equip_max_health_v", name = "Sinh Mệnh V", family = "Sinh Mệnh", tier = "V", slot = "Giáp hoặc phụ kiện", effect_key = "equipMaxHealthPercent", image_id = "SM05", min = 25, max = 35, step = 2, scale = 1, unit = "%", fixed = false, fixed_value = 0, display = "+25-35% máu tối đa", exclusive_group = "max_health", cap = "Tổng 80%", source = "scripts/components/hh_dungeon_effects.lua" },
    { code = "equip_health_regen_i", name = "Sinh Cơ I", family = "Sinh Cơ", tier = "I", slot = "Giáp hoặc phụ kiện", effect_key = "equipHealthRegen", image_id = "SC01", min = 0, max = 0, step = 0, scale = 1, unit = "HP/giây", fixed = true, fixed_value = 0.2, display = "0,2 HP/s", exclusive_group = "health_regen", cap = "Tổng 2 HP/s", source = "scripts/components/hh_dungeon_effects.lua + scripts/components/ttk_alchemy_effects.lua" },
    { code = "equip_health_regen_ii", name = "Sinh Cơ II", family = "Sinh Cơ", tier = "II", slot = "Giáp hoặc phụ kiện", effect_key = "equipHealthRegen", image_id = "SC02", min = 0, max = 0, step = 0, scale = 1, unit = "HP/giây", fixed = true, fixed_value = 0.4, display = "0,4 HP/s", exclusive_group = "health_regen", cap = "Tổng 2 HP/s", source = "scripts/components/hh_dungeon_effects.lua + scripts/components/ttk_alchemy_effects.lua" },
    { code = "equip_health_regen_iii", name = "Sinh Cơ III", family = "Sinh Cơ", tier = "III", slot = "Giáp hoặc phụ kiện", effect_key = "equipHealthRegen", image_id = "SC03", min = 0, max = 0, step = 0, scale = 1, unit = "HP/giây", fixed = true, fixed_value = 0.7, display = "0,7 HP/s", exclusive_group = "health_regen", cap = "Tổng 2 HP/s", source = "scripts/components/hh_dungeon_effects.lua + scripts/components/ttk_alchemy_effects.lua" },
    { code = "equip_health_regen_iv", name = "Sinh Cơ IV", family = "Sinh Cơ", tier = "IV", slot = "Giáp hoặc phụ kiện", effect_key = "equipHealthRegen", image_id = "SC04", min = 0, max = 0, step = 0, scale = 1, unit = "HP/giây", fixed = true, fixed_value = 1, display = "1 HP/s", exclusive_group = "health_regen", cap = "Tổng 2 HP/s", source = "scripts/components/hh_dungeon_effects.lua + scripts/components/ttk_alchemy_effects.lua" },
    { code = "equip_health_regen_v", name = "Sinh Cơ V", family = "Sinh Cơ", tier = "V", slot = "Giáp hoặc phụ kiện", effect_key = "equipHealthRegen", image_id = "SC05", min = 0, max = 0, step = 0, scale = 1, unit = "HP/giây", fixed = true, fixed_value = 1.5, display = "1,5 HP/s", exclusive_group = "health_regen", cap = "Tổng 2 HP/s", source = "scripts/components/hh_dungeon_effects.lua + scripts/components/ttk_alchemy_effects.lua" },
    { code = "equip_max_mana_i", name = "Linh Hải I", family = "Linh Hải", tier = "I", slot = "Mũ hoặc phụ kiện", effect_key = "equipMaxMana", image_id = "LH01", min = 5, max = 10, step = 1, scale = 1, unit = "Linh Lực", fixed = false, fixed_value = 0, display = "+5-10 Linh Lực", exclusive_group = "mana_pool", cap = "Tổng từ đá +300 mana", source = "scripts/components/hh_mana.lua" },
    { code = "equip_max_mana_ii", name = "Linh Hải II", family = "Linh Hải", tier = "II", slot = "Mũ hoặc phụ kiện", effect_key = "equipMaxMana", image_id = "LH02", min = 8, max = 20, step = 1, scale = 1, unit = "Linh Lực", fixed = false, fixed_value = 0, display = "+8-20 Linh Lực", exclusive_group = "mana_pool", cap = "Tổng từ đá +300 mana", source = "scripts/components/hh_mana.lua" },
    { code = "equip_max_mana_iii", name = "Linh Hải III", family = "Linh Hải", tier = "III", slot = "Mũ hoặc phụ kiện", effect_key = "equipMaxMana", image_id = "LH03", min = 16, max = 30, step = 1, scale = 1, unit = "Linh Lực", fixed = false, fixed_value = 0, display = "+16-30 Linh Lực", exclusive_group = "mana_pool", cap = "Tổng từ đá +300 mana", source = "scripts/components/hh_mana.lua" },
    { code = "equip_max_mana_iv", name = "Linh Hải IV", family = "Linh Hải", tier = "IV", slot = "Mũ hoặc phụ kiện", effect_key = "equipMaxMana", image_id = "LH04", min = 24, max = 45, step = 1, scale = 1, unit = "Linh Lực", fixed = false, fixed_value = 0, display = "+24-45 Linh Lực", exclusive_group = "mana_pool", cap = "Tổng từ đá +300 mana", source = "scripts/components/hh_mana.lua" },
    { code = "equip_max_mana_v", name = "Linh Hải V", family = "Linh Hải", tier = "V", slot = "Mũ hoặc phụ kiện", effect_key = "equipMaxMana", image_id = "LH05", min = 36, max = 65, step = 1, scale = 1, unit = "Linh Lực", fixed = false, fixed_value = 0, display = "+36-65 Linh Lực", exclusive_group = "mana_pool", cap = "Tổng từ đá +300 mana", source = "scripts/components/hh_mana.lua" },
    { code = "equip_mana_regen_i", name = "Tụ Linh I", family = "Tụ Linh", tier = "I", slot = "Mũ hoặc phụ kiện", effect_key = "equipManaRegen", image_id = "TL01", min = 5, max = 10, step = 1, scale = 100, unit = "Linh Lực/giây", fixed = false, fixed_value = 0, display = "+0,05-0,1 Linh Lực/giây", exclusive_group = "mana_regen", cap = "Tổng từ đá +3 mana/giây", source = "scripts/components/hh_mana.lua" },
    { code = "equip_mana_regen_ii", name = "Tụ Linh II", family = "Tụ Linh", tier = "II", slot = "Mũ hoặc phụ kiện", effect_key = "equipManaRegen", image_id = "TL02", min = 8, max = 20, step = 1, scale = 100, unit = "Linh Lực/giây", fixed = false, fixed_value = 0, display = "+0,08-0,2 Linh Lực/giây", exclusive_group = "mana_regen", cap = "Tổng từ đá +3 mana/giây", source = "scripts/components/hh_mana.lua" },
    { code = "equip_mana_regen_iii", name = "Tụ Linh III", family = "Tụ Linh", tier = "III", slot = "Mũ hoặc phụ kiện", effect_key = "equipManaRegen", image_id = "TL03", min = 16, max = 35, step = 1, scale = 100, unit = "Linh Lực/giây", fixed = false, fixed_value = 0, display = "+0,16-0,35 Linh Lực/giây", exclusive_group = "mana_regen", cap = "Tổng từ đá +3 mana/giây", source = "scripts/components/hh_mana.lua" },
    { code = "equip_mana_regen_iv", name = "Tụ Linh IV", family = "Tụ Linh", tier = "IV", slot = "Mũ hoặc phụ kiện", effect_key = "equipManaRegen", image_id = "TL04", min = 28, max = 60, step = 1, scale = 100, unit = "Linh Lực/giây", fixed = false, fixed_value = 0, display = "+0,28-0,6 Linh Lực/giây", exclusive_group = "mana_regen", cap = "Tổng từ đá +3 mana/giây", source = "scripts/components/hh_mana.lua" },
    { code = "equip_mana_regen_v", name = "Tụ Linh V", family = "Tụ Linh", tier = "V", slot = "Mũ hoặc phụ kiện", effect_key = "equipManaRegen", image_id = "TL05", min = 50, max = 100, step = 1, scale = 100, unit = "Linh Lực/giây", fixed = false, fixed_value = 0, display = "+0,5-1 Linh Lực/giây", exclusive_group = "mana_regen", cap = "Tổng từ đá +3 mana/giây", source = "scripts/components/hh_mana.lua" },
}

for _, row in ipairs(rows) do
    assert(M.by_code[row.code] == nil, "duplicate affix code: " .. row.code)
    M.by_code[row.code] = row
    M.rows[#M.rows + 1] = row
    if M.by_family[row.family] == nil then
        M.by_family[row.family] = {}
        M.families[#M.families + 1] = row.family
    end
    local family = M.by_family[row.family]
    family[#family + 1] = row
end

local function Decimal(value, scale)
    local integer = math.floor(value / scale)
    local fraction = value % scale
    if fraction == 0 then return tostring(integer) end
    local digits = scale == 100 and 2 or 1
    local text = string.format("%0" .. digits .. "d", fraction)
    text = string.gsub(text, "0+$", "")
    return tostring(integer) .. "," .. text
end

function M.ValueText(code, value)
    local row = M.by_code[code]
    if row == nil then return nil end
    if row.fixed then return row.display end
    if type(value) ~= "number" then return nil end
    local suffix = row.unit == "%" and "%" or (" " .. row.unit)
    return Decimal(value, row.scale) .. suffix
end

function M.Format(code, value)
    local row = M.by_code[code]
    local text = M.ValueText(code, value)
    return row ~= nil and text ~= nil and (row.name .. ": " .. text) or nil
end

function M.IsValidValue(code, value)
    local row = M.by_code[code]
    if row == nil or type(value) ~= "number" or value ~= math.floor(value) then return false end
    if row.fixed then return value == 0 end
    return value >= row.min and value <= row.max and (value - row.min) % row.step == 0
end

return M
