local G=GLOBAL or _G;G.setfenv(1,G)
TheWorld:DoTaskInTime(3,function()
 local m=assert(TheWorld.components.hn_dungeon_manager);assert(m:FindArena())
 local chest=SpawnPrefab('minotaurchest');m:Track(chest);chest.Transform:SetPosition(m.dungeon_center_x,0,m.dungeon_center_z+4)
 local reward=SpawnPrefab('xd_lingshi1');reward.components.stackable:SetStackSize(5);m:Track(reward);chest.components.container:GiveItem(reward)
 local personal=SpawnPrefab('xd_lingshi1');personal.components.stackable:SetStackSize(7);chest.components.container:GiveItem(personal)
 assert(reward.components.hn_owned.claimed,'personal units lost provenance during merge')
 local split=reward.components.stackable:Get(3)
 assert(split.components.hn_owned.claimed and split.components.hn_owned.run_id==m.run_epoch)
 split.components.inventoryitem:OnDropped()
 split.Transform:SetPosition(m.run_gate_x,0,m.run_gate_z)
 m:Reset('stack regression');assert(reward:IsValid() and split:IsValid() and reward.components.stackable:StackSize()+split.components.stackable:StackSize()==12)
 print('HN_QA_PASS','mixed stack preserves 12 units after split and cleanup')
 local bag=SpawnPrefab('hn_recovery_bag');bag.components.hn_recovery.recovery_id='hn-qa-persist';bag.components.hn_recovery.owner='hn-qa'
 bag.Transform:SetPosition(m.run_gate_x,0,m.run_gate_z)
 local gem=SpawnPrefab('bluegem');bag.components.container:GiveItem(gem)
 m.state='IN_PROGRESS';local mob=SpawnPrefab('hn_dungeon_pig');m:Track(mob);mob.Transform:SetPosition(m.dungeon_center_x,0,m.dungeon_center_z+4)
 c_save();TheWorld:DoTaskInTime(2,function() print('HN_QA_DONE','saved active run and recovery marker') end)
end)

