-- Final approved catalog. See docs/SLOT_REWARDS_FINAL.md.
return {version="1.6.4", groups={
    {["key"]="good",["id"]="hiem",["name"]="Hiếm",["weight"]=0.5,bundles={
        {["name"]="Dreadstone",["weight"]=1,["items"]={{["prefab"]="dreadstonehat",["count"]=1},{["prefab"]="armordreadstone",["count"]=1}},["id"]="hiem_01"},
        {["name"]="Nguyệt thực",["weight"]=1,["items"]={{["prefab"]="lunarplanthat",["count"]=1},{["prefab"]="armor_lunarplant",["count"]=1}},["id"]="hiem_02"},
        {["name"]="Hư không",["weight"]=1,["items"]={{["prefab"]="voidclothhat",["count"]=1},{["prefab"]="armor_voidcloth",["count"]=1},{["prefab"]="voidcloth_scythe",["count"]=1},{["prefab"]="voidcloth_umbrella",["count"]=1}},["id"]="hiem_03"},
        {["name"]="Trượng dịch chuyển",["weight"]=1,["items"]={{["prefab"]="orangestaff",["count"]=1},{["prefab"]="xd_luoshen_huayin",["count"]=3,["legacy"]="ttk_luoshen_huayin"}},["id"]="hiem_04"},
        {["name"]="Tử Xá Diện Giáp",["weight"]=1,["items"]={{["prefab"]="xd_zcmj",["count"]=1,["legacy"]="ttk_zcmj"},{["prefab"]="xd_pog_tail",["count"]=3,["legacy"]="ttk_pog_tail"}},["id"]="hiem_05"},
        {["name"]="Tà Sát Hộ Giáp",["weight"]=1,["items"]={{["prefab"]="xd_xshj",["count"]=1,["legacy"]="ttk_xshj"},{["prefab"]="xd_spider_leg",["count"]=2,["legacy"]="ttk_spider_leg"}},["id"]="hiem_06"},
        {["name"]="Vương miện và Giáp Xương",["weight"]=1,["items"]={{["prefab"]="alterguardianhat",["count"]=1},{["prefab"]="armorskeleton",["count"]=1}},["id"]="hiem_07"},
        {["name"]="Trượng ngọc",["weight"]=1,["items"]={{["prefab"]="yellowstaff",["count"]=1},{["prefab"]="opalstaff",["count"]=1},{["prefab"]="greenstaff",["count"]=1}},["id"]="hiem_08"},
        {["name"]="Linh thực cay",["weight"]=1,["items"]={{["prefab"]="jellybean_spice_chili",["count"]=2},{["prefab"]="seafoodgumbo_spice_chili",["count"]=2},{["prefab"]="flowersalad_spice_chili",["count"]=2}},["id"]="hiem_09"},
        {["name"]="Thạch dê điện",["weight"]=1,["items"]={{["prefab"]="voltgoatjelly",["count"]=7},{["prefab"]="xd_luoxiang_pengrou",["count"]=2,["legacy"]="ttk_luoxiang_pengrou"}},["id"]="hiem_10"},
        {["name"]="Lục Mạch Thần Kiếm",["weight"]=1,["items"]={{["prefab"]="lucmachthankiem",["count"]=1},{["prefab"]="xd_lc_lmg_seed",["count"]=3,["legacy"]="ttk_lc_lmg_seed"}},["id"]="hiem_11"},
        {["name"]="Tinh La Kiếm",["weight"]=1,["items"]={{["prefab"]="ttk_tinhlakiem",["count"]=1},{["prefab"]="xd_luoshen_qingshu",["count"]=2,["legacy"]="ttk_luoshen_qingshu"}},["id"]="hiem_12"},
        {["name"]="Phần Thiên Kiếm",["weight"]=0.5,["items"]={{["prefab"]="xd_ftj",["count"]=1}},["id"]="hiem_13"},
        {["name"]="Tôn Hồn Phiên",["weight"]=0.5,["items"]={{["prefab"]="xd_zhf",["count"]=1}},["id"]="hiem_14"},
        {["name"]="Tẩy Tủy Hoàn",["weight"]=1,["items"]={{["prefab"]="xd_danyao_xs",["count"]=1}},["id"]="hiem_15"},
        {["name"]="Hóa Tinh Đan",["weight"]=1,["items"]={{["prefab"]="xd_danyao_hj",["count"]=1}},["id"]="hiem_16"},
        {["name"]="Vân Trung Đan",["weight"]=1,["items"]={{["prefab"]="xd_danyao_yz",["count"]=1}},["id"]="hiem_17"},
        {["name"]="Nguyên liệu quý",["weight"]=1,["items"]={{["prefab"]="xd_fs",["count"]=1},{["prefab"]="xd_qlr",["count"]=1}},["id"]="hiem_18"},
        {["name"]="Huyền Tinh quý",["weight"]=1,["items"]={{["prefab"]="wb_enhancegem",["count"]=1}},["id"]="hiem_19"},
        {["name"]="Bùa cường hóa",["weight"]=1,["items"]={{["prefab"]="nn_magicpaper",["count"]=2},{["prefab"]="wb_strengthen_strengthen_protectpaper",["count"]=1}},["id"]="hiem_20"},
        {["name"]="Chỉnh thuộc tính",["weight"]=1,["items"]={{["prefab"]="ac_refreshstone",["count"]=3},{["prefab"]="ad_cleanstone",["count"]=2}},["id"]="hiem_21"},
        {["name"]="Cuộn cường hóa +6",["weight"]=1,["items"]={{["prefab"]="wb_strengthen_strengthen_6_levelpaper",["count"]=1}},["id"]="hiem_22"},
        {["name"]="Shadow Atrium",["weight"]=1,["items"]={{["prefab"]="shadowheart",["count"]=1}},["id"]="hiem_23"},
        {["name"]="Hoa Hồng Ám Ảnh",["weight"]=1,["items"]={{["prefab"]="xd_aymg",["count"]=1}},["id"]="hiem_24"},
    }},
    {["key"]="ok",["id"]="kha",["name"]="Khá",["weight"]=1.5,bundles={
        {["name"]="Hạt Giống Phủ Băng",["weight"]=1,["items"]={{["prefab"]="xd_lc_hsc_seed",["count"]=3,["legacy"]="ttk_lc_hsc_seed"}},["id"]="kha_01"},
        {["name"]="Đá Sa Mạc",["weight"]=1,["items"]={{["prefab"]="townportaltalisman",["count"]=3}},["id"]="kha_02"},
        {["name"]="Ngư Long Đăng",["weight"]=1,["items"]={{["prefab"]="xd_sudaji_redlantern",["count"]=1,["legacy"]="ttk_ngulongdang"},{["prefab"]="xd_lingshi1",["count"]=20,["legacy"]="ttk_lingshi1"}},["id"]="kha_03"},
        {["name"]="Chưởng Thiên Bình",["weight"]=1,["items"]={{["prefab"]="xd_ztp",["count"]=1,["legacy"]="ttk_chuongthienbinh"},{["prefab"]="xd_luoshen_huazhong",["count"]=2,["legacy"]="ttk_luoshen_huazhong"}},["id"]="kha_04"},
        {["name"]="Di tích",["weight"]=1,["items"]={{["prefab"]="armorruins",["count"]=3},{["prefab"]="ruinshat",["count"]=3},{["prefab"]="thulecite",["count"]=3}},["id"]="kha_05"},
        {["name"]="Mùa mưa",["weight"]=1,["items"]={{["prefab"]="eyebrellahat",["count"]=2},{["prefab"]="xd_luoxiang_pengrou",["count"]=2,["legacy"]="ttk_luoxiang_pengrou"}},["id"]="kha_06"},
        {["name"]="Linh thực",["weight"]=1,["items"]={{["prefab"]="jellybean",["count"]=10},{["prefab"]="xd_luoshen_qingshu",["count"]=3,["legacy"]="ttk_luoshen_qingshu"}},["id"]="kha_07"},
        {["name"]="Chiến lợi phẩm",["weight"]=1,["items"]={{["prefab"]="deerclops_eyeball",["count"]=1},{["prefab"]="bearger_fur",["count"]=1},{["prefab"]="xd_npxsz",["count"]=3,["legacy"]="ttk_npxsz"}},["id"]="kha_08"},
        {["name"]="Vảy và da",["weight"]=1,["items"]={{["prefab"]="dragon_scales",["count"]=1},{["prefab"]="shroom_skin",["count"]=1}},["id"]="kha_09"},
        {["name"]="Làm vườn",["weight"]=1,["items"]={{["prefab"]="shovel_lunarplant",["count"]=1},{["prefab"]="rock_avocado_fruit_sprout",["count"]=5},{["prefab"]="xd_luoshen_huazhong",["count"]=2,["legacy"]="ttk_luoshen_huazhong"}},["id"]="kha_10"},
        {["name"]="Vân Mạc Thượng Trang",["weight"]=1,["items"]={{["prefab"]="xd_yunxiao_ymsz",["count"]=1,["legacy"]="ttk_yunxiao_ymsz"},{["prefab"]="xd_lc_cyh",["count"]=3,["legacy"]="ttk_lc_cyh"}},["id"]="kha_11"},
        {["name"]="Sáu bùa",["weight"]=1,["items"]={{["prefab"]="blueamulet",["count"]=1},{["prefab"]="greenamulet",["count"]=1},{["prefab"]="purpleamulet",["count"]=1},{["prefab"]="orangeamulet",["count"]=1},{["prefab"]="yellowamulet",["count"]=1},{["prefab"]="amulet",["count"]=1}},["id"]="kha_12"},
        {["name"]="Linh thực đóng gói",["weight"]=1,["items"]={{["prefab"]="xd_luoxiang_pengrou",["count"]=3,["legacy"]="ttk_luoxiang_pengrou"},{["prefab"]="xd_luoshen_qingshu",["count"]=3,["legacy"]="ttk_luoshen_qingshu"},{["prefab"]="bundlewrap",["count"]=7}},["id"]="kha_13"},
        {["name"]="Công cụ mặt trăng",["weight"]=1,["items"]={{["prefab"]="pickaxe_lunarplant",["count"]=1},{["prefab"]="moonglassaxe",["count"]=4}},["id"]="kha_14"},
        {["name"]="Chìa khóa và mỏ biển",["weight"]=1,["items"]={{["prefab"]="klaussackkey",["count"]=1},{["prefab"]="malbatross_beak",["count"]=1}},["id"]="kha_15"},
        {["name"]="Bữa ăn tiếp tế",["weight"]=1,["items"]={{["prefab"]="bonestew",["count"]=2},{["prefab"]="dragonpie",["count"]=5},{["prefab"]="perogies",["count"]=5}},["id"]="kha_16"},
        {["name"]="Kem",["weight"]=1,["items"]={{["prefab"]="icecream",["count"]=10}},["id"]="kha_17"},
        {["name"]="Linh Thạch Solo",["weight"]=1,["items"]={{["prefab"]="hh_essence",["count"]=10}},["id"]="kha_18"},
        {["name"]="Vật liệu thuộc tính Solo",["weight"]=1,["items"]={{["prefab"]="hh_effect_tally",["count"]=3},{["prefab"]="hh_remove_stone",["count"]=2}},["id"]="kha_19"},
        {["name"]="Đá Thuộc Tính Solo",["weight"]=1,["items"]={{["prefab"]="hh_effect_stone",["count"]=2}},["id"]="kha_20"},
        {["name"]="Phúc Lạc Dược II",["weight"]=1,["items"]={{["prefab"]="nn_liquidluck_2",["count"]=1}},["id"]="kha_21"},
    }},
    {["key"]="ok2",["id"]="thuong",["name"]="Thường",["weight"]=3.5,bundles={
        {["name"]="Linh thực Lạc Thần",["weight"]=1,["items"]={{["prefab"]="xd_luoshen_qingshu",["count"]=2,["legacy"]="ttk_luoshen_qingshu"},{["prefab"]="xd_luoxiang_pengrou",["count"]=2,["legacy"]="ttk_luoxiang_pengrou"}},["id"]="thuong_01"},
        {["name"]="Hạt dưỡng sinh",["weight"]=1,["items"]={{["prefab"]="xd_lc_hsc_seed",["count"]=4,["legacy"]="ttk_lc_hsc_seed"},{["prefab"]="xd_lc_cyh_seed",["count"]=4,["legacy"]="ttk_lc_cyh_seed"}},["id"]="thuong_02"},
        {["name"]="Hạt dưỡng thần",["weight"]=1,["items"]={{["prefab"]="xd_lc_qfx_seed",["count"]=4,["legacy"]="ttk_lc_qfx_seed"},{["prefab"]="xd_lc_yhh_seed",["count"]=4,["legacy"]="ttk_lc_yhh_seed"}},["id"]="thuong_03"},
        {["name"]="Hạt dưỡng khí",["weight"]=1,["items"]={{["prefab"]="xd_lc_dms_seed",["count"]=4,["legacy"]="ttk_lc_dms_seed"},{["prefab"]="xd_lc_lmg_seed",["count"]=4,["legacy"]="ttk_lc_lmg_seed"}},["id"]="thuong_04"},
        {["name"]="Linh thảo băng hỏa",["weight"]=1,["items"]={{["prefab"]="xd_lc_hsc",["count"]=3,["legacy"]="ttk_lc_hsc"},{["prefab"]="xd_lc_cyh",["count"]=3,["legacy"]="ttk_lc_cyh"},{["prefab"]="xd_lc_dms_seed",["count"]=3,["legacy"]="ttk_lc_dms_seed"}},["id"]="thuong_05"},
        {["name"]="Địa Mạch Sâm",["weight"]=1,["items"]={{["prefab"]="xd_lc_dms",["count"]=4,["legacy"]="ttk_lc_dms"},{["prefab"]="xd_lc_dms_seed",["count"]=3,["legacy"]="ttk_lc_dms_seed"}},["id"]="thuong_06"},
        {["name"]="Thanh Phong Tiên",["weight"]=1,["items"]={{["prefab"]="xd_lc_qfx",["count"]=3,["legacy"]="ttk_lc_qfx"},{["prefab"]="xd_lc_qfx_seed",["count"]=4,["legacy"]="ttk_lc_qfx_seed"}},["id"]="thuong_07"},
        {["name"]="Lôi Minh Quả",["weight"]=1,["items"]={{["prefab"]="xd_lc_lmg",["count"]=3,["legacy"]="ttk_lc_lmg"},{["prefab"]="xd_lc_lmg_seed",["count"]=4,["legacy"]="ttk_lc_lmg_seed"}},["id"]="thuong_08"},
        {["name"]="U Hồn Hoa",["weight"]=1,["items"]={{["prefab"]="xd_lc_yhh",["count"]=3,["legacy"]="ttk_lc_yhh"},{["prefab"]="xd_lc_yhh_seed",["count"]=4,["legacy"]="ttk_lc_yhh_seed"}},["id"]="thuong_09"},
        {["name"]="Vườn Lạc Thần",["weight"]=1,["items"]={{["prefab"]="xd_luoshen_huazhong",["count"]=2,["legacy"]="ttk_luoshen_huazhong"},{["prefab"]="xd_luoshen_huayin",["count"]=3,["legacy"]="ttk_luoshen_huayin"}},["id"]="thuong_10"},
        {["name"]="Nguyên liệu Tu Tiên",["weight"]=1,["items"]={{["prefab"]="xd_pog_tail",["count"]=3,["legacy"]="ttk_pog_tail"},{["prefab"]="xd_spider_leg",["count"]=2,["legacy"]="ttk_spider_leg"},{["prefab"]="xd_npxsz",["count"]=3,["legacy"]="ttk_npxsz"}},["id"]="thuong_11"},
        {["name"]="Linh khí dự trữ",["weight"]=1,["items"]={{["prefab"]="xd_lingshi1",["count"]=30,["legacy"]="ttk_lingshi1"},{["prefab"]="xd_luoshen_qingshu",["count"]=2,["legacy"]="ttk_luoshen_qingshu"}},["id"]="thuong_12"},
        {["name"]="Ngọc sơ cấp",["weight"]=1,["items"]={{["prefab"]="redgem",["count"]=1},{["prefab"]="bluegem",["count"]=1},{["prefab"]="xd_lc_lmg_seed",["count"]=3,["legacy"]="ttk_lc_lmg_seed"}},["id"]="thuong_13"},
        {["name"]="Trở về",["weight"]=1,["items"]={{["prefab"]="amulet",["count"]=1},{["prefab"]="reviver",["count"]=2},{["prefab"]="xd_lc_dms_seed",["count"]=3,["legacy"]="ttk_lc_dms_seed"}},["id"]="thuong_14"},
        {["name"]="Mắt và sinh lực",["weight"]=1,["items"]={{["prefab"]="eyemaskhat",["count"]=1},{["prefab"]="lifeinjector",["count"]=3},{["prefab"]="xd_luoshen_qingshu",["count"]=2,["legacy"]="ttk_luoshen_qingshu"}},["id"]="thuong_15"},
        {["name"]="Mandrake",["weight"]=1,["items"]={{["prefab"]="mandrake_planted",["count"]=1},{["prefab"]="mandrakesoup",["count"]=1}},["id"]="thuong_16"},
        {["name"]="Sừng cổ đại",["weight"]=1,["items"]={{["prefab"]="minotaurhorn",["count"]=1},{["prefab"]="xd_spider_leg",["count"]=2,["legacy"]="ttk_spider_leg"}},["id"]="thuong_17"},
        {["name"]="Khai khoáng đa năng",["weight"]=1,["items"]={{["prefab"]="multitool_axe_pickaxe",["count"]=2},{["prefab"]="moonglass",["count"]=12}},["id"]="thuong_18"},
        {["name"]="Thuyền trưởng",["weight"]=1,["items"]={{["prefab"]="polly_rogershat",["count"]=1},{["prefab"]="xd_lc_hsc_seed",["count"]=3,["legacy"]="ttk_lc_hsc_seed"}},["id"]="thuong_19"},
        {["name"]="Nhện đồng hành",["weight"]=1,["items"]={{["prefab"]="spidereggsack",["count"]=2},{["prefab"]="spiderhat",["count"]=1},{["prefab"]="xd_spider_leg",["count"]=2,["legacy"]="ttk_spider_leg"}},["id"]="thuong_20"},
        {["name"]="Mũ hải mã",["weight"]=1,["items"]={{["prefab"]="walrushat",["count"]=1},{["prefab"]="xd_lc_qfx_seed",["count"]=3,["legacy"]="ttk_lc_qfx_seed"}},["id"]="thuong_21"},
        {["name"]="Dịch chuyển",["weight"]=1,["items"]={{["prefab"]="townportaltalisman",["count"]=6},{["prefab"]="xd_lc_yhh_seed",["count"]=3,["legacy"]="ttk_lc_yhh_seed"}},["id"]="thuong_22"},
        {["name"]="Nguyên liệu ma thuật",["weight"]=1,["items"]={{["prefab"]="livinglog",["count"]=6},{["prefab"]="cutreeds",["count"]=20}},["id"]="thuong_23"},
        {["name"]="Hồi phục",["weight"]=1,["items"]={{["prefab"]="bandage",["count"]=3},{["prefab"]="taffy",["count"]=6}},["id"]="thuong_24"},
        {["name"]="Linh Thạch Solo",["weight"]=1,["items"]={{["prefab"]="hh_essence",["count"]=3}},["id"]="thuong_25"},
        {["name"]="Giấy Thuộc Tính",["weight"]=1,["items"]={{["prefab"]="hh_effect_tally",["count"]=2}},["id"]="thuong_26"},
        {["name"]="Lục Bảo Thạch",["weight"]=1,["items"]={{["prefab"]="hh_remove_stone",["count"]=2}},["id"]="thuong_27"},
        {["name"]="Phúc Lạc Dược I",["weight"]=1,["items"]={{["prefab"]="nn_liquidluck",["count"]=2}},["id"]="thuong_28"},
        {["name"]="Thuốc Tái Sinh Solo",["weight"]=1,["items"]={{["prefab"]="hh_thuoc_tai_sinh",["count"]=2}},["id"]="thuong_29"},
        {["name"]="Thuốc Ma Lực Solo",["weight"]=1,["items"]={{["prefab"]="hh_thuoc_ma_luc",["count"]=2}},["id"]="thuong_30"},
    }},
    {["key"]="bad",["id"]="boss",["name"]="Boss",["weight"]=0.8,bundles={
        {["name"]="Bee Queen",["weight"]=1,["items"]={{["prefab"]="beequeen",["count"]=1}},["id"]="boss_01"},
        {["name"]="Dragonfly",["weight"]=1,["items"]={{["prefab"]="dragonfly",["count"]=1}},["id"]="boss_02"},
        {["name"]="Bearger + Deerclops",["weight"]=1,["items"]={{["prefab"]="bearger",["count"]=1},{["prefab"]="deerclops",["count"]=1}},["id"]="boss_03"},
        {["name"]="Spider Queen",["weight"]=1,["items"]={{["prefab"]="spiderqueen",["count"]=2}},["id"]="boss_04"},
        {["name"]="Armored Bearger",["weight"]=1,["items"]={{["prefab"]="mutatedbearger",["count"]=1}},["id"]="boss_05"},
        {["name"]="Crystal Deerclops",["weight"]=1,["items"]={{["prefab"]="mutateddeerclops",["count"]=1}},["id"]="boss_06"},
        {["name"]="Possessed Varg",["weight"]=1,["items"]={{["prefab"]="mutatedwarg",["count"]=2}},["id"]="boss_07"},
        {["name"]="Bộ ba cờ bóng tối",["weight"]=1,["items"]={{["prefab"]="shadow_knight",["count"]=1},{["prefab"]="shadow_bishop",["count"]=1},{["prefab"]="shadow_rook",["count"]=1}},["id"]="boss_08"},
        {["name"]="Klaus",["weight"]=1,["items"]={{["prefab"]="klaus",["count"]=1}},["id"]="boss_09"},
        {["name"]="Celestial Champion giai đoạn 3",["weight"]=1,["items"]={{["prefab"]="alterguardian_phase3",["count"]=1}},["id"]="boss_10"},
        {["name"]="Ancient Guardian",["weight"]=1,["items"]={{["prefab"]="minotaur",["count"]=1}},["id"]="boss_11"},
        {["name"]="Brightshade",["weight"]=1,["items"]={{["prefab"]="lunarthrall_plant",["count"]=3}},["id"]="boss_12"},
        {["name"]="Kim Phượng Thần Niệm",["weight"]=1,["items"]={{["prefab"]="xd_jfsn",["count"]=1}},["id"]="boss_13"},
        {["name"]="Kỳ Lân Tàn Hồn",["weight"]=1,["items"]={{["prefab"]="xd_qlch",["count"]=1}},["id"]="boss_14"},
        {["name"]="Moose/Goose",["weight"]=1,["items"]={{["prefab"]="moose",["count"]=1}},["id"]="boss_15"},
        {["name"]="Antlion",["weight"]=1,["items"]={{["prefab"]="antlion",["count"]=1}},["id"]="boss_16"},
        {["name"]="Toadstool",["weight"]=1,["items"]={{["prefab"]="toadstool",["count"]=1}},["id"]="boss_17"},
        {["name"]="Misery Toadstool",["weight"]=1,["items"]={{["prefab"]="toadstool_dark",["count"]=1}},["id"]="boss_18"},
        {["name"]="Eye of Terror",["weight"]=1,["items"]={{["prefab"]="eyeofterror",["count"]=1}},["id"]="boss_19"},
        {["name"]="Twins of Terror",["weight"]=1,["items"]={{["prefab"]="twinofterror1",["count"]=1},{["prefab"]="twinofterror2",["count"]=1}},["adapter"]="twins",["id"]="boss_20"},
        {["name"]="Nightmare Werepig",["weight"]=1,["items"]={{["prefab"]="daywalker",["count"]=1}},["id"]="boss_21"},
        {["name"]="Scrappy Werepig",["weight"]=1,["items"]={{["prefab"]="daywalker2",["count"]=1}},["id"]="boss_22"},
        {["name"]="Great Depths Worm",["weight"]=1,["items"]={{["prefab"]="worm_boss",["count"]=1}},["id"]="boss_23"},
        {["name"]="Igris",["weight"]=1,["items"]={{["prefab"]="hh_igris_dungeon",["count"]=1}},["id"]="boss_24"},
        {["name"]="Beru",["weight"]=1,["items"]={{["prefab"]="hh_beru_dungeon",["count"]=1}},["id"]="boss_25"},
        {["name"]="Super Frostjaw",["weight"]=1,["items"]={{["prefab"]="hh_sharkboi",["count"]=1}},["id"]="boss_26"},
        {["name"]="Lợn Rừng Bọ Hung",["weight"]=1,["items"]={{["prefab"]="hh_beetle_pig",["count"]=1}},["id"]="boss_27"},
        {["name"]="Siêu Lợn Song Kiếm",["weight"]=1,["items"]={{["prefab"]="hh_dual_wield_pig",["count"]=1}},["id"]="boss_28"},
        {["name"]="Multiverse Guardian",["weight"]=1,["items"]={{["prefab"]="minotau",["count"]=1}},["id"]="boss_29"},
        {["name"]="Super MacTusk",["weight"]=1,["items"]={{["prefab"]="walrus",["count"]=1,["treasure"]="walrus_adc"}},["solo"]=true,["id"]="boss_30"},
        {["name"]="Super Crystal Deerclops",["weight"]=1,["items"]={{["prefab"]="mutateddeerclops",["count"]=1,["treasure"]="mutateddeerclops_boss"}},["solo"]=true,["id"]="boss_31"},
        {["name"]="Super Armored Bearger",["weight"]=1,["items"]={{["prefab"]="mutatedbearger",["count"]=1,["treasure"]="mutatedbearger_boss"}},["solo"]=true,["id"]="boss_32"},
        {["name"]="Super Mutated Warg",["weight"]=1,["items"]={{["prefab"]="mutatedwarg",["count"]=1,["treasure"]="mutatedwarg_boss"}},["solo"]=true,["id"]="boss_33"},
        {["name"]="Super Frostjaw — bản kho báu",["weight"]=1,["items"]={{["prefab"]="hh_sharkboi",["count"]=1,["treasure"]="hh_sharkboi_boss"}},["solo"]=true,["id"]="boss_34"},
        {["name"]="Super Krampus",["weight"]=1,["items"]={{["prefab"]="krampus",["count"]=1,["treasure"]="treasure_kps"}},["solo"]=true,["id"]="boss_35"},
        {["name"]="Super Catcoon",["weight"]=1,["items"]={{["prefab"]="catcoon",["count"]=1,["treasure"]="treasure_cat_you"}},["solo"]=true,["id"]="boss_36"},
        {["name"]="Lord of the Fruit Flies",["weight"]=1,["items"]={{["prefab"]="lordfruitfly",["count"]=1}},["id"]="boss_37"},
        {["name"]="Treeguard",["weight"]=1,["items"]={{["prefab"]="leif",["count"]=1}},["id"]="boss_38"},
        {["name"]="Treeguard — cây thưa",["weight"]=1,["items"]={{["prefab"]="leif_sparse",["count"]=1}},["id"]="boss_39"},
        {["name"]="Varg",["weight"]=1,["items"]={{["prefab"]="warg",["count"]=1}},["id"]="boss_40"},
        {["name"]="Clay Varg",["weight"]=1,["items"]={{["prefab"]="claywarg",["count"]=1}},["id"]="boss_41"},
        {["name"]="Gingerbread Varg",["weight"]=1,["items"]={{["prefab"]="gingerbreadwarg",["count"]=1}},["id"]="boss_42"},
        {["name"]="Reanimated Skeleton — hang",["weight"]=1,["items"]={{["prefab"]="stalker",["count"]=1}},["id"]="boss_43"},
    }},
    {["key"]="bad2",["id"]="quai",["name"]="Quái",["weight"]=4.2,bundles={
        {["name"]="Lính heo",["weight"]=1,["items"]={{["prefab"]="pigguard",["count"]=5}},["id"]="quai_03"},
        {["name"]="Ewecus",["weight"]=1,["items"]={{["prefab"]="spat",["count"]=2}},["id"]="quai_06"},
        {["name"]="Chim cao cổ",["weight"]=1,["items"]={{["prefab"]="tallbird",["count"]=3}},["id"]="quai_08"},
        {["name"]="Quân cờ máy",["weight"]=1,["items"]={{["prefab"]="bishop",["count"]=1},{["prefab"]="rook",["count"]=1},{["prefab"]="knight",["count"]=1}},["id"]="quai_09"},
        {["name"]="Khỉ cướp biển",["weight"]=1,["items"]={{["prefab"]="powder_monkey",["count"]=5}},["id"]="quai_10"},
        {["name"]="Dơi",["weight"]=1,["items"]={{["prefab"]="bat",["count"]=10}},["id"]="quai_13"},
        {["name"]="Ác mộng",["weight"]=1,["items"]={{["prefab"]="crawlingnightmare",["count"]=3},{["prefab"]="nightmarebeak",["count"]=2}},["id"]="quai_16"},
        {["name"]="Nhện y tá",["weight"]=1,["items"]={{["prefab"]="spider_healer",["count"]=5}},["id"]="quai_19"},
        {["name"]="Bộ ba Ink Blight",["weight"]=1,["items"]={{["prefab"]="shadowthrall_horns",["count"]=1},{["prefab"]="shadowthrall_hands",["count"]=1},{["prefab"]="shadowthrall_wings",["count"]=1}},["id"]="quai_20"},
        {["name"]="Mắt bay nhỏ",["weight"]=1,["items"]={{["prefab"]="eyeofterror_mini",["count"]=6}},["id"]="quai_24"},
        {["name"]="Nhện hang",["weight"]=1,["items"]={{["prefab"]="spider_hider",["count"]=4},{["prefab"]="spider_spitter",["count"]=2}},["id"]="quai_26"},
        {["name"]="Krampus thường",["weight"]=1,["items"]={{["prefab"]="krampus",["count"]=2}},["id"]="quai_27"},
        {["name"]="Rồng trái cây",["weight"]=1,["items"]={{["prefab"]="fruitdragon",["count"]=5}},["id"]="quai_28"},
        {["name"]="Bầy nhện",["weight"]=1,["items"]={{["prefab"]="spider",["count"]=5},{["prefab"]="spider_warrior",["count"]=2},{["prefab"]="moonspider_spike",["count"]=2}},["id"]="quai_30"},
        {["name"]="Lính người cá",["weight"]=1,["items"]={{["prefab"]="mermguard",["count"]=5}},["id"]="quai_31"},
    }},
}}
