name = "Tiện Ích Client"
description = [[
Phiên bản 1.0 - Tiện Ích Client

★ Tự động đi bộ đến điểm chọn trên bản đồ, có chỉ dẫn đường đi.
★ Camera quan sát: đổi góc nhìn, ẩn HUD và theo dõi mục tiêu.
★ Bổ sung biểu tượng sinh vật, vật phẩm và công trình trên bản đồ.
★ Thả vật phẩm theo lưới; ẩn hình vật phẩm để thấy rõ điểm thả.
★ Đặt công trình theo lưới với nhiều kiểu hình học và màu hiển thị.

Chỉ cần cài phía Client.

]]
author = "Nyx"
version = "1.0.3"
api_version = 10
api_version_dst = 10
dst_compatible = true
all_clients_require_mod = false
client_only_mod = true
server_only_mod = false
priority = -10
icon_atlas = "modicon.xml"
icon = "modicon.tex"

local yes_no = {
    {description = "Bật", data = true},
    {description = "Tắt", data = false},
}
local function heading(label)
    return {name = "", label = label, options = {{description = "", data = 0}}, default = 0}
end

configuration_options = {
    heading("Tự động đi bộ"),
    heading("Giao diện"),
    {name = "UI_DISPLAY", label = "UI Diplay Settings", options = {{["data"]="Both", ["description"]="Icon & PathLine"}, {["data"]="DestIcon", ["description"]="Icon Only"}, {["data"]="PathLine", ["description"]="PathLine Only"}, {["data"]=false, ["description"]="None"}}, default = "Both", hover = "Configure the display of the icon and path line"},
    {name = "ICON_STYLE", label = "Icon Style", options = {{["data"]=1, ["description"]="New"}, {["data"]=0, ["description"]="Classical"}}, default = 1, hover = "Thank you Miss Wu for drawing the new icon"},
    heading("Điều khiển"),
    {name = "MAPS_TRIGGER", label = "Maps Trigger Settings", options = {{["data"]="Both", ["description"]="Map & MiniMap"}, {["data"]="MainMap", ["description"]="MainMap Only"}, {["data"]="MiniMap", ["description"]="MiniMap Only"}}, default = "Both", hover = "Configure whether the MainMapScreen and MiniMapHUD/SmallMap Mod can trigger auto-pathing"},
    {name = "DBCLICK_TIME_THRESHOLD", label = "DoubleClick Interval", options = {{["data"]=0.2, ["description"]="0.2s"}, {["data"]=0.3, ["description"]="0.3s"}, {["data"]=0.4, ["description"]="0.4s"}, {["data"]=0.5, ["description"]="0.5s"}}, default = 0.3, hover = "DoubleClick to trigger the original map action (Also Shift/Ctrl/Alt+Path Key), set the time interval of double-click"},
    {name = "MOUSEBUTTON_TRAVEL", label = "Auto Pathing Keybind", options = {{["data"]="MOUSEBUTTON_RIGHT", ["description"]=""}, {["data"]="MOUSEBUTTON_MIDDLE", ["description"]=""}, {["data"]="MOUSEBUTTON_4", ["description"]=""}, {["data"]="MOUSEBUTTON_5", ["description"]=""}}, default = "MOUSEBUTTON_RIGHT", hover = "Set the mouse button to trigger auto-pathing on the map"},
    {name = "KEY_ADDITION_TRAVEL", label = "Append Pathing Keybind", options = {{["data"]=false, ["description"]="Disabled"}, {["data"]="CONTROL_FORCE_TRADE", ["description"]="Shift+Path Key"}, {["data"]="CONTROL_FORCE_ATTACK", ["description"]="Ctrl+Path Key"}, {["data"]="CONTROL_FORCE_INSPECT", ["description"]="Alt+Path Key"}}, default = false, hover = "Append the path with the previous target when we already have a path and want to continue to travel by marking another point."},
    heading("Tìm đường"),
    {name = "ALLOW_FOGOFWAR", label = "Allow Fog Of War", options = yes_no, default = true, hover = "Allow Pathfinding in Fog Of War"},
    {name = "TWEAK_DETOUR_ENABLE", label = "Bypass Obstacles(With Cave)", options = yes_no, default = true, hover = "it helps to avoid stucked by obstacles, but only works in the world with cave on and no Dont Starve Alone Mod"},
    {name = "PATHFINDER", label = "Pathfinder", options = {{["data"]="A star", ["description"]="A star"}, {["data"]="klei's", ["description"]="klei's"}}, default = "A star", hover = "A star:long-distance pathfinder and can follow the road\
klei's:short-distance but cost less time to caculate, may fail in long-distance search"},
    heading("Khác"),
    {name = "TIMESCALE_TWEAK_MULTI", label = "Auto Speedup Game(Solo)", options = {{["data"]=false, ["description"]="Disabled"}, {["data"]=1.25, ["description"]="1.25x"}, {["data"]=1.5, ["description"]="1.5x"}, {["data"]=2, ["description"]="2x"}, {["data"]=3, ["description"]="3x"}, {["data"]=4, ["description"]="4x"}}, default = false, hover = "Auto increase the timescale of the game during autowalking"},
    {name = "PATCH_MINIMAP", label = "Patch For MiniMap HUD", options = {{["data"]=false, ["description"]="Disabled"}, {["data"]=true, ["description"]="Enabled"}}, default = false, hover = "Fixed the issue of MiniMap HUD resetting zoom by holding down the close map button"},
    heading("Camera quan sát"),
    {name = "OBC_INITIAL_VIEW_MODE", label = "进入游戏时的初始视角模式", options = {{["data"]=0, ["description"]="Default - 默认"}, {["data"]=1, ["description"]="Aerial - 高空"}, {["data"]=2, ["description"]="Vertical - 俯视"}}, default = 0, hover = "Initial view mode when entering a game."},
    {name = "OBC_FUNCTION_KEY_1", label = "在默认/高空/俯视模式间切换", options = {{["data"]=-1, ["description"]="Disable - 禁用"}, {["data"]=282, ["description"]="F1"}, {["data"]=283, ["description"]="F2"}, {["data"]=284, ["description"]="F3"}, {["data"]=285, ["description"]="F4"}, {["data"]=286, ["description"]="F5"}, {["data"]=287, ["description"]="F6"}, {["data"]=288, ["description"]="F7"}, {["data"]=289, ["description"]="F8"}, {["data"]=290, ["description"]="F9"}, {["data"]=291, ["description"]="F10"}, {["data"]=292, ["description"]="F11"}, {["data"]=293, ["description"]="F12"}, {["data"]=48, ["description"]="0"}, {["data"]=49, ["description"]="1"}, {["data"]=50, ["description"]="2"}, {["data"]=51, ["description"]="3"}, {["data"]=52, ["description"]="4"}, {["data"]=53, ["description"]="5"}, {["data"]=54, ["description"]="6"}, {["data"]=55, ["description"]="7"}, {["data"]=56, ["description"]="8"}, {["data"]=57, ["description"]="9"}, {["data"]=97, ["description"]="A"}, {["data"]=98, ["description"]="B"}, {["data"]=99, ["description"]="C"}, {["data"]=100, ["description"]="D"}, {["data"]=101, ["description"]="E"}, {["data"]=102, ["description"]="F"}, {["data"]=103, ["description"]="G"}, {["data"]=104, ["description"]="H"}, {["data"]=105, ["description"]="I"}, {["data"]=106, ["description"]="J"}, {["data"]=107, ["description"]="K"}, {["data"]=108, ["description"]="L"}, {["data"]=109, ["description"]="M"}, {["data"]=110, ["description"]="N"}, {["data"]=111, ["description"]="O"}, {["data"]=112, ["description"]="P"}, {["data"]=113, ["description"]="Q"}, {["data"]=114, ["description"]="R"}, {["data"]=115, ["description"]="S"}, {["data"]=116, ["description"]="T"}, {["data"]=117, ["description"]="U"}, {["data"]=118, ["description"]="V"}, {["data"]=119, ["description"]="W"}, {["data"]=120, ["description"]="X"}, {["data"]=121, ["description"]="Y"}, {["data"]=122, ["description"]="Z"}, {["data"]=273, ["description"]="↑"}, {["data"]=274, ["description"]="↓"}, {["data"]=276, ["description"]="←"}, {["data"]=275, ["description"]="→"}}, default = 290, hover = "The key to switch among default/aerial/vertical view mode."},
    {name = "OBC_FUNCTION_KEY_2", label = "隐藏/显示游戏HUD", options = {{["data"]=-1, ["description"]="Disable - 禁用"}, {["data"]=282, ["description"]="F1"}, {["data"]=283, ["description"]="F2"}, {["data"]=284, ["description"]="F3"}, {["data"]=285, ["description"]="F4"}, {["data"]=286, ["description"]="F5"}, {["data"]=287, ["description"]="F6"}, {["data"]=288, ["description"]="F7"}, {["data"]=289, ["description"]="F8"}, {["data"]=290, ["description"]="F9"}, {["data"]=291, ["description"]="F10"}, {["data"]=292, ["description"]="F11"}, {["data"]=293, ["description"]="F12"}, {["data"]=48, ["description"]="0"}, {["data"]=49, ["description"]="1"}, {["data"]=50, ["description"]="2"}, {["data"]=51, ["description"]="3"}, {["data"]=52, ["description"]="4"}, {["data"]=53, ["description"]="5"}, {["data"]=54, ["description"]="6"}, {["data"]=55, ["description"]="7"}, {["data"]=56, ["description"]="8"}, {["data"]=57, ["description"]="9"}, {["data"]=97, ["description"]="A"}, {["data"]=98, ["description"]="B"}, {["data"]=99, ["description"]="C"}, {["data"]=100, ["description"]="D"}, {["data"]=101, ["description"]="E"}, {["data"]=102, ["description"]="F"}, {["data"]=103, ["description"]="G"}, {["data"]=104, ["description"]="H"}, {["data"]=105, ["description"]="I"}, {["data"]=106, ["description"]="J"}, {["data"]=107, ["description"]="K"}, {["data"]=108, ["description"]="L"}, {["data"]=109, ["description"]="M"}, {["data"]=110, ["description"]="N"}, {["data"]=111, ["description"]="O"}, {["data"]=112, ["description"]="P"}, {["data"]=113, ["description"]="Q"}, {["data"]=114, ["description"]="R"}, {["data"]=115, ["description"]="S"}, {["data"]=116, ["description"]="T"}, {["data"]=117, ["description"]="U"}, {["data"]=118, ["description"]="V"}, {["data"]=119, ["description"]="W"}, {["data"]=120, ["description"]="X"}, {["data"]=121, ["description"]="Y"}, {["data"]=122, ["description"]="Z"}, {["data"]=273, ["description"]="↑"}, {["data"]=274, ["description"]="↓"}, {["data"]=276, ["description"]="←"}, {["data"]=275, ["description"]="→"}}, default = 291, hover = "The key to hide/show game HUD."},
    {name = "OBC_FUNCTION_KEY_3", label = "隐藏/显示自身角色", options = {{["data"]=-1, ["description"]="Disable - 禁用"}, {["data"]=282, ["description"]="F1"}, {["data"]=283, ["description"]="F2"}, {["data"]=284, ["description"]="F3"}, {["data"]=285, ["description"]="F4"}, {["data"]=286, ["description"]="F5"}, {["data"]=287, ["description"]="F6"}, {["data"]=288, ["description"]="F7"}, {["data"]=289, ["description"]="F8"}, {["data"]=290, ["description"]="F9"}, {["data"]=291, ["description"]="F10"}, {["data"]=292, ["description"]="F11"}, {["data"]=293, ["description"]="F12"}, {["data"]=48, ["description"]="0"}, {["data"]=49, ["description"]="1"}, {["data"]=50, ["description"]="2"}, {["data"]=51, ["description"]="3"}, {["data"]=52, ["description"]="4"}, {["data"]=53, ["description"]="5"}, {["data"]=54, ["description"]="6"}, {["data"]=55, ["description"]="7"}, {["data"]=56, ["description"]="8"}, {["data"]=57, ["description"]="9"}, {["data"]=97, ["description"]="A"}, {["data"]=98, ["description"]="B"}, {["data"]=99, ["description"]="C"}, {["data"]=100, ["description"]="D"}, {["data"]=101, ["description"]="E"}, {["data"]=102, ["description"]="F"}, {["data"]=103, ["description"]="G"}, {["data"]=104, ["description"]="H"}, {["data"]=105, ["description"]="I"}, {["data"]=106, ["description"]="J"}, {["data"]=107, ["description"]="K"}, {["data"]=108, ["description"]="L"}, {["data"]=109, ["description"]="M"}, {["data"]=110, ["description"]="N"}, {["data"]=111, ["description"]="O"}, {["data"]=112, ["description"]="P"}, {["data"]=113, ["description"]="Q"}, {["data"]=114, ["description"]="R"}, {["data"]=115, ["description"]="S"}, {["data"]=116, ["description"]="T"}, {["data"]=117, ["description"]="U"}, {["data"]=118, ["description"]="V"}, {["data"]=119, ["description"]="W"}, {["data"]=120, ["description"]="X"}, {["data"]=121, ["description"]="Y"}, {["data"]=122, ["description"]="Z"}, {["data"]=273, ["description"]="↑"}, {["data"]=274, ["description"]="↓"}, {["data"]=276, ["description"]="←"}, {["data"]=275, ["description"]="→"}}, default = 292, hover = "The key to hide/show your character."},
    {name = "OBC_SWITCH_KEY_1", label = "固定视角到鼠标所指实体", options = {{["data"]=-1, ["description"]="Disable - 禁用"}, {["data"]=282, ["description"]="F1"}, {["data"]=283, ["description"]="F2"}, {["data"]=284, ["description"]="F3"}, {["data"]=285, ["description"]="F4"}, {["data"]=286, ["description"]="F5"}, {["data"]=287, ["description"]="F6"}, {["data"]=288, ["description"]="F7"}, {["data"]=289, ["description"]="F8"}, {["data"]=290, ["description"]="F9"}, {["data"]=291, ["description"]="F10"}, {["data"]=292, ["description"]="F11"}, {["data"]=293, ["description"]="F12"}, {["data"]=48, ["description"]="0"}, {["data"]=49, ["description"]="1"}, {["data"]=50, ["description"]="2"}, {["data"]=51, ["description"]="3"}, {["data"]=52, ["description"]="4"}, {["data"]=53, ["description"]="5"}, {["data"]=54, ["description"]="6"}, {["data"]=55, ["description"]="7"}, {["data"]=56, ["description"]="8"}, {["data"]=57, ["description"]="9"}, {["data"]=97, ["description"]="A"}, {["data"]=98, ["description"]="B"}, {["data"]=99, ["description"]="C"}, {["data"]=100, ["description"]="D"}, {["data"]=101, ["description"]="E"}, {["data"]=102, ["description"]="F"}, {["data"]=103, ["description"]="G"}, {["data"]=104, ["description"]="H"}, {["data"]=105, ["description"]="I"}, {["data"]=106, ["description"]="J"}, {["data"]=107, ["description"]="K"}, {["data"]=108, ["description"]="L"}, {["data"]=109, ["description"]="M"}, {["data"]=110, ["description"]="N"}, {["data"]=111, ["description"]="O"}, {["data"]=112, ["description"]="P"}, {["data"]=113, ["description"]="Q"}, {["data"]=114, ["description"]="R"}, {["data"]=115, ["description"]="S"}, {["data"]=116, ["description"]="T"}, {["data"]=117, ["description"]="U"}, {["data"]=118, ["description"]="V"}, {["data"]=119, ["description"]="W"}, {["data"]=120, ["description"]="X"}, {["data"]=121, ["description"]="Y"}, {["data"]=122, ["description"]="Z"}, {["data"]=273, ["description"]="↑"}, {["data"]=274, ["description"]="↓"}, {["data"]=276, ["description"]="←"}, {["data"]=275, ["description"]="→"}}, default = 111, hover = "The key to focus the camera on the entity under mouse."},
    {name = "OBC_SWITCH_KEY_2", label = "固定视角到鼠标所指位置", options = {{["data"]=-1, ["description"]="Disable - 禁用"}, {["data"]=282, ["description"]="F1"}, {["data"]=283, ["description"]="F2"}, {["data"]=284, ["description"]="F3"}, {["data"]=285, ["description"]="F4"}, {["data"]=286, ["description"]="F5"}, {["data"]=287, ["description"]="F6"}, {["data"]=288, ["description"]="F7"}, {["data"]=289, ["description"]="F8"}, {["data"]=290, ["description"]="F9"}, {["data"]=291, ["description"]="F10"}, {["data"]=292, ["description"]="F11"}, {["data"]=293, ["description"]="F12"}, {["data"]=48, ["description"]="0"}, {["data"]=49, ["description"]="1"}, {["data"]=50, ["description"]="2"}, {["data"]=51, ["description"]="3"}, {["data"]=52, ["description"]="4"}, {["data"]=53, ["description"]="5"}, {["data"]=54, ["description"]="6"}, {["data"]=55, ["description"]="7"}, {["data"]=56, ["description"]="8"}, {["data"]=57, ["description"]="9"}, {["data"]=97, ["description"]="A"}, {["data"]=98, ["description"]="B"}, {["data"]=99, ["description"]="C"}, {["data"]=100, ["description"]="D"}, {["data"]=101, ["description"]="E"}, {["data"]=102, ["description"]="F"}, {["data"]=103, ["description"]="G"}, {["data"]=104, ["description"]="H"}, {["data"]=105, ["description"]="I"}, {["data"]=106, ["description"]="J"}, {["data"]=107, ["description"]="K"}, {["data"]=108, ["description"]="L"}, {["data"]=109, ["description"]="M"}, {["data"]=110, ["description"]="N"}, {["data"]=111, ["description"]="O"}, {["data"]=112, ["description"]="P"}, {["data"]=113, ["description"]="Q"}, {["data"]=114, ["description"]="R"}, {["data"]=115, ["description"]="S"}, {["data"]=116, ["description"]="T"}, {["data"]=117, ["description"]="U"}, {["data"]=118, ["description"]="V"}, {["data"]=119, ["description"]="W"}, {["data"]=120, ["description"]="X"}, {["data"]=121, ["description"]="Y"}, {["data"]=122, ["description"]="Z"}, {["data"]=273, ["description"]="↑"}, {["data"]=274, ["description"]="↓"}, {["data"]=276, ["description"]="←"}, {["data"]=275, ["description"]="→"}}, default = 112, hover = "The key to focus the camera on the position under mouse."},
    {name = "OBC_RESET_KEY", label = "在自身与最近选定的实体/位置间切换", options = {{["data"]=-1, ["description"]="Disable - 禁用"}, {["data"]=282, ["description"]="F1"}, {["data"]=283, ["description"]="F2"}, {["data"]=284, ["description"]="F3"}, {["data"]=285, ["description"]="F4"}, {["data"]=286, ["description"]="F5"}, {["data"]=287, ["description"]="F6"}, {["data"]=288, ["description"]="F7"}, {["data"]=289, ["description"]="F8"}, {["data"]=290, ["description"]="F9"}, {["data"]=291, ["description"]="F10"}, {["data"]=292, ["description"]="F11"}, {["data"]=293, ["description"]="F12"}, {["data"]=48, ["description"]="0"}, {["data"]=49, ["description"]="1"}, {["data"]=50, ["description"]="2"}, {["data"]=51, ["description"]="3"}, {["data"]=52, ["description"]="4"}, {["data"]=53, ["description"]="5"}, {["data"]=54, ["description"]="6"}, {["data"]=55, ["description"]="7"}, {["data"]=56, ["description"]="8"}, {["data"]=57, ["description"]="9"}, {["data"]=97, ["description"]="A"}, {["data"]=98, ["description"]="B"}, {["data"]=99, ["description"]="C"}, {["data"]=100, ["description"]="D"}, {["data"]=101, ["description"]="E"}, {["data"]=102, ["description"]="F"}, {["data"]=103, ["description"]="G"}, {["data"]=104, ["description"]="H"}, {["data"]=105, ["description"]="I"}, {["data"]=106, ["description"]="J"}, {["data"]=107, ["description"]="K"}, {["data"]=108, ["description"]="L"}, {["data"]=109, ["description"]="M"}, {["data"]=110, ["description"]="N"}, {["data"]=111, ["description"]="O"}, {["data"]=112, ["description"]="P"}, {["data"]=113, ["description"]="Q"}, {["data"]=114, ["description"]="R"}, {["data"]=115, ["description"]="S"}, {["data"]=116, ["description"]="T"}, {["data"]=117, ["description"]="U"}, {["data"]=118, ["description"]="V"}, {["data"]=119, ["description"]="W"}, {["data"]=120, ["description"]="X"}, {["data"]=121, ["description"]="Y"}, {["data"]=122, ["description"]="Z"}, {["data"]=273, ["description"]="↑"}, {["data"]=274, ["description"]="↓"}, {["data"]=276, ["description"]="←"}, {["data"]=275, ["description"]="→"}}, default = 114, hover = "The key to switch the focus of the camera between your character and recent selected entity/position."},
    {name = "OBC_FOV_PLUS_KEY", label = "FOV + 1", options = {{["data"]=-1, ["description"]="Disable - 禁用"}, {["data"]=282, ["description"]="F1"}, {["data"]=283, ["description"]="F2"}, {["data"]=284, ["description"]="F3"}, {["data"]=285, ["description"]="F4"}, {["data"]=286, ["description"]="F5"}, {["data"]=287, ["description"]="F6"}, {["data"]=288, ["description"]="F7"}, {["data"]=289, ["description"]="F8"}, {["data"]=290, ["description"]="F9"}, {["data"]=291, ["description"]="F10"}, {["data"]=292, ["description"]="F11"}, {["data"]=293, ["description"]="F12"}, {["data"]=48, ["description"]="0"}, {["data"]=49, ["description"]="1"}, {["data"]=50, ["description"]="2"}, {["data"]=51, ["description"]="3"}, {["data"]=52, ["description"]="4"}, {["data"]=53, ["description"]="5"}, {["data"]=54, ["description"]="6"}, {["data"]=55, ["description"]="7"}, {["data"]=56, ["description"]="8"}, {["data"]=57, ["description"]="9"}, {["data"]=97, ["description"]="A"}, {["data"]=98, ["description"]="B"}, {["data"]=99, ["description"]="C"}, {["data"]=100, ["description"]="D"}, {["data"]=101, ["description"]="E"}, {["data"]=102, ["description"]="F"}, {["data"]=103, ["description"]="G"}, {["data"]=104, ["description"]="H"}, {["data"]=105, ["description"]="I"}, {["data"]=106, ["description"]="J"}, {["data"]=107, ["description"]="K"}, {["data"]=108, ["description"]="L"}, {["data"]=109, ["description"]="M"}, {["data"]=110, ["description"]="N"}, {["data"]=111, ["description"]="O"}, {["data"]=112, ["description"]="P"}, {["data"]=113, ["description"]="Q"}, {["data"]=114, ["description"]="R"}, {["data"]=115, ["description"]="S"}, {["data"]=116, ["description"]="T"}, {["data"]=117, ["description"]="U"}, {["data"]=118, ["description"]="V"}, {["data"]=119, ["description"]="W"}, {["data"]=120, ["description"]="X"}, {["data"]=121, ["description"]="Y"}, {["data"]=122, ["description"]="Z"}, {["data"]=273, ["description"]="↑"}, {["data"]=274, ["description"]="↓"}, {["data"]=276, ["description"]="←"}, {["data"]=275, ["description"]="→"}}, default = 275},
    {name = "OBC_FOV_MINUS_KEY", label = "FOV - 1", options = {{["data"]=-1, ["description"]="Disable - 禁用"}, {["data"]=282, ["description"]="F1"}, {["data"]=283, ["description"]="F2"}, {["data"]=284, ["description"]="F3"}, {["data"]=285, ["description"]="F4"}, {["data"]=286, ["description"]="F5"}, {["data"]=287, ["description"]="F6"}, {["data"]=288, ["description"]="F7"}, {["data"]=289, ["description"]="F8"}, {["data"]=290, ["description"]="F9"}, {["data"]=291, ["description"]="F10"}, {["data"]=292, ["description"]="F11"}, {["data"]=293, ["description"]="F12"}, {["data"]=48, ["description"]="0"}, {["data"]=49, ["description"]="1"}, {["data"]=50, ["description"]="2"}, {["data"]=51, ["description"]="3"}, {["data"]=52, ["description"]="4"}, {["data"]=53, ["description"]="5"}, {["data"]=54, ["description"]="6"}, {["data"]=55, ["description"]="7"}, {["data"]=56, ["description"]="8"}, {["data"]=57, ["description"]="9"}, {["data"]=97, ["description"]="A"}, {["data"]=98, ["description"]="B"}, {["data"]=99, ["description"]="C"}, {["data"]=100, ["description"]="D"}, {["data"]=101, ["description"]="E"}, {["data"]=102, ["description"]="F"}, {["data"]=103, ["description"]="G"}, {["data"]=104, ["description"]="H"}, {["data"]=105, ["description"]="I"}, {["data"]=106, ["description"]="J"}, {["data"]=107, ["description"]="K"}, {["data"]=108, ["description"]="L"}, {["data"]=109, ["description"]="M"}, {["data"]=110, ["description"]="N"}, {["data"]=111, ["description"]="O"}, {["data"]=112, ["description"]="P"}, {["data"]=113, ["description"]="Q"}, {["data"]=114, ["description"]="R"}, {["data"]=115, ["description"]="S"}, {["data"]=116, ["description"]="T"}, {["data"]=117, ["description"]="U"}, {["data"]=118, ["description"]="V"}, {["data"]=119, ["description"]="W"}, {["data"]=120, ["description"]="X"}, {["data"]=121, ["description"]="Y"}, {["data"]=122, ["description"]="Z"}, {["data"]=273, ["description"]="↑"}, {["data"]=274, ["description"]="↓"}, {["data"]=276, ["description"]="←"}, {["data"]=275, ["description"]="→"}}, default = 276},
    {name = "OBC_FOV_PLUS_MORE_KEY", label = "FOV + 5", options = {{["data"]=-1, ["description"]="Disable - 禁用"}, {["data"]=282, ["description"]="F1"}, {["data"]=283, ["description"]="F2"}, {["data"]=284, ["description"]="F3"}, {["data"]=285, ["description"]="F4"}, {["data"]=286, ["description"]="F5"}, {["data"]=287, ["description"]="F6"}, {["data"]=288, ["description"]="F7"}, {["data"]=289, ["description"]="F8"}, {["data"]=290, ["description"]="F9"}, {["data"]=291, ["description"]="F10"}, {["data"]=292, ["description"]="F11"}, {["data"]=293, ["description"]="F12"}, {["data"]=48, ["description"]="0"}, {["data"]=49, ["description"]="1"}, {["data"]=50, ["description"]="2"}, {["data"]=51, ["description"]="3"}, {["data"]=52, ["description"]="4"}, {["data"]=53, ["description"]="5"}, {["data"]=54, ["description"]="6"}, {["data"]=55, ["description"]="7"}, {["data"]=56, ["description"]="8"}, {["data"]=57, ["description"]="9"}, {["data"]=97, ["description"]="A"}, {["data"]=98, ["description"]="B"}, {["data"]=99, ["description"]="C"}, {["data"]=100, ["description"]="D"}, {["data"]=101, ["description"]="E"}, {["data"]=102, ["description"]="F"}, {["data"]=103, ["description"]="G"}, {["data"]=104, ["description"]="H"}, {["data"]=105, ["description"]="I"}, {["data"]=106, ["description"]="J"}, {["data"]=107, ["description"]="K"}, {["data"]=108, ["description"]="L"}, {["data"]=109, ["description"]="M"}, {["data"]=110, ["description"]="N"}, {["data"]=111, ["description"]="O"}, {["data"]=112, ["description"]="P"}, {["data"]=113, ["description"]="Q"}, {["data"]=114, ["description"]="R"}, {["data"]=115, ["description"]="S"}, {["data"]=116, ["description"]="T"}, {["data"]=117, ["description"]="U"}, {["data"]=118, ["description"]="V"}, {["data"]=119, ["description"]="W"}, {["data"]=120, ["description"]="X"}, {["data"]=121, ["description"]="Y"}, {["data"]=122, ["description"]="Z"}, {["data"]=273, ["description"]="↑"}, {["data"]=274, ["description"]="↓"}, {["data"]=276, ["description"]="←"}, {["data"]=275, ["description"]="→"}}, default = 273},
    {name = "OBC_FOV_MINUS_MORE_KEY", label = "FOV - 5", options = {{["data"]=-1, ["description"]="Disable - 禁用"}, {["data"]=282, ["description"]="F1"}, {["data"]=283, ["description"]="F2"}, {["data"]=284, ["description"]="F3"}, {["data"]=285, ["description"]="F4"}, {["data"]=286, ["description"]="F5"}, {["data"]=287, ["description"]="F6"}, {["data"]=288, ["description"]="F7"}, {["data"]=289, ["description"]="F8"}, {["data"]=290, ["description"]="F9"}, {["data"]=291, ["description"]="F10"}, {["data"]=292, ["description"]="F11"}, {["data"]=293, ["description"]="F12"}, {["data"]=48, ["description"]="0"}, {["data"]=49, ["description"]="1"}, {["data"]=50, ["description"]="2"}, {["data"]=51, ["description"]="3"}, {["data"]=52, ["description"]="4"}, {["data"]=53, ["description"]="5"}, {["data"]=54, ["description"]="6"}, {["data"]=55, ["description"]="7"}, {["data"]=56, ["description"]="8"}, {["data"]=57, ["description"]="9"}, {["data"]=97, ["description"]="A"}, {["data"]=98, ["description"]="B"}, {["data"]=99, ["description"]="C"}, {["data"]=100, ["description"]="D"}, {["data"]=101, ["description"]="E"}, {["data"]=102, ["description"]="F"}, {["data"]=103, ["description"]="G"}, {["data"]=104, ["description"]="H"}, {["data"]=105, ["description"]="I"}, {["data"]=106, ["description"]="J"}, {["data"]=107, ["description"]="K"}, {["data"]=108, ["description"]="L"}, {["data"]=109, ["description"]="M"}, {["data"]=110, ["description"]="N"}, {["data"]=111, ["description"]="O"}, {["data"]=112, ["description"]="P"}, {["data"]=113, ["description"]="Q"}, {["data"]=114, ["description"]="R"}, {["data"]=115, ["description"]="S"}, {["data"]=116, ["description"]="T"}, {["data"]=117, ["description"]="U"}, {["data"]=118, ["description"]="V"}, {["data"]=119, ["description"]="W"}, {["data"]=120, ["description"]="X"}, {["data"]=121, ["description"]="Y"}, {["data"]=122, ["description"]="Z"}, {["data"]=273, ["description"]="↑"}, {["data"]=274, ["description"]="↓"}, {["data"]=276, ["description"]="←"}, {["data"]=275, ["description"]="→"}}, default = 274},
    heading("Biểu tượng bản đồ"),
    heading("Thú đồng hành"),
    {name = "chester_eyebone", label = "Chester Eyebone", options = yes_no, default = true},
    {name = "hutch_fishbowl", label = "Hutch Fishbowl", options = yes_no, default = true},
    heading("Hang và động vật"),
    {name = "batcave", label = "Batcave", options = yes_no, default = true},
    {name = "catcoonden", label = "Catcoonden", options = yes_no, default = true},
    {name = "molehill", label = "Molehill", options = yes_no, default = true},
    {name = "rabbithole", label = "Rabbithole", options = yes_no, default = true},
    {name = "slurtlehole", label = "Slurtlehole", options = yes_no, default = true},
    {name = "spiderhole", label = "Spiderhole", options = yes_no, default = true},
    heading("Trùm"),
    {name = "alterguardian_phase3dead", label = "Alterguardian Phase3dead", options = yes_no, default = true},
    {name = "antlion", label = "Antlion", options = yes_no, default = true},
    {name = "bearger", label = "Bearger", options = yes_no, default = true},
    {name = "beequeen", label = "Beequeen", options = yes_no, default = true},
    {name = "beequeenhivegrown", label = "Beequeenhivegrown", options = yes_no, default = true},
    {name = "bishop_nightmare", label = "Bishop Nightmare", options = yes_no, default = true},
    {name = "alterguardian_phase1", label = "Celestial Champion Phase 1", options = yes_no, default = true},
    {name = "alterguardian_phase2", label = "Celestial Champion Phase 2", options = yes_no, default = true},
    {name = "alterguardian_phase3", label = "Celestial Champion Phase 3", options = yes_no, default = true},
    {name = "crabking", label = "Crabking", options = yes_no, default = true},
    {name = "daywalker", label = "Daywalker", options = yes_no, default = true},
    {name = "deerclops", label = "Deerclops", options = yes_no, default = true},
    {name = "dragonfly", label = "Dragonfly", options = yes_no, default = true},
    {name = "eyeofterror", label = "Eyeofterror", options = yes_no, default = true},
    {name = "knight_nightmare", label = "Knight Nightmare", options = yes_no, default = true},
    {name = "leif", label = "Leif", options = yes_no, default = true},
    {name = "leif_sparse", label = "Leif Sparse", options = yes_no, default = true},
    {name = "lordfruitfly", label = "Lordfruitfly", options = yes_no, default = true},
    {name = "malbatross", label = "Malbatross", options = yes_no, default = true},
    {name = "minotaur", label = "Minotaur", options = yes_no, default = true},
    {name = "moose", label = "Moose", options = yes_no, default = true},
    {name = "rook_nightmare", label = "Rook Nightmare", options = yes_no, default = true},
    {name = "shadow_bishop", label = "Shadow Bishop", options = yes_no, default = true},
    {name = "shadow_knight", label = "Shadow Knight", options = yes_no, default = true},
    {name = "shadow_rook", label = "Shadow Rook", options = yes_no, default = true},
    {name = "toadstool", label = "Toadstool", options = yes_no, default = true},
    {name = "toadstool_dark", label = "Toadstool Dark", options = yes_no, default = true},
    heading("Sinh vật"),
    {name = "abigail", label = "Abigail", options = yes_no, default = true},
    {name = "babybeefalo", label = "Babybeefalo", options = yes_no, default = true},
    {name = "bat", label = "Bat", options = yes_no, default = true},
    {name = "beefalo", label = "Beefalo", options = yes_no, default = true},
    {name = "birchnutdrake", label = "Birchnutdrake", options = yes_no, default = true},
    {name = "bishop", label = "Bishop", options = yes_no, default = true},
    {name = "bunnyman", label = "Bunnyman", options = yes_no, default = true},
    {name = "butterfly", label = "Butterfly", options = yes_no, default = true},
    {name = "canary", label = "Canary", options = yes_no, default = true},
    {name = "canary_poisoned", label = "Canary Poisoned", options = yes_no, default = true},
    {name = "catcoon", label = "Catcoon", options = yes_no, default = true},
    {name = "crawlinghorror", label = "Crawlinghorror", options = yes_no, default = true},
    {name = "crawlingnightmare", label = "Crawlingnightmare", options = yes_no, default = true},
    {name = "crow", label = "Crow", options = yes_no, default = true},
    {name = "deer", label = "Deer", options = yes_no, default = true},
    {name = "deer_blue", label = "Deer Blue", options = yes_no, default = true},
    {name = "deer_red", label = "Deer Red", options = yes_no, default = true},
    {name = "eyeplant", label = "Eyeplant", options = yes_no, default = true},
    {name = "firehound", label = "Firehound", options = yes_no, default = true},
    {name = "frog", label = "Frog", options = yes_no, default = true},
    {name = "fruitfly", label = "Fruit Fly (Non-Friendly)", options = yes_no, default = true},
    {name = "ghost", label = "Ghost", options = yes_no, default = true},
    {name = "hound", label = "Hound", options = yes_no, default = true},
    {name = "icehound", label = "Icehound", options = yes_no, default = true},
    {name = "knight", label = "Knight", options = yes_no, default = true},
    {name = "koalefant_summer", label = "Koalefant Summer", options = yes_no, default = true},
    {name = "koalefant_winter", label = "Koalefant Winter", options = yes_no, default = true},
    {name = "krampus", label = "Krampus", options = yes_no, default = true},
    {name = "lavae", label = "Lavae", options = yes_no, default = true},
    {name = "lavae_pet", label = "Lavae Pet", options = yes_no, default = true},
    {name = "lightninggoat", label = "Lightninggoat", options = yes_no, default = true},
    {name = "little_walrus", label = "Little Walrus", options = yes_no, default = true},
    {name = "mandrake", label = "Mandrake", options = yes_no, default = true},
    {name = "mandrake_active", label = "Mandrake Active", options = yes_no, default = true},
    {name = "mandrake_planted", label = "Mandrake Planted", options = yes_no, default = true},
    {name = "merm", label = "Merm", options = yes_no, default = true},
    {name = "mole", label = "Mole", options = yes_no, default = true},
    {name = "monkey", label = "Monkey", options = yes_no, default = true},
    {name = "mosquito", label = "Mosquito", options = yes_no, default = true},
    {name = "mossling", label = "Mossling", options = yes_no, default = true},
    {name = "nightmarebeak", label = "Nightmarebeak", options = yes_no, default = true},
    {name = "perd", label = "Gobbler", options = yes_no, default = true},
    {name = "pigguard", label = "Pigguard", options = yes_no, default = true},
    {name = "pigman", label = "Pigman", options = yes_no, default = true},
    {name = "powder_monkey", label = "Powder Monkey", options = yes_no, default = true},
    {name = "rabbit", label = "Rabbit", options = yes_no, default = true},
    {name = "ruins_shadeling", label = "Resting Horror", options = yes_no, default = true},
    {name = "robin", label = "Robin", options = yes_no, default = true},
    {name = "robin_winter", label = "Robin Winter", options = yes_no, default = true},
    {name = "rocky", label = "Rocky", options = yes_no, default = true},
    {name = "rook", label = "Rook", options = yes_no, default = true},
    {name = "slurper", label = "Slurper", options = yes_no, default = true},
    {name = "slurtle", label = "Slurtle", options = yes_no, default = true},
    {name = "snurtle", label = "Snurtle", options = yes_no, default = true},
    {name = "spider", label = "Spider", options = yes_no, default = true},
    {name = "spider_dropper", label = "Spider Dropper", options = yes_no, default = true},
    {name = "spider_hider", label = "Spider Hider", options = yes_no, default = true},
    {name = "spider_spitter", label = "Spider Spitter", options = yes_no, default = true},
    {name = "spider_warrior", label = "Spider Warrior", options = yes_no, default = true},
    {name = "spiderqueen", label = "Spiderqueen", options = yes_no, default = true},
    {name = "stalker", label = "Stalker", options = yes_no, default = true},
    {name = "stalker_atrium", label = "Stalker Atrium", options = yes_no, default = true},
    {name = "stalker_forest", label = "Stalker Forest", options = yes_no, default = true},
    {name = "stalker_minion1", label = "Stalker Minion1", options = yes_no, default = true},
    {name = "stalker_minion2", label = "Stalker Minion2", options = yes_no, default = true},
    {name = "tallbird", label = "Tallbird", options = yes_no, default = true},
    {name = "tentacle", label = "Tentacle", options = yes_no, default = true},
    {name = "terrorbeak", label = "Terrorbeak", options = yes_no, default = true},
    {name = "walrus", label = "Walrus", options = yes_no, default = true},
    {name = "wanderingtrader", label = "Wandering Trader", options = yes_no, default = true},
    {name = "warg", label = "Warg", options = yes_no, default = true},
    {name = "warglet", label = "Varglet", options = yes_no, default = true},
    {name = "worm", label = "Worm", options = yes_no, default = true},
    heading("Tài nguyên"),
    {name = "alterguardianhatshard", label = "Alterguardianhatshard", options = yes_no, default = true},
    {name = "animal_track", label = "Animal Track", options = yes_no, default = true},
    {name = "boards", label = "Boards", options = yes_no, default = true},
    {name = "bluegem", label = "Bluegem", options = yes_no, default = true},
    {name = "dirtpile", label = "Suspicious Dirt Pile", options = yes_no, default = true},
    {name = "flint", label = "Flint", options = yes_no, default = true},
    {name = "gears", label = "Gears", options = yes_no, default = true},
    {name = "goldnugget", label = "Goldnugget", options = yes_no, default = true},
    {name = "greengem", label = "Greengem", options = yes_no, default = true},
    {name = "houndbone", label = "Houndbone", options = yes_no, default = true},
    {name = "manrabbit_tail", label = "Bunny Puff", options = yes_no, default = true},
    {name = "poop", label = "Manure", options = yes_no, default = true},
    {name = "orangegem", label = "Orangegem", options = yes_no, default = true},
    {name = "purplegem", label = "Purplegem", options = yes_no, default = true},
    {name = "redgem", label = "Redgem", options = yes_no, default = true},
    {name = "rocks", label = "Rocks", options = yes_no, default = true},
    {name = "skeleton", label = "Skeleton", options = yes_no, default = true},
    {name = "yellowgem", label = "Yellowgem", options = yes_no, default = true},
    heading("Công trình"),
    {name = "ancient_altar", label = "Ancient Altar", options = yes_no, default = true},
    {name = "ancient_altar_broken", label = "Ancient Altar Broken", options = yes_no, default = true},
    {name = "mermhead", label = "Mermhead", options = yes_no, default = true},
    {name = "mermhouse", label = "Merm House", options = yes_no, default = true},
    {name = "pighead", label = "Pighead", options = yes_no, default = true},
    {name = "pigtorch", label = "Pigtorch", options = yes_no, default = true},
    {name = "stagehand", label = "Stagehand", options = yes_no, default = true},
    {name = "wall_hay", label = "Wall Hay", options = yes_no, default = true},
    {name = "wall_moonrock", label = "Wall Moonrock", options = yes_no, default = true},
    {name = "wall_ruins", label = "Wall Ruins", options = yes_no, default = true},
    {name = "wall_stone", label = "Wall Stone", options = yes_no, default = true},
    {name = "wall_wood", label = "Wall Wood", options = yes_no, default = true},
    heading("Trang phục"),
    {name = "sewing_kit", label = "Sewing Kit", options = yes_no, default = true},
    {name = "flowerhat", label = "Garland", options = yes_no, default = true},
    {name = "strawhat", label = "Straw Hat", options = yes_no, default = true},
    {name = "tophat", label = "Top Hat", options = yes_no, default = true},
    {name = "beefalohat", label = "Beefalo Hat", options = yes_no, default = true},
    {name = "featherhat", label = "Feather Hat", options = yes_no, default = true},
    {name = "bushhat", label = "Bush Hat", options = yes_no, default = true},
    {name = "winterhat", label = "Winter Hat", options = yes_no, default = true},
    {name = "beehat", label = "Beekeeper Hat", options = yes_no, default = true},
    {name = "earmuffshat", label = "Rabbit Earmuffs", options = yes_no, default = true},
    {name = "watermelonhat", label = "Fashion Melon", options = yes_no, default = true},
    {name = "sweatervest", label = "Dapper Vest", options = yes_no, default = true},
    {name = "trunkvest_summer", label = "Breezy Vest", options = yes_no, default = true},
    {name = "trunkvest_winter", label = "Puffy Vest", options = yes_no, default = true},
    heading("Dụng cụ"),
    {name = "cane", label = "Walking Cane", options = yes_no, default = true},
    {name = "walking_stick", label = "Wooden Cane", options = yes_no, default = true},
    {name = "axe", label = "Axe", options = yes_no, default = true},
    {name = "goldenaxe", label = "Goldenaxe", options = yes_no, default = true},
    {name = "goldenpickaxe", label = "Goldenpickaxe", options = yes_no, default = true},
    {name = "goldenpitchfork", label = "Goldenpitchfork", options = yes_no, default = true},
    {name = "goldenshovel", label = "Goldenshovel", options = yes_no, default = true},
    {name = "farm_hoe", label = "Garden Hoe", options = yes_no, default = true},
    {name = "golden_farm_hoe", label = "Splendid Garden Hoe", options = yes_no, default = true},
    {name = "hammer", label = "Hammer", options = yes_no, default = true},
    {name = "orangestaff", label = "The Lazy Explorer", options = yes_no, default = true},
    {name = "icestaff", label = "Ice Staff", options = yes_no, default = true},
    {name = "greenstaff", label = "Deconstruction Staff", options = yes_no, default = true},
    {name = "yellowstaff", label = "Star Caller's Staff", options = yes_no, default = true},
    {name = "telestaff", label = "Telelocator Staff", options = yes_no, default = true},
    {name = "firestaff", label = "Fire Staff", options = yes_no, default = true},
    {name = "staff_lunarplant", label = "Brightshade Staff", options = yes_no, default = true},
    {name = "staff_tornado", label = "Weather Pain", options = yes_no, default = true},
    {name = "opalstaff", label = "Moon Caller's Staff", options = yes_no, default = true},
    {name = "moonglassaxe", label = "Moonglassaxe", options = yes_no, default = true},
    {name = "pickaxe", label = "Pickaxe", options = yes_no, default = true},
    {name = "pitchfork", label = "Pitchfork", options = yes_no, default = true},
    {name = "razor", label = "Razor", options = yes_no, default = true},
    {name = "shovel", label = "Shovel", options = yes_no, default = true},
    heading("Thực vật"),
    {name = "blue_mushroom", label = "Blue Mushroom", options = yes_no, default = true},
    {name = "carrot_planted", label = "Carrot Planted", options = yes_no, default = true},
    {name = "flower", label = "Flowers", options = yes_no, default = true},
    {name = "green_mushroom", label = "Green Mushroom", options = yes_no, default = true},
    {name = "marsh_bush", label = "Marsh Bush", options = yes_no, default = true},
    {name = "red_mushroom", label = "Red Mushroom", options = yes_no, default = true},
    {name = "seeds", label = "Seeds", options = yes_no, default = true},
    {name = "wormlight_plant", label = "Wormlight Plant", options = yes_no, default = true},
    heading("Thiết lập khác"),
    {name = "persistent_icons", label = "Structure & Item Persistence", options = yes_no, default = true},
    {name = "creature_persistent_icons", label = "Creature & Boss Persistence", options = yes_no, default = false},
    heading("Thả vật phẩm theo lưới"),
    {name = "CYCLE_OFFSET_KEY", label = "Toggle alignment offset", options = {{["data"]="KEY_A", ["description"]="A"}, {["data"]="KEY_B", ["description"]="B"}, {["data"]="KEY_C", ["description"]="C"}, {["data"]="KEY_D", ["description"]="D"}, {["data"]="KEY_E", ["description"]="E"}, {["data"]="KEY_F", ["description"]="F"}, {["data"]="KEY_G", ["description"]="G"}, {["data"]="KEY_H", ["description"]="H"}, {["data"]="KEY_I", ["description"]="I"}, {["data"]="KEY_J", ["description"]="J"}, {["data"]="KEY_K", ["description"]="K"}, {["data"]="KEY_L", ["description"]="L"}, {["data"]="KEY_M", ["description"]="M"}, {["data"]="KEY_N", ["description"]="N"}, {["data"]="KEY_O", ["description"]="O"}, {["data"]="KEY_P", ["description"]="P"}, {["data"]="KEY_Q", ["description"]="Q"}, {["data"]="KEY_R", ["description"]="R"}, {["data"]="KEY_S", ["description"]="S"}, {["data"]="KEY_T", ["description"]="T"}, {["data"]="KEY_U", ["description"]="U"}, {["data"]="KEY_V", ["description"]="V"}, {["data"]="KEY_W", ["description"]="W"}, {["data"]="KEY_X", ["description"]="X"}, {["data"]="KEY_Y", ["description"]="Y"}, {["data"]="KEY_Z", ["description"]="Z"}, {["data"]="KEY_F1", ["description"]="F1"}, {["data"]="KEY_F2", ["description"]="F2"}, {["data"]="KEY_F3", ["description"]="F3"}, {["data"]="KEY_F4", ["description"]="F4"}, {["data"]="KEY_F5", ["description"]="F5"}, {["data"]="KEY_F6", ["description"]="F6"}, {["data"]="KEY_F7", ["description"]="F7"}, {["data"]="KEY_F8", ["description"]="F8"}, {["data"]="KEY_F9", ["description"]="F9"}, {["data"]="KEY_F10", ["description"]="F10"}, {["data"]="KEY_F11", ["description"]="F11"}, {["data"]="KEY_F12", ["description"]="F12"}, {["data"]="KEY_LALT", ["description"]="LAlt"}, {["data"]="KEY_RALT", ["description"]="RAlt"}, {["data"]="KEY_LCTRL", ["description"]="LCtrl"}, {["data"]="KEY_RCTRL", ["description"]="RCtrl"}, {["data"]="KEY_LSHIFT", ["description"]="LShift"}, {["data"]="KEY_RSHIFT", ["description"]="RShift"}, {["data"]="KEY_TAB", ["description"]="Tab"}, {["data"]="KEY_CAPSLOCK", ["description"]="Capslock"}, {["data"]="KEY_SPACE", ["description"]="Space"}, {["data"]="KEY_MINUS", ["description"]="Minus"}, {["data"]="KEY_EQUALS", ["description"]="Equals"}, {["data"]="KEY_BACKSPACE", ["description"]="Backspace"}, {["data"]="KEY_INSERT", ["description"]="Insert"}, {["data"]="KEY_HOME", ["description"]="Home"}, {["data"]="KEY_DELETE", ["description"]="Delete"}, {["data"]="KEY_END", ["description"]="End"}, {["data"]="KEY_PAGEUP", ["description"]="Pageup"}, {["data"]="KEY_PAGEDOWN", ["description"]="Pagedown"}, {["data"]="KEY_PRINT", ["description"]="Print"}, {["data"]="KEY_SCROLLOCK", ["description"]="Scrollock"}, {["data"]="KEY_PAUSE", ["description"]="Pause"}, {["data"]="KEY_PERIOD", ["description"]="Period"}, {["data"]="KEY_SLASH", ["description"]="Slash"}, {["data"]="KEY_SEMICOLON", ["description"]="Semicolon"}, {["data"]="KEY_LEFTBRACKET", ["description"]="LeftBracket"}, {["data"]="KEY_RIGHTBRACKET", ["description"]="RightBracket"}, {["data"]="KEY_BACKSLASH", ["description"]="Backslash"}, {["data"]="KEY_UP", ["description"]="Up"}, {["data"]="KEY_DOWN", ["description"]="Down"}, {["data"]="KEY_LEFT", ["description"]="Left"}, {["data"]="KEY_RIGHT", ["description"]="Right"}, {["data"]=false, ["description"]="Disabled"}}, default = "KEY_T", hover = "Toggle between aligning on (eg. tile) centers or corners"},
    {name = "CYCLE_RESOLUTION_KEY", label = "Change resolution", options = {{["data"]="KEY_A", ["description"]="A"}, {["data"]="KEY_B", ["description"]="B"}, {["data"]="KEY_C", ["description"]="C"}, {["data"]="KEY_D", ["description"]="D"}, {["data"]="KEY_E", ["description"]="E"}, {["data"]="KEY_F", ["description"]="F"}, {["data"]="KEY_G", ["description"]="G"}, {["data"]="KEY_H", ["description"]="H"}, {["data"]="KEY_I", ["description"]="I"}, {["data"]="KEY_J", ["description"]="J"}, {["data"]="KEY_K", ["description"]="K"}, {["data"]="KEY_L", ["description"]="L"}, {["data"]="KEY_M", ["description"]="M"}, {["data"]="KEY_N", ["description"]="N"}, {["data"]="KEY_O", ["description"]="O"}, {["data"]="KEY_P", ["description"]="P"}, {["data"]="KEY_Q", ["description"]="Q"}, {["data"]="KEY_R", ["description"]="R"}, {["data"]="KEY_S", ["description"]="S"}, {["data"]="KEY_T", ["description"]="T"}, {["data"]="KEY_U", ["description"]="U"}, {["data"]="KEY_V", ["description"]="V"}, {["data"]="KEY_W", ["description"]="W"}, {["data"]="KEY_X", ["description"]="X"}, {["data"]="KEY_Y", ["description"]="Y"}, {["data"]="KEY_Z", ["description"]="Z"}, {["data"]="KEY_F1", ["description"]="F1"}, {["data"]="KEY_F2", ["description"]="F2"}, {["data"]="KEY_F3", ["description"]="F3"}, {["data"]="KEY_F4", ["description"]="F4"}, {["data"]="KEY_F5", ["description"]="F5"}, {["data"]="KEY_F6", ["description"]="F6"}, {["data"]="KEY_F7", ["description"]="F7"}, {["data"]="KEY_F8", ["description"]="F8"}, {["data"]="KEY_F9", ["description"]="F9"}, {["data"]="KEY_F10", ["description"]="F10"}, {["data"]="KEY_F11", ["description"]="F11"}, {["data"]="KEY_F12", ["description"]="F12"}, {["data"]="KEY_LALT", ["description"]="LAlt"}, {["data"]="KEY_RALT", ["description"]="RAlt"}, {["data"]="KEY_LCTRL", ["description"]="LCtrl"}, {["data"]="KEY_RCTRL", ["description"]="RCtrl"}, {["data"]="KEY_LSHIFT", ["description"]="LShift"}, {["data"]="KEY_RSHIFT", ["description"]="RShift"}, {["data"]="KEY_TAB", ["description"]="Tab"}, {["data"]="KEY_CAPSLOCK", ["description"]="Capslock"}, {["data"]="KEY_SPACE", ["description"]="Space"}, {["data"]="KEY_MINUS", ["description"]="Minus"}, {["data"]="KEY_EQUALS", ["description"]="Equals"}, {["data"]="KEY_BACKSPACE", ["description"]="Backspace"}, {["data"]="KEY_INSERT", ["description"]="Insert"}, {["data"]="KEY_HOME", ["description"]="Home"}, {["data"]="KEY_DELETE", ["description"]="Delete"}, {["data"]="KEY_END", ["description"]="End"}, {["data"]="KEY_PAGEUP", ["description"]="Pageup"}, {["data"]="KEY_PAGEDOWN", ["description"]="Pagedown"}, {["data"]="KEY_PRINT", ["description"]="Print"}, {["data"]="KEY_SCROLLOCK", ["description"]="Scrollock"}, {["data"]="KEY_PAUSE", ["description"]="Pause"}, {["data"]="KEY_PERIOD", ["description"]="Period"}, {["data"]="KEY_SLASH", ["description"]="Slash"}, {["data"]="KEY_SEMICOLON", ["description"]="Semicolon"}, {["data"]="KEY_LEFTBRACKET", ["description"]="LeftBracket"}, {["data"]="KEY_RIGHTBRACKET", ["description"]="RightBracket"}, {["data"]="KEY_BACKSLASH", ["description"]="Backslash"}, {["data"]="KEY_UP", ["description"]="Up"}, {["data"]="KEY_DOWN", ["description"]="Down"}, {["data"]="KEY_LEFT", ["description"]="Left"}, {["data"]="KEY_RIGHT", ["description"]="Right"}, {["data"]=false, ["description"]="Disabled"}}, default = "KEY_G", hover = "Cycle between 1/5, 1/4, 1/2, and full tile spacing"},
    {name = "RESTORE_DEFAULTS_KEY", label = "Reset defaults", options = {{["data"]="KEY_A", ["description"]="A"}, {["data"]="KEY_B", ["description"]="B"}, {["data"]="KEY_C", ["description"]="C"}, {["data"]="KEY_D", ["description"]="D"}, {["data"]="KEY_E", ["description"]="E"}, {["data"]="KEY_F", ["description"]="F"}, {["data"]="KEY_G", ["description"]="G"}, {["data"]="KEY_H", ["description"]="H"}, {["data"]="KEY_I", ["description"]="I"}, {["data"]="KEY_J", ["description"]="J"}, {["data"]="KEY_K", ["description"]="K"}, {["data"]="KEY_L", ["description"]="L"}, {["data"]="KEY_M", ["description"]="M"}, {["data"]="KEY_N", ["description"]="N"}, {["data"]="KEY_O", ["description"]="O"}, {["data"]="KEY_P", ["description"]="P"}, {["data"]="KEY_Q", ["description"]="Q"}, {["data"]="KEY_R", ["description"]="R"}, {["data"]="KEY_S", ["description"]="S"}, {["data"]="KEY_T", ["description"]="T"}, {["data"]="KEY_U", ["description"]="U"}, {["data"]="KEY_V", ["description"]="V"}, {["data"]="KEY_W", ["description"]="W"}, {["data"]="KEY_X", ["description"]="X"}, {["data"]="KEY_Y", ["description"]="Y"}, {["data"]="KEY_Z", ["description"]="Z"}, {["data"]="KEY_F1", ["description"]="F1"}, {["data"]="KEY_F2", ["description"]="F2"}, {["data"]="KEY_F3", ["description"]="F3"}, {["data"]="KEY_F4", ["description"]="F4"}, {["data"]="KEY_F5", ["description"]="F5"}, {["data"]="KEY_F6", ["description"]="F6"}, {["data"]="KEY_F7", ["description"]="F7"}, {["data"]="KEY_F8", ["description"]="F8"}, {["data"]="KEY_F9", ["description"]="F9"}, {["data"]="KEY_F10", ["description"]="F10"}, {["data"]="KEY_F11", ["description"]="F11"}, {["data"]="KEY_F12", ["description"]="F12"}, {["data"]="KEY_LALT", ["description"]="LAlt"}, {["data"]="KEY_RALT", ["description"]="RAlt"}, {["data"]="KEY_LCTRL", ["description"]="LCtrl"}, {["data"]="KEY_RCTRL", ["description"]="RCtrl"}, {["data"]="KEY_LSHIFT", ["description"]="LShift"}, {["data"]="KEY_RSHIFT", ["description"]="RShift"}, {["data"]="KEY_TAB", ["description"]="Tab"}, {["data"]="KEY_CAPSLOCK", ["description"]="Capslock"}, {["data"]="KEY_SPACE", ["description"]="Space"}, {["data"]="KEY_MINUS", ["description"]="Minus"}, {["data"]="KEY_EQUALS", ["description"]="Equals"}, {["data"]="KEY_BACKSPACE", ["description"]="Backspace"}, {["data"]="KEY_INSERT", ["description"]="Insert"}, {["data"]="KEY_HOME", ["description"]="Home"}, {["data"]="KEY_DELETE", ["description"]="Delete"}, {["data"]="KEY_END", ["description"]="End"}, {["data"]="KEY_PAGEUP", ["description"]="Pageup"}, {["data"]="KEY_PAGEDOWN", ["description"]="Pagedown"}, {["data"]="KEY_PRINT", ["description"]="Print"}, {["data"]="KEY_SCROLLOCK", ["description"]="Scrollock"}, {["data"]="KEY_PAUSE", ["description"]="Pause"}, {["data"]="KEY_PERIOD", ["description"]="Period"}, {["data"]="KEY_SLASH", ["description"]="Slash"}, {["data"]="KEY_SEMICOLON", ["description"]="Semicolon"}, {["data"]="KEY_LEFTBRACKET", ["description"]="LeftBracket"}, {["data"]="KEY_RIGHTBRACKET", ["description"]="RightBracket"}, {["data"]="KEY_BACKSLASH", ["description"]="Backslash"}, {["data"]="KEY_UP", ["description"]="Up"}, {["data"]="KEY_DOWN", ["description"]="Down"}, {["data"]="KEY_LEFT", ["description"]="Left"}, {["data"]="KEY_RIGHT", ["description"]="Right"}, {["data"]=false, ["description"]="Disabled"}}, default = "KEY_EQUALS", hover = "Disables the offset and restores spacing to 1/4 tile"},
    {name = "TOGGLE_PLACERS_KEY", label = "Toggle placer visibility", options = {{["data"]="KEY_A", ["description"]="A"}, {["data"]="KEY_B", ["description"]="B"}, {["data"]="KEY_C", ["description"]="C"}, {["data"]="KEY_D", ["description"]="D"}, {["data"]="KEY_E", ["description"]="E"}, {["data"]="KEY_F", ["description"]="F"}, {["data"]="KEY_G", ["description"]="G"}, {["data"]="KEY_H", ["description"]="H"}, {["data"]="KEY_I", ["description"]="I"}, {["data"]="KEY_J", ["description"]="J"}, {["data"]="KEY_K", ["description"]="K"}, {["data"]="KEY_L", ["description"]="L"}, {["data"]="KEY_M", ["description"]="M"}, {["data"]="KEY_N", ["description"]="N"}, {["data"]="KEY_O", ["description"]="O"}, {["data"]="KEY_P", ["description"]="P"}, {["data"]="KEY_Q", ["description"]="Q"}, {["data"]="KEY_R", ["description"]="R"}, {["data"]="KEY_S", ["description"]="S"}, {["data"]="KEY_T", ["description"]="T"}, {["data"]="KEY_U", ["description"]="U"}, {["data"]="KEY_V", ["description"]="V"}, {["data"]="KEY_W", ["description"]="W"}, {["data"]="KEY_X", ["description"]="X"}, {["data"]="KEY_Y", ["description"]="Y"}, {["data"]="KEY_Z", ["description"]="Z"}, {["data"]="KEY_F1", ["description"]="F1"}, {["data"]="KEY_F2", ["description"]="F2"}, {["data"]="KEY_F3", ["description"]="F3"}, {["data"]="KEY_F4", ["description"]="F4"}, {["data"]="KEY_F5", ["description"]="F5"}, {["data"]="KEY_F6", ["description"]="F6"}, {["data"]="KEY_F7", ["description"]="F7"}, {["data"]="KEY_F8", ["description"]="F8"}, {["data"]="KEY_F9", ["description"]="F9"}, {["data"]="KEY_F10", ["description"]="F10"}, {["data"]="KEY_F11", ["description"]="F11"}, {["data"]="KEY_F12", ["description"]="F12"}, {["data"]="KEY_LALT", ["description"]="LAlt"}, {["data"]="KEY_RALT", ["description"]="RAlt"}, {["data"]="KEY_LCTRL", ["description"]="LCtrl"}, {["data"]="KEY_RCTRL", ["description"]="RCtrl"}, {["data"]="KEY_LSHIFT", ["description"]="LShift"}, {["data"]="KEY_RSHIFT", ["description"]="RShift"}, {["data"]="KEY_TAB", ["description"]="Tab"}, {["data"]="KEY_CAPSLOCK", ["description"]="Capslock"}, {["data"]="KEY_SPACE", ["description"]="Space"}, {["data"]="KEY_MINUS", ["description"]="Minus"}, {["data"]="KEY_EQUALS", ["description"]="Equals"}, {["data"]="KEY_BACKSPACE", ["description"]="Backspace"}, {["data"]="KEY_INSERT", ["description"]="Insert"}, {["data"]="KEY_HOME", ["description"]="Home"}, {["data"]="KEY_DELETE", ["description"]="Delete"}, {["data"]="KEY_END", ["description"]="End"}, {["data"]="KEY_PAGEUP", ["description"]="Pageup"}, {["data"]="KEY_PAGEDOWN", ["description"]="Pagedown"}, {["data"]="KEY_PRINT", ["description"]="Print"}, {["data"]="KEY_SCROLLOCK", ["description"]="Scrollock"}, {["data"]="KEY_PAUSE", ["description"]="Pause"}, {["data"]="KEY_PERIOD", ["description"]="Period"}, {["data"]="KEY_SLASH", ["description"]="Slash"}, {["data"]="KEY_SEMICOLON", ["description"]="Semicolon"}, {["data"]="KEY_LEFTBRACKET", ["description"]="LeftBracket"}, {["data"]="KEY_RIGHTBRACKET", ["description"]="RightBracket"}, {["data"]="KEY_BACKSLASH", ["description"]="Backslash"}, {["data"]="KEY_UP", ["description"]="Up"}, {["data"]="KEY_DOWN", ["description"]="Down"}, {["data"]="KEY_LEFT", ["description"]="Left"}, {["data"]="KEY_RIGHT", ["description"]="Right"}, {["data"]=false, ["description"]="Disabled"}}, default = "KEY_MINUS", hover = "Enables and disables placers being visible while holding an item"},
    {name = "TOGGLE_ENABLED_KEY", label = "Mode", options = {{["data"]="KEY_A", ["description"]="A"}, {["data"]="KEY_B", ["description"]="B"}, {["data"]="KEY_C", ["description"]="C"}, {["data"]="KEY_D", ["description"]="D"}, {["data"]="KEY_E", ["description"]="E"}, {["data"]="KEY_F", ["description"]="F"}, {["data"]="KEY_G", ["description"]="G"}, {["data"]="KEY_H", ["description"]="H"}, {["data"]="KEY_I", ["description"]="I"}, {["data"]="KEY_J", ["description"]="J"}, {["data"]="KEY_K", ["description"]="K"}, {["data"]="KEY_L", ["description"]="L"}, {["data"]="KEY_M", ["description"]="M"}, {["data"]="KEY_N", ["description"]="N"}, {["data"]="KEY_O", ["description"]="O"}, {["data"]="KEY_P", ["description"]="P"}, {["data"]="KEY_Q", ["description"]="Q"}, {["data"]="KEY_R", ["description"]="R"}, {["data"]="KEY_S", ["description"]="S"}, {["data"]="KEY_T", ["description"]="T"}, {["data"]="KEY_U", ["description"]="U"}, {["data"]="KEY_V", ["description"]="V"}, {["data"]="KEY_W", ["description"]="W"}, {["data"]="KEY_X", ["description"]="X"}, {["data"]="KEY_Y", ["description"]="Y"}, {["data"]="KEY_Z", ["description"]="Z"}, {["data"]="KEY_F1", ["description"]="F1"}, {["data"]="KEY_F2", ["description"]="F2"}, {["data"]="KEY_F3", ["description"]="F3"}, {["data"]="KEY_F4", ["description"]="F4"}, {["data"]="KEY_F5", ["description"]="F5"}, {["data"]="KEY_F6", ["description"]="F6"}, {["data"]="KEY_F7", ["description"]="F7"}, {["data"]="KEY_F8", ["description"]="F8"}, {["data"]="KEY_F9", ["description"]="F9"}, {["data"]="KEY_F10", ["description"]="F10"}, {["data"]="KEY_F11", ["description"]="F11"}, {["data"]="KEY_F12", ["description"]="F12"}, {["data"]="KEY_LALT", ["description"]="LAlt"}, {["data"]="KEY_RALT", ["description"]="RAlt"}, {["data"]="KEY_LCTRL", ["description"]="LCtrl"}, {["data"]="KEY_RCTRL", ["description"]="RCtrl"}, {["data"]="KEY_LSHIFT", ["description"]="LShift"}, {["data"]="KEY_RSHIFT", ["description"]="RShift"}, {["data"]="KEY_TAB", ["description"]="Tab"}, {["data"]="KEY_CAPSLOCK", ["description"]="Capslock"}, {["data"]="KEY_SPACE", ["description"]="Space"}, {["data"]="KEY_MINUS", ["description"]="Minus"}, {["data"]="KEY_EQUALS", ["description"]="Equals"}, {["data"]="KEY_BACKSPACE", ["description"]="Backspace"}, {["data"]="KEY_INSERT", ["description"]="Insert"}, {["data"]="KEY_HOME", ["description"]="Home"}, {["data"]="KEY_DELETE", ["description"]="Delete"}, {["data"]="KEY_END", ["description"]="End"}, {["data"]="KEY_PAGEUP", ["description"]="Pageup"}, {["data"]="KEY_PAGEDOWN", ["description"]="Pagedown"}, {["data"]="KEY_PRINT", ["description"]="Print"}, {["data"]="KEY_SCROLLOCK", ["description"]="Scrollock"}, {["data"]="KEY_PAUSE", ["description"]="Pause"}, {["data"]="KEY_PERIOD", ["description"]="Period"}, {["data"]="KEY_SLASH", ["description"]="Slash"}, {["data"]="KEY_SEMICOLON", ["description"]="Semicolon"}, {["data"]="KEY_LEFTBRACKET", ["description"]="LeftBracket"}, {["data"]="KEY_RIGHTBRACKET", ["description"]="RightBracket"}, {["data"]="KEY_BACKSLASH", ["description"]="Backslash"}, {["data"]="KEY_UP", ["description"]="Up"}, {["data"]="KEY_DOWN", ["description"]="Down"}, {["data"]="KEY_LEFT", ["description"]="Left"}, {["data"]="KEY_RIGHT", ["description"]="Right"}, {["data"]=false, ["description"]="Disabled"}}, default = "KEY_H", hover = "Change mode between grid, circle, and disabled. Control+MODE sets origin. Shift+MODE rotates grid around origin."},
    {name = "PLACERS_START_VISIBLE", label = "Default visible placers", options = yes_no, default = true, hover = "Toggle whether placers show up by default while holding an item"},
    {name = "DEFAULT_DROP_RESOLUTION", label = "Default grid spacing", options = {{["data"]=0, ["description"]="1/8 Tile"}, {["data"]=1, ["description"]="1/5 Tile"}, {["data"]=2, ["description"]="1/4 Tile"}, {["data"]=3, ["description"]="1/2 Tile"}, {["data"]=4, ["description"]="1 Tile"}}, default = 2, hover = "Change which grid spacing is used upon entering game or using the Reset Defaults keybind"},
    {name = "DEFAULT_DROP_OFFSET", label = "Default offset grid", options = {{["data"]=0, ["description"]="Normal"}, {["data"]=1, ["description"]="Offset"}}, default = 1, hover = "Change which grid spacing is used upon entering game or using the Reset Defaults keybind"},
    {name = "DEFAULT_MODE", label = "Default mode", options = {{["data"]="grid", ["description"]="Grid"}, {["data"]="polar", ["description"]="Circle"}, {["data"]="disabled", ["description"]="Disabled"}}, default = "grid", hover = "Select which dropper mode is enabled upon entering the game or using the Reset Defaults keybind"},
    heading("Đặt công trình theo lưới"),
    {name = "CTRL", label = "CTRL Turns Mod", options = yes_no, default = false, hover = "Whether holding CTRL enables or disables the mod."},
    {name = "KEYBOARDTOGGLEKEY", label = "Options Button", options = {{["data"]="A", ["description"]="A"}, {["data"]="B", ["description"]="B"}, {["data"]="C", ["description"]="C"}, {["data"]="D", ["description"]="D"}, {["data"]="E", ["description"]="E"}, {["data"]="F", ["description"]="F"}, {["data"]="G", ["description"]="G"}, {["data"]="H", ["description"]="H"}, {["data"]="I", ["description"]="I"}, {["data"]="J", ["description"]="J"}, {["data"]="K", ["description"]="K"}, {["data"]="L", ["description"]="L"}, {["data"]="M", ["description"]="M"}, {["data"]="N", ["description"]="N"}, {["data"]="O", ["description"]="O"}, {["data"]="P", ["description"]="P"}, {["data"]="Q", ["description"]="Q"}, {["data"]="R", ["description"]="R"}, {["data"]="S", ["description"]="S"}, {["data"]="T", ["description"]="T"}, {["data"]="U", ["description"]="U"}, {["data"]="V", ["description"]="V"}, {["data"]="W", ["description"]="W"}, {["data"]="X", ["description"]="X"}, {["data"]="Y", ["description"]="Y"}, {["data"]="Z", ["description"]="Z"}, {["data"]="", ["description"]="None"}}, default = "B", hover = "A key to open the mod's options. On controllers, open\
the scoreboard and then use Menu Misc 3 (left stick click). When set to None, controller is also unbound."},
    {name = "GEOMETRYTOGGLEKEY", label = "Toggle Button", options = {{["data"]="A", ["description"]="A"}, {["data"]="B", ["description"]="B"}, {["data"]="C", ["description"]="C"}, {["data"]="D", ["description"]="D"}, {["data"]="E", ["description"]="E"}, {["data"]="F", ["description"]="F"}, {["data"]="G", ["description"]="G"}, {["data"]="H", ["description"]="H"}, {["data"]="I", ["description"]="I"}, {["data"]="J", ["description"]="J"}, {["data"]="K", ["description"]="K"}, {["data"]="L", ["description"]="L"}, {["data"]="M", ["description"]="M"}, {["data"]="N", ["description"]="N"}, {["data"]="O", ["description"]="O"}, {["data"]="P", ["description"]="P"}, {["data"]="Q", ["description"]="Q"}, {["data"]="R", ["description"]="R"}, {["data"]="S", ["description"]="S"}, {["data"]="T", ["description"]="T"}, {["data"]="U", ["description"]="U"}, {["data"]="V", ["description"]="V"}, {["data"]="W", ["description"]="W"}, {["data"]="X", ["description"]="X"}, {["data"]="Y", ["description"]="Y"}, {["data"]="Z", ["description"]="Z"}, {["data"]="", ["description"]="None"}}, default = "V", hover = "A key to toggle to the most recently used geometry\
(for example, switching between Square and X-Hexagon). No controller binding."},
    {name = "SNAPGRIDKEY", label = "Snap Grid Button", options = {{["data"]="A", ["description"]="A"}, {["data"]="B", ["description"]="B"}, {["data"]="C", ["description"]="C"}, {["data"]="D", ["description"]="D"}, {["data"]="E", ["description"]="E"}, {["data"]="F", ["description"]="F"}, {["data"]="G", ["description"]="G"}, {["data"]="H", ["description"]="H"}, {["data"]="I", ["description"]="I"}, {["data"]="J", ["description"]="J"}, {["data"]="K", ["description"]="K"}, {["data"]="L", ["description"]="L"}, {["data"]="M", ["description"]="M"}, {["data"]="N", ["description"]="N"}, {["data"]="O", ["description"]="O"}, {["data"]="P", ["description"]="P"}, {["data"]="Q", ["description"]="Q"}, {["data"]="R", ["description"]="R"}, {["data"]="S", ["description"]="S"}, {["data"]="T", ["description"]="T"}, {["data"]="U", ["description"]="U"}, {["data"]="V", ["description"]="V"}, {["data"]="W", ["description"]="W"}, {["data"]="X", ["description"]="X"}, {["data"]="Y", ["description"]="Y"}, {["data"]="Z", ["description"]="Z"}, {["data"]="", ["description"]="None"}}, default = "", hover = "A key to snap the grid to have a point centered on the hovered object or point. No controller binding."},
    {name = "SHOWMENU", label = "In-Game Menu", options = yes_no, default = true, hover = "If on, the button opens the menu.\
If off, it just toggles the mod on and off."},
    {name = "BUILDGRID", label = "Show Build Grid", options = yes_no, default = true, hover = "Whether to show the build grid."},
    {name = "GEOMETRY", label = "Grid Geometry", options = {{["data"]="SQUARE", ["description"]="Square"}, {["data"]="DIAMOND", ["description"]="Diamond"}, {["data"]="X_HEXAGON", ["description"]="X Hexagon"}, {["data"]="Z_HEXAGON", ["description"]="Z Hexagon"}, {["data"]="FLAT_HEXAGON", ["description"]="Flat Hexagon"}, {["data"]="POINTY_HEXAGON", ["description"]="Pointy Hexagon"}}, default = "SQUARE", hover = "What build grid geometry to use."},
    {name = "TIMEBUDGET", label = "Refresh Speed", options = {{["data"]=0.1, ["description"]="10%"}, {["data"]=0.2, ["description"]="20%"}, {["data"]=0.3, ["description"]="30%"}, {["data"]=0.4, ["description"]="40%"}, {["data"]=0.5, ["description"]="50%"}, {["data"]=0.6, ["description"]="60%"}, {["data"]=0.7, ["description"]="70%"}, {["data"]=0.8, ["description"]="80%"}, {["data"]=0.9, ["description"]="90%"}, {["data"]=1.0, ["description"]="100%"}, {["data"]=false, ["description"]="Unlimited"}}, default = 0.1, hover = "How much of the available time to use for refreshing the grid.\
Disabling or setting too high will likely cause lag."},
    {name = "HIDEPLACER", label = "Hide Placer", options = yes_no, default = false, hover = "Whether to hide the placer (the ghost version of the item you're placing).\
Hiding it can help you see the grid better."},
    {name = "HIDECURSOR", label = "Hide Cursor Item", options = {{["data"]=1, ["description"]="Hide All"}, {["data"]=true, ["description"]="Show Number"}, {["data"]=false, ["description"]="Show All"}}, default = false, hover = "Whether to hide the cursor item, to better see the grid."},
    {name = "SMARTSPACING", label = "Smart Spacing", options = yes_no, default = false, hover = "Whether to adjust the spacing of the grid based on what object is being placed.\
Allows for optimal grids, but can make it hard to put things just where you want them."},
    {name = "ACTION_TILL", label = "Till Grid", options = yes_no, default = true, hover = "Whether to use a grid for tilling farm soil.\
Automatically turned off when using the Snapping Tills mod."},
    {name = "SMALLGRIDSIZE", label = "Fine Grid Size", options = {{["data"]=0, ["description"]="0"}, {["data"]=2, ["description"]="2"}, {["data"]=4, ["description"]="4"}, {["data"]=6, ["description"]="6"}, {["data"]=8, ["description"]="8"}, {["data"]=10, ["description"]="10"}, {["data"]=12, ["description"]="12"}, {["data"]=14, ["description"]="14"}, {["data"]=16, ["description"]="16"}, {["data"]=18, ["description"]="18"}, {["data"]=20, ["description"]="20"}}, default = 10, hover = "How big to make the grid for things that use a fine grid (structures, plants, etc)."},
    {name = "MEDGRIDSIZE", label = "Medium Grid Size", options = {{["data"]=0, ["description"]="0"}, {["data"]=1, ["description"]="1"}, {["data"]=2, ["description"]="2"}, {["data"]=3, ["description"]="3"}, {["data"]=4, ["description"]="4"}, {["data"]=5, ["description"]="5"}, {["data"]=6, ["description"]="6"}, {["data"]=7, ["description"]="7"}, {["data"]=8, ["description"]="8"}, {["data"]=9, ["description"]="9"}, {["data"]=10, ["description"]="10"}}, default = 6, hover = "How big to make the grid for things that use a medium grid (such as walls, DST crops)."},
    {name = "BIGGRIDSIZE", label = "Large Grid Size", options = {{["data"]=0, ["description"]="0"}, {["data"]=1, ["description"]="1"}, {["data"]=2, ["description"]="2"}, {["data"]=3, ["description"]="3"}, {["data"]=4, ["description"]="4"}, {["data"]=5, ["description"]="5"}}, default = 2, hover = "How big to make the grid for things that use a large grid (such as turf and pitchforks)."},
    {name = "GOODCOLOR", label = "Unblocked Color", options = {{["data"]="green", ["description"]="Green", ["hover"]="The normal green  the game uses."}, {["data"]="blue", ["description"]="Blue", ["hover"]="Blue, helpful if you're red/green colorblind."}, {["data"]="red", ["description"]="Red", ["hover"]="The normal red the game uses."}, {["data"]="white", ["description"]="White", ["hover"]="A bright white, for better visibility."}, {["data"]="black", ["description"]="Black", ["hover"]="Black, to contrast with the brighter colors."}, {["data"]="whiteoutline", ["description"]="Outlined White", ["hover"]="White with a black outline, for the best visibility."}, {["data"]="blackoutline", ["description"]="Outlined Black", ["hover"]="Black with a white outline, for the best visibility."}, {["data"]="hidden", ["description"]="Hidden", ["hover"]="Hide it entirely, because you didn't need to see it anyway, right?"}}, default = "whiteoutline", hover = "The color to use for unblocked points, where you can place things."},
    {name = "BADCOLOR", label = "Blocked Color", options = {{["data"]="green", ["description"]="Green", ["hover"]="The normal green  the game uses."}, {["data"]="blue", ["description"]="Blue", ["hover"]="Blue, helpful if you're red/green colorblind."}, {["data"]="red", ["description"]="Red", ["hover"]="The normal red the game uses."}, {["data"]="white", ["description"]="White", ["hover"]="A bright white, for better visibility."}, {["data"]="black", ["description"]="Black", ["hover"]="Black, to contrast with the brighter colors."}, {["data"]="whiteoutline", ["description"]="Outlined White", ["hover"]="White with a black outline, for the best visibility."}, {["data"]="blackoutline", ["description"]="Outlined Black", ["hover"]="Black with a white outline, for the best visibility."}, {["data"]="hidden", ["description"]="Hidden", ["hover"]="Hide it entirely, because you didn't need to see it anyway, right?"}}, default = "blackoutline", hover = "The color to use for blocked points, where you cannot place things."},
    {name = "NEARTILECOLOR", label = "Nearest Tile Color", options = {{["data"]="green", ["description"]="Green", ["hover"]="The normal green  the game uses."}, {["data"]="blue", ["description"]="Blue", ["hover"]="Blue, helpful if you're red/green colorblind."}, {["data"]="red", ["description"]="Red", ["hover"]="The normal red the game uses."}, {["data"]="white", ["description"]="White", ["hover"]="A bright white, for better visibility."}, {["data"]="black", ["description"]="Black", ["hover"]="Black, to contrast with the brighter colors."}, {["data"]="whiteoutline", ["description"]="Outlined White", ["hover"]="White with a black outline, for the best visibility."}, {["data"]="blackoutline", ["description"]="Outlined Black", ["hover"]="Black with a white outline, for the best visibility."}, {["data"]="hidden", ["description"]="Hidden", ["hover"]="Hide it entirely, because you didn't need to see it anyway, right?"}}, default = "white", hover = "The color to use for the nearest tile outline."},
    {name = "GOODTILECOLOR", label = "Unblocked Tile Color", options = {{["data"]="green", ["description"]="Green", ["hover"]="The normal green  the game uses."}, {["data"]="blue", ["description"]="Blue", ["hover"]="Blue, helpful if you're red/green colorblind."}, {["data"]="red", ["description"]="Red", ["hover"]="The normal red the game uses."}, {["data"]="white", ["description"]="White", ["hover"]="A bright white, for better visibility."}, {["data"]="black", ["description"]="Black", ["hover"]="Black, to contrast with the brighter colors."}, {["data"]="whiteoutline", ["description"]="Outlined White", ["hover"]="White with a black outline, for the best visibility."}, {["data"]="blackoutline", ["description"]="Outlined Black", ["hover"]="Black with a white outline, for the best visibility."}, {["data"]="hidden", ["description"]="Hidden", ["hover"]="Hide it entirely, because you didn't need to see it anyway, right?"}}, default = "whiteoutline", hover = "The color to use for the turf tile grid, where you can place turf."},
    {name = "BADTILECOLOR", label = "Blocked Tile Color", options = {{["data"]="green", ["description"]="Green", ["hover"]="The normal green  the game uses."}, {["data"]="blue", ["description"]="Blue", ["hover"]="Blue, helpful if you're red/green colorblind."}, {["data"]="red", ["description"]="Red", ["hover"]="The normal red the game uses."}, {["data"]="white", ["description"]="White", ["hover"]="A bright white, for better visibility."}, {["data"]="black", ["description"]="Black", ["hover"]="Black, to contrast with the brighter colors."}, {["data"]="whiteoutline", ["description"]="Outlined White", ["hover"]="White with a black outline, for the best visibility."}, {["data"]="blackoutline", ["description"]="Outlined Black", ["hover"]="Black with a white outline, for the best visibility."}, {["data"]="hidden", ["description"]="Hidden", ["hover"]="Hide it entirely, because you didn't need to see it anyway, right?"}}, default = "blackoutline", hover = "The color to use for the turf tile grid, where you can't place turf."},
    {name = "GOODPLACERCOLOR", label = "Unblocked Placer Color", options = {{["data"]="green", ["description"]="Green", ["hover"]="The normal green  the game uses."}, {["data"]="blue", ["description"]="Blue", ["hover"]="Blue, helpful if you're red/green colorblind."}, {["data"]="red", ["description"]="Red", ["hover"]="The normal red the game uses."}, {["data"]="white", ["description"]="White", ["hover"]="A bright white, for better visibility."}, {["data"]="black", ["description"]="Black", ["hover"]="Black, to contrast with the brighter colors."}, {["data"]="hidden", ["description"]="Hidden", ["hover"]="Hide it entirely, because you didn't need to see it anyway, right?"}}, default = "white", hover = "The color to use for an unblocked placer\
(the \"shadow copy\" of the thing you're placing)."},
    {name = "BADPLACERCOLOR", label = "Blocked Placer Color", options = {{["data"]="green", ["description"]="Green", ["hover"]="The normal green  the game uses."}, {["data"]="blue", ["description"]="Blue", ["hover"]="Blue, helpful if you're red/green colorblind."}, {["data"]="red", ["description"]="Red", ["hover"]="The normal red the game uses."}, {["data"]="white", ["description"]="White", ["hover"]="A bright white, for better visibility."}, {["data"]="black", ["description"]="Black", ["hover"]="Black, to contrast with the brighter colors."}, {["data"]="hidden", ["description"]="Hidden", ["hover"]="Hide it entirely, because you didn't need to see it anyway, right?"}}, default = "black", hover = "The color to use for a blocked placer\
(the \"shadow copy\" of the thing you're placing)."},
    {name = "REDUCECHESTSPACING", label = "Tighter Chests", options = yes_no, default = true, hover = "Whether to allow chests to be placed closer together than normal.\
This may not work in DST."},
    {name = "CONTROLLEROFFSET", label = "Controller Offset", options = yes_no, default = false, hover = "With a controller, whether objects get placed\
right at your feet (\"off\") or at an offset (\"on\")."},
}

-- Giữ nguyên tên khóa và giá trị của các mod gốc; chỉ đổi phần chữ hiển thị.
local labels = {
    UI_DISPLAY = "Hiển thị đường đi",
    ICON_STYLE = "Kiểu biểu tượng",
    MAPS_TRIGGER = "Bản đồ kích hoạt",
    DBCLICK_TIME_THRESHOLD = "Khoảng nhấp đúp",
    MOUSEBUTTON_TRAVEL = "Nút chuột tự đi",
    KEY_ADDITION_TRAVEL = "Phím nối đường đi",
    ALLOW_FOGOFWAR = "Đi vào vùng chưa khám phá",
    TWEAK_DETOUR_ENABLE = "Đi vòng chướng ngại vật",
    PATHFINDER = "Thuật toán tìm đường",
    TIMESCALE_TWEAK_MULTI = "Tăng tốc khi đi một mình",
    PATCH_MINIMAP = "Sửa bản đồ nhỏ",

    OBC_INITIAL_VIEW_MODE = "Góc nhìn khi vào game",
    OBC_FUNCTION_KEY_1 = "Phím đổi góc nhìn",
    OBC_FUNCTION_KEY_2 = "Phím ẩn/hiện HUD",
    OBC_FUNCTION_KEY_3 = "Phím ẩn/hiện nhân vật",
    OBC_SWITCH_KEY_1 = "Phím theo dõi thực thể",
    OBC_SWITCH_KEY_2 = "Phím nhìn điểm chọn",
    OBC_RESET_KEY = "Phím đổi mục tiêu camera",
    OBC_FOV_PLUS_KEY = "Phím tăng FOV 1",
    OBC_FOV_MINUS_KEY = "Phím giảm FOV 1",
    OBC_FOV_PLUS_MORE_KEY = "Phím tăng FOV 5",
    OBC_FOV_MINUS_MORE_KEY = "Phím giảm FOV 5",

    persistent_icons = "Giữ biểu tượng công trình, vật phẩm",
    creature_persistent_icons = "Giữ biểu tượng sinh vật, trùm",

    CYCLE_OFFSET_KEY = "Phím đổi vị trí lưới",
    CYCLE_RESOLUTION_KEY = "Phím đổi khoảng cách lưới",
    RESTORE_DEFAULTS_KEY = "Phím khôi phục mặc định",
    TOGGLE_PLACERS_KEY = "Phím ẩn/hiện điểm thả",
    TOGGLE_ENABLED_KEY = "Phím đổi chế độ thả",
    PLACERS_START_VISIBLE = "Hiện điểm thả ban đầu",
    DEFAULT_DROP_RESOLUTION = "Khoảng cách lưới mặc định",
    DEFAULT_DROP_OFFSET = "Vị trí lưới mặc định",
    DEFAULT_MODE = "Chế độ thả vật phẩm",

    CTRL = "Giữ Ctrl để đảo trạng thái",
    KEYBOARDTOGGLEKEY = "Phím mở tùy chọn",
    GEOMETRYTOGGLEKEY = "Phím đổi kiểu lưới",
    SNAPGRIDKEY = "Phím căn lưới vào mục tiêu",
    SHOWMENU = "Hiện menu trong game",
    BUILDGRID = "Hiện lưới xây dựng",
    GEOMETRY = "Kiểu hình học",
    TIMEBUDGET = "Tốc độ làm mới lưới",
    HIDEPLACER = "Ẩn mô hình xem trước",
    HIDECURSOR = "Ẩn hình vật phẩm trên chuột",
    SMARTSPACING = "Tự chỉnh khoảng cách",
    ACTION_TILL = "Lưới xới đất",
    SMALLGRIDSIZE = "Kích thước lưới mịn",
    MEDGRIDSIZE = "Kích thước lưới vừa",
    BIGGRIDSIZE = "Kích thước lưới lớn",
    GOODCOLOR = "Màu vị trí hợp lệ",
    BADCOLOR = "Màu vị trí bị chặn",
    NEARTILECOLOR = "Màu ô gần nhất",
    GOODTILECOLOR = "Màu ô đất hợp lệ",
    BADTILECOLOR = "Màu ô đất bị chặn",
    GOODPLACERCOLOR = "Màu mô hình hợp lệ",
    BADPLACERCOLOR = "Màu mô hình bị chặn",
    REDUCECHESTSPACING = "Đặt rương sát nhau",
    CONTROLLEROFFSET = "Độ lệch tay cầm",
}

local explanations = {
    UI_DISPLAY = "Chọn cách hiển thị điểm đến và đường đi trên bản đồ.",
    ICON_STYLE = "Chọn kiểu biểu tượng của điểm đến.",
    MAPS_TRIGGER = "Chọn bản đồ có thể dùng để bắt đầu tự đi.",
    DBCLICK_TIME_THRESHOLD = "Khoảng thời gian nhận nhấp đúp để dùng thao tác bản đồ gốc.",
    MOUSEBUTTON_TRAVEL = "Nút chuột bắt đầu tìm đường trên bản đồ.",
    KEY_ADDITION_TRAVEL = "Giữ phím này khi chọn điểm mới để nối tiếp đường đi hiện tại.",
    ALLOW_FOGOFWAR = "Cho phép tìm đường qua vùng bản đồ chưa khám phá.",
    TWEAK_DETOUR_ENABLE = "Tìm đường vòng để tránh chướng ngại vật.",
    PATHFINDER = "Chọn thuật toán tìm đường: A* cho quãng xa hoặc thuật toán của game.",
    TIMESCALE_TWEAK_MULTI = "Tăng tốc thời gian khi tự đi trong thế giới một người chơi.",
    PATCH_MINIMAP = "Giữ mức phóng to của bản đồ nhỏ khi đóng bản đồ.",
    OBC_INITIAL_VIEW_MODE = "Góc nhìn được dùng khi vào thế giới.",
    OBC_FUNCTION_KEY_1 = "Đổi giữa góc nhìn mặc định, góc cao và từ trên xuống.",
    OBC_FUNCTION_KEY_2 = "Ẩn hoặc hiện giao diện HUD.",
    OBC_FUNCTION_KEY_3 = "Ẩn hoặc hiện nhân vật của bạn.",
    OBC_SWITCH_KEY_1 = "Đặt camera theo thực thể dưới con trỏ.",
    OBC_SWITCH_KEY_2 = "Đặt camera nhìn vào vị trí dưới con trỏ.",
    OBC_RESET_KEY = "Đổi giữa nhân vật và mục tiêu camera vừa chọn.",
    CYCLE_OFFSET_KEY = "Đổi giữa tâm ô và góc ô khi thả vật phẩm.",
    CYCLE_RESOLUTION_KEY = "Đổi khoảng cách giữa các điểm thả.",
    RESTORE_DEFAULTS_KEY = "Khôi phục vị trí lưới, khoảng cách và chế độ mặc định.",
    TOGGLE_PLACERS_KEY = "Ẩn hoặc hiện các điểm chỉ vị trí thả.",
    TOGGLE_ENABLED_KEY = "Đổi giữa lưới, vòng tròn và chế độ tắt.",
    PLACERS_START_VISIBLE = "Hiện các điểm thả khi cầm vật phẩm.",
    DEFAULT_DROP_RESOLUTION = "Khoảng cách điểm thả khi vào game.",
    DEFAULT_DROP_OFFSET = "Chọn thả ở tâm ô hoặc vị trí lệch nửa ô.",
    DEFAULT_MODE = "Chế độ thả khi vào game.",
    CTRL = "Giữ Ctrl để đảo trạng thái của Geometric Placement.",
    KEYBOARDTOGGLEKEY = "Phím mở bảng tùy chọn khi đang chơi.",
    GEOMETRYTOGGLEKEY = "Chuyển nhanh giữa các kiểu hình học gần đây.",
    SNAPGRIDKEY = "Căn một điểm lưới vào mục tiêu dưới con trỏ.",
    SHOWMENU = "Mở menu tùy chọn trong game thay vì bật/tắt trực tiếp.",
    BUILDGRID = "Hiện các điểm lưới xung quanh vị trí đặt.",
    GEOMETRY = "Chọn hình dạng lưới khi đặt vật phẩm và công trình.",
    TIMEBUDGET = "Thời gian dành cho mỗi lần làm mới lưới; giá trị cao có thể gây lag.",
    HIDEPLACER = "Ẩn bóng xem trước của công trình để nhìn lưới rõ hơn.",
    HIDECURSOR = "Ẩn hình vật phẩm đang cầm để nhìn vị trí đặt rõ hơn.",
    SMARTSPACING = "Tự đổi khoảng cách lưới theo vật thể đang đặt.",
    ACTION_TILL = "Dùng lưới khi xới đất trồng trọt.",
    REDUCECHESTSPACING = "Cho phép đặt các rương gần nhau hơn.",
    CONTROLLEROFFSET = "Dịch vị trí đặt khi dùng tay cầm.",
}

local choice_text = {
    ["Yes"] = "Bật", ["No"] = "Tắt", ["On"] = "Bật", ["Off"] = "Tắt",
    ["Enabled"] = "Bật", ["Disabled"] = "Tắt", ["Disable - 禁用"] = "Tắt",
    ["Default - 默认"] = "Mặc định", ["Aerial - 高空"] = "Góc cao",
    ["Vertical - 俯视"] = "Từ trên xuống", ["Grid"] = "Lưới",
    ["Circle"] = "Vòng tròn", ["Normal"] = "Bình thường", ["Offset"] = "Lệch nửa ô",
    ["New"] = "Mới", ["Classical"] = "Cổ điển", ["None"] = "Không hiện",
    ["Icon Only"] = "Chỉ biểu tượng", ["PathLine Only"] = "Chỉ đường đi",
    ["Icon & PathLine"] = "Biểu tượng và đường đi",
}

for i = 1, #configuration_options do
    local option = configuration_options[i]
    if option.name ~= "" then
        option.label = labels[option.name] or option.label
        option.hover = explanations[option.name] or option.hover
        for j = 1, #(option.options or {}) do
            local choice = option.options[j]
            choice.description = choice_text[choice.description] or choice.description
        end
    end
end
