-- Generated from pham-nhan-remaining-achievement-quest.csv.
-- The six ttk_boss_core_* food achievements were omitted by request.
-- Names and descriptions retain the CSV wording for later translation edits.
return {
    {
        id = "survive_autumn",
        group = "survival",
        tracker = "survival_event",
        params = { ["key"] = "autumn" },
        current = 1,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Qua Mùa Thu", description = "Còn sống khi mùa thu kết thúc và thế giới chuyển mùa.", info = "đã hoàn thành Qua Mùa Thu" } },
    },
    {
        id = "survive_winter",
        group = "survival",
        tracker = "survival_event",
        params = { ["key"] = "winter" },
        current = 1,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Qua Mùa Đông", description = "Còn sống khi mùa đông kết thúc và thế giới chuyển mùa.", info = "đã hoàn thành Qua Mùa Đông" } },
    },
    {
        id = "survive_spring",
        group = "survival",
        tracker = "survival_event",
        params = { ["key"] = "spring" },
        current = 1,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Qua Mùa Xuân", description = "Còn sống khi mùa xuân kết thúc và thế giới chuyển mùa.", info = "đã hoàn thành Qua Mùa Xuân" } },
    },
    {
        id = "survive_summer",
        group = "survival",
        tracker = "survival_event",
        params = { ["key"] = "summer" },
        current = 1,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Qua Mùa Hạ", description = "Còn sống khi mùa hạ kết thúc và thế giới chuyển mùa.", info = "đã hoàn thành Qua Mùa Hạ" } },
    },
    {
        id = "survive_hundred_days",
        group = "survival",
        tracker = "survival_event",
        params = { ["key"] = "hundred_days" },
        current = 100,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Sinh Tồn Trăm Ngày", description = "Còn sống qua một trăm lần kết thúc ngày trong thế giới.", info = "đã hoàn thành Sinh Tồn Trăm Ngày" } },
    },
    {
        id = "survive_revive",
        group = "survival",
        tracker = "survival_event",
        params = { ["key"] = "revive" },
        current = 1,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Trở Về Từ Cõi Chết", description = "Hồi sinh từ dạng hồn ma và trở lại thân thể sống.", info = "đã hoàn thành Trở Về Từ Cõi Chết" } },
    },
    {
        id = "survive_rescue_friend",
        group = "survival",
        tracker = "survival_event",
        params = { ["key"] = "solo_days" },
        current = 30,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Sinh Tồn Ba Mươi Ngày", description = "Còn sống qua ba mươi lần kết thúc ngày; có thể hoàn thành khi chơi một mình.", info = "đã hoàn thành Sinh Tồn Ba Mươi Ngày" } },
    },
    {
        id = "survive_heat",
        group = "survival",
        tracker = "survival_event",
        params = { ["key"] = "heat" },
        current = 1,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Thoát Cơn Nóng", description = "Sống sót sau khi thân nhiệt quá nóng và trở về mức an toàn.", info = "đã hoàn thành Thoát Cơn Nóng" } },
    },
    {
        id = "survive_cold",
        group = "survival",
        tracker = "survival_event",
        params = { ["key"] = "cold" },
        current = 1,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Thoát Cơn Lạnh", description = "Sống sót sau khi thân nhiệt đóng băng và trở về mức an toàn.", info = "đã hoàn thành Thoát Cơn Lạnh" } },
    },
    {
        id = "survive_night",
        group = "survival",
        tracker = "survival_event",
        params = { ["key"] = "night" },
        current = 1,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Đón Bình Minh", description = "Sống từ lúc đêm bắt đầu cho tới bình minh mà không chết.", info = "đã hoàn thành Đón Bình Minh" } },
    },
    {
        id = "food_meatballs",
        group = "food",
        tracker = "eat_prefabs",
        params = { ["prefabs"] = { "meatballs" } },
        current = 10,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Viên Thịt", description = "Hoàn thành thử thách ẩm thực Viên Thịt.", info = "đã hoàn thành Viên Thịt" } },
    },
    {
        id = "food_pierogi",
        group = "food",
        tracker = "eat_prefabs",
        params = { ["prefabs"] = { "perogies" } },
        current = 5,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Bánh Xếp", description = "Hoàn thành thử thách ẩm thực Bánh Xếp.", info = "đã hoàn thành Bánh Xếp" } },
    },
    {
        id = "food_bacon_eggs",
        group = "food",
        tracker = "eat_prefabs",
        params = { ["prefabs"] = { "baconeggs" } },
        current = 5,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Trứng Thịt", description = "Hoàn thành thử thách ẩm thực Trứng Thịt.", info = "đã hoàn thành Trứng Thịt" } },
    },
    {
        id = "food_fishsticks",
        group = "food",
        tracker = "eat_prefabs",
        params = { ["prefabs"] = { "fishsticks" } },
        current = 5,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Que Cá", description = "Hoàn thành thử thách ẩm thực Que Cá.", info = "đã hoàn thành Que Cá" } },
    },
    {
        id = "food_trailmix",
        group = "food",
        tracker = "eat_prefabs",
        params = { ["prefabs"] = { "trailmix" } },
        current = 5,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Hỗn Hợp Rừng", description = "Hoàn thành thử thách ẩm thực Hỗn Hợp Rừng.", info = "đã hoàn thành Hỗn Hợp Rừng" } },
    },
    {
        id = "food_honeyham",
        group = "food",
        tracker = "eat_prefabs",
        params = { ["prefabs"] = { "honeyham" } },
        current = 3,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Giăm Bông Mật", description = "Hoàn thành thử thách ẩm thực Giăm Bông Mật.", info = "đã hoàn thành Giăm Bông Mật" } },
    },
    {
        id = "food_turkey_dinner",
        group = "food",
        tracker = "eat_prefabs",
        params = { ["prefabs"] = { "turkeydinner" } },
        current = 3,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Tiệc Gà Tây", description = "Hoàn thành thử thách ẩm thực Tiệc Gà Tây.", info = "đã hoàn thành Tiệc Gà Tây" } },
    },
    {
        id = "food_dragonpie",
        group = "food",
        tracker = "eat_prefabs",
        params = { ["prefabs"] = { "dragonpie" } },
        current = 3,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Bánh Thanh Long", description = "Hoàn thành thử thách ẩm thực Bánh Thanh Long.", info = "đã hoàn thành Bánh Thanh Long" } },
    },
    {
        id = "food_waffles",
        group = "food",
        tracker = "eat_prefabs",
        params = { ["prefabs"] = { "waffles" } },
        current = 3,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Bánh Waffle", description = "Hoàn thành thử thách ẩm thực Bánh Waffle.", info = "đã hoàn thành Bánh Waffle" } },
    },
    {
        id = "food_jellybeans",
        group = "food",
        tracker = "eat_prefabs",
        params = { ["prefabs"] = { "jellybean" } },
        current = 10,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Kẹo Đậu", description = "Hoàn thành thử thách ẩm thực Kẹo Đậu.", info = "đã hoàn thành Kẹo Đậu" } },
    },
    {
        id = "food_icecream",
        group = "food",
        tracker = "eat_prefabs",
        params = { ["prefabs"] = { "icecream" } },
        current = 5,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Kem Mùa Hạ", description = "Hoàn thành thử thách ẩm thực Kem Mùa Hạ.", info = "đã hoàn thành Kem Mùa Hạ" } },
    },
    {
        id = "food_spicychili",
        group = "food",
        tracker = "eat_prefabs",
        params = { ["prefabs"] = { "hotchili" } },
        current = 5,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Ớt Cay", description = "Hoàn thành thử thách ẩm thực Ớt Cay.", info = "đã hoàn thành Ớt Cay" } },
    },
    {
        id = "food_stuffed_eggplant",
        group = "food",
        tracker = "eat_prefabs",
        params = { ["prefabs"] = { "stuffedeggplant" } },
        current = 5,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Cà Tím Nhồi", description = "Hoàn thành thử thách ẩm thực Cà Tím Nhồi.", info = "đã hoàn thành Cà Tím Nhồi" } },
    },
    {
        id = "food_guacamole",
        group = "food",
        tracker = "eat_prefabs",
        params = { ["prefabs"] = { "guacamole" } },
        current = 5,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Sốt bơ nghiền", description = "Hoàn thành thử thách ẩm thực Sốt bơ nghiền.", info = "đã hoàn thành Sốt bơ nghiền" } },
    },
    {
        id = "food_powcake",
        group = "food",
        tracker = "eat_prefabs",
        params = { ["prefabs"] = { "powcake" } },
        current = 3,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Bánh Mật", description = "Hoàn thành thử thách ẩm thực Bánh Mật.", info = "đã hoàn thành Bánh Mật" } },
    },
    {
        id = "food_cultivation_pill_path",
        group = "food",
        tracker = "eat_prefabs",
        params = { ["prefabs"] = { "xd_danyao_jq", "xd_danyao_dt", "xd_danyao_zj", "xd_danyao_xs", "xd_danyao_hj", "xd_danyao_yz", "xd_danyao_sm", "xd_danyao_rl", "xd_danyao_jy", "xd_danyao_yx", "xd_danyao_ns", "xd_danyao_hs", "xd_danyao_hy", "xd_danyao_hl", "xd_danyao_kx" } },
        current = 15,
        coinget = 2,
        requires_tutien = true,
        strings = { vi = { name = "Đan Đạo Thông Huyền", description = "Hoàn thành thử thách ẩm thực Đan Đạo Thông Huyền.", info = "đã hoàn thành Đan Đạo Thông Huyền" } },
    },
    {
        id = "food_fasting_pill",
        group = "food",
        tracker = "eat_prefabs",
        params = { ["prefabs"] = { "xd_danyao_bg" } },
        current = 1,
        coinget = 2,
        requires_tutien = true,
        strings = { vi = { name = "Tịch Cốc", description = "Hoàn thành thử thách ẩm thực Tịch Cốc.", info = "đã hoàn thành Tịch Cốc" } },
    },
    {
        id = "food_buff_cyfxd",
        group = "food",
        tracker = "eat_prefabs",
        params = { ["prefabs"] = { "xd_dy_cyfxd_1" } },
        current = 1,
        coinget = 2,
        requires_tutien = true,
        strings = { vi = { name = "Xích Dương Phần Huyết Đan", description = "Hoàn thành thử thách ẩm thực Xích Dương Phần Huyết Đan.", info = "đã hoàn thành Xích Dương Phần Huyết Đan" } },
    },
    {
        id = "food_buff_dmhsd",
        group = "food",
        tracker = "eat_prefabs",
        params = { ["prefabs"] = { "xd_dy_dmhsd_1" } },
        current = 1,
        coinget = 2,
        requires_tutien = true,
        strings = { vi = { name = "Địa Mạch Hồi Sinh Đan", description = "Hoàn thành thử thách ẩm thực Địa Mạch Hồi Sinh Đan.", info = "đã hoàn thành Địa Mạch Hồi Sinh Đan" } },
    },
    {
        id = "food_buff_lmsqd",
        group = "food",
        tracker = "eat_prefabs",
        params = { ["prefabs"] = { "xd_dy_lmsqd_1" } },
        current = 1,
        coinget = 2,
        requires_tutien = true,
        strings = { vi = { name = "Lôi Minh Sát Khí Đan", description = "Hoàn thành thử thách ẩm thực Lôi Minh Sát Khí Đan.", info = "đã hoàn thành Lôi Minh Sát Khí Đan" } },
    },
    {
        id = "food_buff_qxdhd",
        group = "food",
        tracker = "eat_prefabs",
        params = { ["prefabs"] = { "xd_dy_qxdhd_1" } },
        current = 1,
        coinget = 2,
        requires_tutien = true,
        strings = { vi = { name = "Thanh Tâm Địch Hồn Đan", description = "Hoàn thành thử thách ẩm thực Thanh Tâm Địch Hồn Đan.", info = "đã hoàn thành Thanh Tâm Địch Hồn Đan" } },
    },
    {
        id = "food_buff_yfsxd",
        group = "food",
        tracker = "eat_prefabs",
        params = { ["prefabs"] = { "xd_dy_yfsxd_1" } },
        current = 1,
        coinget = 2,
        requires_tutien = true,
        strings = { vi = { name = "Ngự Phong Thần Hành Đan", description = "Hoàn thành thử thách ẩm thực Ngự Phong Thần Hành Đan.", info = "đã hoàn thành Ngự Phong Thần Hành Đan" } },
    },
    {
        id = "food_buff_pshsd",
        group = "food",
        tracker = "eat_prefabs",
        params = { ["prefabs"] = { "xd_dy_pshsd_1" } },
        current = 1,
        coinget = 2,
        requires_tutien = true,
        strings = { vi = { name = "Bàn Thạch Hộ Thân Đan", description = "Hoàn thành thử thách ẩm thực Bàn Thạch Hộ Thân Đan.", info = "đã hoàn thành Bàn Thạch Hộ Thân Đan" } },
    },
    {
        id = "food_buff_qjqsd",
        group = "food",
        tracker = "eat_prefabs",
        params = { ["prefabs"] = { "xd_dy_qjqsd_1" } },
        current = 1,
        coinget = 2,
        requires_tutien = true,
        strings = { vi = { name = "Thiên Cơ Xảo Thủ Đan", description = "Hoàn thành thử thách ẩm thực Thiên Cơ Xảo Thủ Đan.", info = "đã hoàn thành Thiên Cơ Xảo Thủ Đan" } },
    },
    {
        id = "food_buff_xynyd",
        group = "food",
        tracker = "eat_prefabs",
        params = { ["prefabs"] = { "xd_dy_xynyd_1" } },
        current = 1,
        coinget = 2,
        requires_tutien = true,
        strings = { vi = { name = "Huyền Dương Noãn Ngọc Đan", description = "Hoàn thành thử thách ẩm thực Huyền Dương Noãn Ngọc Đan.", info = "đã hoàn thành Huyền Dương Noãn Ngọc Đan" } },
    },
    {
        id = "food_buff_hsphd",
        group = "food",
        tracker = "eat_prefabs",
        params = { ["prefabs"] = { "xd_dy_hsphd_1" } },
        current = 1,
        coinget = 2,
        requires_tutien = true,
        strings = { vi = { name = "Hàn Tủy Tịch Hỏa Đan", description = "Hoàn thành thử thách ẩm thực Hàn Tủy Tịch Hỏa Đan.", info = "đã hoàn thành Hàn Tủy Tịch Hỏa Đan" } },
    },
    {
        id = "food_buff_xttyd",
        group = "food",
        tracker = "eat_prefabs",
        params = { ["prefabs"] = { "xd_dy_xttyd_1" } },
        current = 1,
        coinget = 2,
        requires_tutien = true,
        strings = { vi = { name = "Huyết Thao Thiết Nguyên Đan", description = "Hoàn thành thử thách ẩm thực Huyết Thao Thiết Nguyên Đan.", info = "đã hoàn thành Huyết Thao Thiết Nguyên Đan" } },
    },
    {
        id = "food_mandrake_soup",
        group = "food",
        tracker = "eat_prefabs",
        params = { ["prefabs"] = { "mandrakesoup" } },
        current = 1,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Súp Mandrake", description = "Hoàn thành thử thách ẩm thực Súp Mandrake.", info = "đã hoàn thành Súp Mandrake" } },
    },
    {
        id = "food_banana_pop",
        group = "food",
        tracker = "eat_prefabs",
        params = { ["prefabs"] = { "bananapop" } },
        current = 5,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Kem Chuối", description = "Hoàn thành thử thách ẩm thực Kem Chuối.", info = "đã hoàn thành Kem Chuối" } },
    },
    {
        id = "food_butterfly_muffin",
        group = "food",
        tracker = "eat_prefabs",
        params = { ["prefabs"] = { "butterflymuffin" } },
        current = 3,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Muffin Bướm", description = "Hoàn thành thử thách ẩm thực Muffin Bướm.", info = "đã hoàn thành Muffin Bướm" } },
    },
    {
        id = "food_frogglebunwich",
        group = "food",
        tracker = "eat_prefabs",
        params = { ["prefabs"] = { "frogglebunwich" } },
        current = 3,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Bánh Ếch", description = "Hoàn thành thử thách ẩm thực Bánh Ếch.", info = "đã hoàn thành Bánh Ếch" } },
    },
    {
        id = "food_ratatouille",
        group = "food",
        tracker = "eat_prefabs",
        params = { ["prefabs"] = { "ratatouille" } },
        current = 3,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Rau củ hầm", description = "Hoàn thành thử thách ẩm thực Rau củ hầm.", info = "đã hoàn thành Rau củ hầm" } },
    },
    {
        id = "food_fruitmedley",
        group = "food",
        tracker = "eat_prefabs",
        params = { ["prefabs"] = { "fruitmedley" } },
        current = 3,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Trái Cây Trộn", description = "Hoàn thành thử thách ẩm thực Trái Cây Trộn.", info = "đã hoàn thành Trái Cây Trộn" } },
    },
    {
        id = "collection_twigs",
        group = "collection",
        tracker = "collect_prefab",
        params = { ["prefab"] = "twigs" },
        current = 100,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Thu thập Cành cây", description = "Thu thập Cành cây.", info = "đã hoàn thành Thu thập Cành cây" } },
    },
    {
        id = "collection_grass",
        group = "collection",
        tracker = "collect_prefab",
        params = { ["prefab"] = "cutgrass" },
        current = 100,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Cỏ Khô Dự Trữ", description = "Thu thập một trăm Cỏ Cắt.", info = "đã hoàn thành Cỏ Khô Dự Trữ" } },
    },
    {
        id = "collection_flint",
        group = "collection",
        tracker = "collect_prefab",
        params = { ["prefab"] = "flint" },
        current = 100,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Thu thập Đá lửa", description = "Thu thập Đá lửa.", info = "đã hoàn thành Thu thập Đá lửa" } },
    },
    {
        id = "collection_logs",
        group = "collection",
        tracker = "collect_prefab",
        params = { ["prefab"] = "log" },
        current = 100,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Kho Gỗ", description = "Thu thập một trăm Khúc Gỗ.", info = "đã hoàn thành Kho Gỗ" } },
    },
    {
        id = "collection_rocks",
        group = "collection",
        tracker = "collect_prefab",
        params = { ["prefab"] = "rocks" },
        current = 100,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Thu thập Đá", description = "Thu thập Đá.", info = "đã hoàn thành Thu thập Đá" } },
    },
    {
        id = "collection_gold",
        group = "collection",
        tracker = "collect_prefab",
        params = { ["prefab"] = "goldnugget" },
        current = 100,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Kho Vàng", description = "Thu thập một trăm Cục Vàng.", info = "đã hoàn thành Kho Vàng" } },
    },
    {
        id = "collection_nitre",
        group = "collection",
        tracker = "collect_prefab",
        params = { ["prefab"] = "nitre" },
        current = 100,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Thu thập Diêm tiêu", description = "Thu thập Diêm tiêu.", info = "đã hoàn thành Thu thập Diêm tiêu" } },
    },
    {
        id = "collection_charcoal",
        group = "collection",
        tracker = "collect_prefab",
        params = { ["prefab"] = "charcoal" },
        current = 100,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Thu thập Than củi", description = "Thu thập Than củi.", info = "đã hoàn thành Thu thập Than củi" } },
    },
    {
        id = "collection_cutstone",
        group = "collection",
        tracker = "collect_prefab",
        params = { ["prefab"] = "cutstone" },
        current = 100,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Thu thập Đá đẽo", description = "Thu thập Đá đẽo.", info = "đã hoàn thành Thu thập Đá đẽo" } },
    },
    {
        id = "collection_boards",
        group = "collection",
        tracker = "collect_prefab",
        params = { ["prefab"] = "boards" },
        current = 100,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Thu thập Ván gỗ", description = "Thu thập Ván gỗ.", info = "đã hoàn thành Thu thập Ván gỗ" } },
    },
    {
        id = "collection_rope",
        group = "collection",
        tracker = "collect_prefab",
        params = { ["prefab"] = "rope" },
        current = 100,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Thu thập Dây thừng", description = "Thu thập Dây thừng.", info = "đã hoàn thành Thu thập Dây thừng" } },
    },
    {
        id = "collection_silk",
        group = "collection",
        tracker = "collect_prefab",
        params = { ["prefab"] = "silk" },
        current = 100,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Thu thập Tơ nhện", description = "Thu thập Tơ nhện.", info = "đã hoàn thành Thu thập Tơ nhện" } },
    },
    {
        id = "collection_houndstooth",
        group = "collection",
        tracker = "collect_prefab",
        params = { ["prefab"] = "houndstooth" },
        current = 100,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Thu thập Răng chó săn", description = "Thu thập Răng chó săn.", info = "đã hoàn thành Thu thập Răng chó săn" } },
    },
    {
        id = "collection_gears",
        group = "collection",
        tracker = "collect_prefab",
        params = { ["prefab"] = "gears" },
        current = 100,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Thu thập Bánh răng", description = "Thu thập Bánh răng.", info = "đã hoàn thành Thu thập Bánh răng" } },
    },
    {
        id = "collection_gems",
        group = "collection",
        tracker = "collect_prefabs",
        params = { ["prefabs"] = { "redgem", "bluegem", "purplegem", "greengem", "yellowgem", "orangegem" } },
        current = 30,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Đá Quý Đa Sắc", description = "Thu thập ba mươi Đá Quý hiện có.", info = "đã hoàn thành Đá Quý Đa Sắc" } },
    },
    {
        id = "collection_livinglog",
        group = "collection",
        tracker = "collect_prefab",
        params = { ["prefab"] = "livinglog" },
        current = 100,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Thu thập Gỗ sống", description = "Thu thập Gỗ sống.", info = "đã hoàn thành Thu thập Gỗ sống" } },
    },
    {
        id = "collection_thulecite",
        group = "collection",
        tracker = "collect_prefab",
        params = { ["prefab"] = "thulecite" },
        current = 100,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Thu thập Thulecite", description = "Thu thập Thulecite.", info = "đã hoàn thành Thu thập Thulecite" } },
    },
    {
        id = "collection_moonrock",
        group = "collection",
        tracker = "collect_prefab",
        params = { ["prefab"] = "moonrocknugget" },
        current = 100,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Đá Mặt Trăng", description = "Thu thập một trăm Đá Mặt Trăng.", info = "đã hoàn thành Đá Mặt Trăng" } },
    },
    {
        id = "collection_purebrilliance",
        group = "collection",
        tracker = "collect_prefab",
        params = { ["prefab"] = "purebrilliance" },
        current = 100,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Thu thập Tinh hoa thuần khiết", description = "Thu thập Tinh hoa thuần khiết.", info = "đã hoàn thành Thu thập Tinh hoa thuần khiết" } },
    },
    {
        id = "collection_horrorfuel",
        group = "collection",
        tracker = "collect_prefab",
        params = { ["prefab"] = "horrorfuel" },
        current = 100,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Thu thập Nhiên liệu kinh dị", description = "Thu thập Nhiên liệu kinh dị.", info = "đã hoàn thành Thu thập Nhiên liệu kinh dị" } },
    },
    {
        id = "collection_spidergland",
        group = "collection",
        tracker = "collect_prefab",
        params = { ["prefab"] = "spidergland" },
        current = 100,
        coinget = 2,
        requires_tutien = false,
        strings = { vi = { name = "Thu thập Tuyến nhện", description = "Thu thập Tuyến nhện.", info = "đã hoàn thành Thu thập Tuyến nhện" } },
    },
    {
        id = "collection_stinger",
        group = "collection",
        tracker = "collect_prefab",
        params = { ["prefab"] = "stinger" },
        current = 100,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Thu thập Ngòi ong", description = "Thu thập Ngòi ong.", info = "đã hoàn thành Thu thập Ngòi ong" } },
    },
    {
        id = "collection_tentaclespots",
        group = "collection",
        tracker = "collect_prefab",
        params = { ["prefab"] = "tentaclespots" },
        current = 100,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Thu thập Da đốm xúc tu", description = "Thu thập Da đốm xúc tu.", info = "đã hoàn thành Thu thập Da đốm xúc tu" } },
    },
    {
        id = "collection_beardhair",
        group = "collection",
        tracker = "collect_prefab",
        params = { ["prefab"] = "beardhair" },
        current = 100,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Thu thập Râu", description = "Thu thập Râu.", info = "đã hoàn thành Thu thập Râu" } },
    },
    {
        id = "collection_feather_crow",
        group = "collection",
        tracker = "collect_prefab",
        params = { ["prefab"] = "feather_crow" },
        current = 100,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Thu thập Lông quạ", description = "Thu thập Lông quạ.", info = "đã hoàn thành Thu thập Lông quạ" } },
    },
    {
        id = "collection_feather_robin",
        group = "collection",
        tracker = "collect_prefab",
        params = { ["prefab"] = "feather_robin" },
        current = 100,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Thu thập Lông chim đỏ", description = "Thu thập Lông chim đỏ.", info = "đã hoàn thành Thu thập Lông chim đỏ" } },
    },
    {
        id = "collection_feather_robin_winter",
        group = "collection",
        tracker = "collect_prefab",
        params = { ["prefab"] = "feather_robin_winter" },
        current = 100,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Thu thập Lông chim xanh mùa đông", description = "Thu thập Lông chim xanh mùa đông.", info = "đã hoàn thành Thu thập Lông chim xanh mùa đông" } },
    },
    {
        id = "collection_slurtle_shellpieces",
        group = "collection",
        tracker = "collect_prefab",
        params = { ["prefab"] = "slurtle_shellpieces" },
        current = 100,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Thu thập Mảnh vỏ Slurtle", description = "Thu thập Mảnh vỏ Slurtle.", info = "đã hoàn thành Thu thập Mảnh vỏ Slurtle" } },
    },
    {
        id = "collection_nightmarefuel",
        group = "collection",
        tracker = "collect_prefab",
        params = { ["prefab"] = "nightmarefuel" },
        current = 100,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Thu thập Nhiên liệu ác mộng", description = "Thu thập Nhiên liệu ác mộng.", info = "đã hoàn thành Thu thập Nhiên liệu ác mộng" } },
    },
    {
        id = "collection_lingshi1",
        group = "collection",
        tracker = "own_prefab",
        params = { ["prefab"] = "xd_lingshi1" },
        current = 10000,
        coinget = 3,
        requires_tutien = true,
        strings = { vi = { name = "Linh thạch 1", description = "Sở hữu linh thạch cấp 1.", info = "đã hoàn thành Linh thạch 1" } },
    },
    {
        id = "collection_lingshi2",
        group = "collection",
        tracker = "own_prefab",
        params = { ["prefab"] = "xd_lingshi2" },
        current = 10000,
        coinget = 3,
        requires_tutien = true,
        strings = { vi = { name = "Linh thạch 2", description = "Sở hữu linh thạch cấp 2.", info = "đã hoàn thành Linh thạch 2" } },
    },
    {
        id = "collection_lingshi3",
        group = "collection",
        tracker = "own_prefab",
        params = { ["prefab"] = "xd_lingshi3" },
        current = 1000,
        coinget = 3,
        requires_tutien = true,
        strings = { vi = { name = "Linh thạch 3", description = "Sở hữu linh thạch cấp 3.", info = "đã hoàn thành Linh thạch 3" } },
    },
    {
        id = "collection_lingshi4",
        group = "collection",
        tracker = "own_prefab",
        params = { ["prefab"] = "xd_lingshi4" },
        current = 100,
        coinget = 3,
        requires_tutien = true,
        strings = { vi = { name = "Linh thạch 4", description = "Sở hữu linh thạch cấp 4.", info = "đã hoàn thành Linh thạch 4" } },
    },
    {
        id = "labor_chop_trees",
        group = "labor",
        tracker = "work_action",
        params = { ["action"] = "CHOP" },
        current = 50,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Tiều Phu Cần Mẫn", description = "Chặt hạ năm mươi cây bằng rìu.", info = "đã hoàn thành Tiều Phu Cần Mẫn" } },
    },
    {
        id = "labor_mine_rocks",
        group = "labor",
        tracker = "work_action",
        params = { ["action"] = "MINE" },
        current = 50,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Thợ Mỏ Bền Bỉ", description = "Khai thác năm mươi tảng đá bằng cuốc.", info = "đã hoàn thành Thợ Mỏ Bền Bỉ" } },
    },
    {
        id = "labor_dig_stumps",
        group = "labor",
        tracker = "work_action",
        params = { ["action"] = "DIG", ["stump"] = true },
        current = 20,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Dọn Gốc Cây", description = "Đào bỏ hai mươi gốc cây.", info = "đã hoàn thành Dọn Gốc Cây" } },
    },
    {
        id = "labor_hammer_structures",
        group = "labor",
        tracker = "work_action",
        params = { ["action"] = "HAMMER" },
        current = 10,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Thợ Tháo Dỡ", description = "Tháo dỡ mười công trình bằng búa.", info = "đã hoàn thành Thợ Tháo Dỡ" } },
    },
    {
        id = "labor_pick_grass",
        group = "labor",
        tracker = "pick_prefab",
        params = { ["prefab"] = "grass" },
        current = 100,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Cắt Cỏ Ngoài Đồng", description = "Thu hoạch một trăm bụi cỏ.", info = "đã hoàn thành Cắt Cỏ Ngoài Đồng" } },
    },
    {
        id = "labor_pick_twigs",
        group = "labor",
        tracker = "pick_prefab",
        params = { ["prefab"] = "sapling" },
        current = 100,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Nhặt Cành Rừng", description = "Thu hoạch một trăm bụi cành.", info = "đã hoàn thành Nhặt Cành Rừng" } },
    },
    {
        id = "labor_pick_berries",
        group = "labor",
        tracker = "pick_prefab",
        params = { ["prefab"] = "berrybush" },
        current = 50,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Hái Quả Chín", description = "Thu hoạch năm mươi bụi quả.", info = "đã hoàn thành Hái Quả Chín" } },
    },
    {
        id = "labor_fish_pond",
        group = "labor",
        tracker = "fish_caught",
        params = { ["source"] = "pond" },
        current = 20,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Cần Thủ Ao Hồ", description = "Câu được hai mươi con cá ao.", info = "đã hoàn thành Cần Thủ Ao Hồ" } },
    },
    {
        id = "labor_cook_meals",
        group = "labor",
        tracker = "cook_product",
        params = { ["cooker"] = "cookpot" },
        current = 20,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Đầu Bếp Lửa Trại", description = "Nấu hai mươi món trong Nồi Hầm.", info = "đã hoàn thành Đầu Bếp Lửa Trại" } },
    },
    {
        id = "labor_plant_seeds",
        group = "labor",
        tracker = "plant_seed",
        params = { ["prefab"] = "seeds" },
        current = 50,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Người Gieo Hạt", description = "Gieo năm mươi hạt giống trên luống.", info = "đã hoàn thành Người Gieo Hạt" } },
    },
    {
        id = "labor_harvest_plants",
        group = "labor",
        tracker = "harvest_crop",
        params = { ["source"] = "farm" },
        current = 50,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Mùa Vụ Sung Túc", description = "Thu hoạch năm mươi cây trồng.", info = "đã hoàn thành Mùa Vụ Sung Túc" } },
    },
    {
        id = "craft_alchemy_furnace",
        group = "crafting",
        tracker = "crafting_event",
        params = { ["prefab"] = "xd_liandanlu" },
        current = 1,
        coinget = 3,
        requires_tutien = true,
        strings = { vi = { name = "Chế tạo Lò luyện đan", description = "Chế tạo Lò luyện đan.", info = "đã hoàn thành Chế tạo Lò luyện đan" } },
    },
    {
        id = "crafting_science_machine",
        group = "crafting",
        tracker = "craft_prefab",
        params = { ["prefab"] = "researchlab" },
        current = 1,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Máy Khoa Học", description = "Chế tạo một Máy Khoa Học.", info = "đã hoàn thành Máy Khoa Học" } },
    },
    {
        id = "crafting_alchemy_engine",
        group = "crafting",
        tracker = "craft_prefab",
        params = { ["prefab"] = "researchlab2" },
        current = 1,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Máy Luyện Kim", description = "Chế tạo một Máy Luyện Kim.", info = "đã hoàn thành Máy Luyện Kim" } },
    },
    {
        id = "crafting_prestihatitator",
        group = "crafting",
        tracker = "craft_prefab",
        params = { ["prefab"] = "researchlab4" },
        current = 1,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Mũ Pháp Sư", description = "Chế tạo một Mũ Pháp Sư.", info = "đã hoàn thành Mũ Pháp Sư" } },
    },
    {
        id = "crafting_shadow_manipulator",
        group = "crafting",
        tracker = "craft_prefab",
        params = { ["prefab"] = "researchlab3" },
        current = 1,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Máy Thao Túng Bóng Tối", description = "Chế tạo Máy Thao Túng Bóng Tối.", info = "đã hoàn thành Máy Thao Túng Bóng Tối" } },
    },
    {
        id = "crafting_cartographers_desk",
        group = "crafting",
        tracker = "craft_prefab",
        params = { ["prefab"] = "cartographydesk" },
        current = 1,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Bàn Bản Đồ", description = "Chế tạo một Bàn Bản Đồ.", info = "đã hoàn thành Bàn Bản Đồ" } },
    },
    {
        id = "crafting_birdcage",
        group = "crafting",
        tracker = "crafting_event",
        params = { ["prefab"] = "birdcage" },
        current = 1,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Chế tạo Lồng chim", description = "Chế tạo Lồng chim.", info = "đã hoàn thành Chế tạo Lồng chim" } },
    },
    {
        id = "crafting_icebox",
        group = "crafting",
        tracker = "crafting_event",
        params = { ["prefab"] = "icebox" },
        current = 1,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Chế tạo Tủ lạnh", description = "Chế tạo Tủ lạnh.", info = "đã hoàn thành Chế tạo Tủ lạnh" } },
    },
    {
        id = "crafting_lightning_rod",
        group = "crafting",
        tracker = "craft_prefab",
        params = { ["prefab"] = "lightningrod" },
        current = 1,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Cột Thu Lôi", description = "Chế tạo một Cột Thu Lôi.", info = "đã hoàn thành Cột Thu Lôi" } },
    },
    {
        id = "crafting_thermal_measurer",
        group = "crafting",
        tracker = "craft_prefab",
        params = { ["prefab"] = "winterometer" },
        current = 1,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Nhiệt Kế", description = "Chế tạo một Nhiệt Kế.", info = "đã hoàn thành Nhiệt Kế" } },
    },
    {
        id = "crafting_sewing_kit",
        group = "crafting",
        tracker = "crafting_event",
        params = { ["prefab"] = "sewing_kit" },
        current = 1,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Chế tạo Bộ kim chỉ", description = "Chế tạo Bộ kim chỉ.", info = "đã hoàn thành Chế tạo Bộ kim chỉ" } },
    },
    {
        id = "crafting_backpack",
        group = "crafting",
        tracker = "crafting_event",
        params = { ["prefab"] = "backpack" },
        current = 1,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Chế tạo Ba lô", description = "Chế tạo Ba lô.", info = "đã hoàn thành Chế tạo Ba lô" } },
    },
    {
        id = "crafting_football_hat",
        group = "crafting",
        tracker = "craft_prefab",
        params = { ["prefab"] = "footballhat" },
        current = 1,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Mũ Bóng Bầu Dục", description = "Chế tạo một Mũ Bóng Bầu Dục.", info = "đã hoàn thành Mũ Bóng Bầu Dục" } },
    },
    {
        id = "crafting_ham_bat",
        group = "crafting",
        tracker = "craft_prefab",
        params = { ["prefab"] = "hambat" },
        current = 1,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Gậy Giăm Bông", description = "Chế tạo một Gậy Giăm Bông.", info = "đã hoàn thành Gậy Giăm Bông" } },
    },
    {
        id = "crafting_tent",
        group = "crafting",
        tracker = "crafting_event",
        params = { ["prefab"] = "tent" },
        current = 1,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Chế tạo Lều", description = "Chế tạo Lều.", info = "đã hoàn thành Chế tạo Lều" } },
    },
    {
        id = "crafting_endothermic_fire",
        group = "crafting",
        tracker = "craft_prefab",
        params = { ["prefab"] = "coldfire" },
        current = 1,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Lửa Lạnh", description = "Chế tạo một Lửa Lạnh.", info = "đã hoàn thành Lửa Lạnh" } },
    },
    {
        id = "crafting_firepit",
        group = "crafting",
        tracker = "crafting_event",
        params = { ["prefab"] = "firepit" },
        current = 1,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Chế tạo Hố lửa", description = "Chế tạo Hố lửa.", info = "đã hoàn thành Chế tạo Hố lửa" } },
    },
    {
        id = "crafting_cookpot",
        group = "crafting",
        tracker = "crafting_event",
        params = { ["prefab"] = "cookpot" },
        current = 1,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Chế tạo Nồi hầm", description = "Chế tạo Nồi hầm.", info = "đã hoàn thành Chế tạo Nồi hầm" } },
    },
    {
        id = "crafting_bee_box",
        group = "crafting",
        tracker = "craft_prefab",
        params = { ["prefab"] = "beebox" },
        current = 1,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Thùng Ong", description = "Chế tạo một Thùng Ong.", info = "đã hoàn thành Thùng Ong" } },
    },
    {
        id = "crafting_salt_box",
        group = "crafting",
        tracker = "craft_prefab",
        params = { ["prefab"] = "saltbox" },
        current = 1,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Hộp Muối", description = "Chế tạo một Hộp Muối.", info = "đã hoàn thành Hộp Muối" } },
    },
    {
        id = "farming_till_soil",
        group = "farming",
        tracker = "farm_action",
        params = { ["action"] = "TILL" },
        current = 20,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Xới Luống", description = "Xới hai mươi luống đất nông nghiệp.", info = "đã hoàn thành Xới Luống" } },
    },
    {
        id = "farming_water_plants",
        group = "farming",
        tracker = "farm_action",
        params = { ["action"] = "WATER" },
        current = 20,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Tưới Nước", description = "Tưới hai mươi cây trồng.", info = "đã hoàn thành Tưới Nước" } },
    },
    {
        id = "farming_fertilize_plants",
        group = "farming",
        tracker = "farm_action",
        params = { ["action"] = "FERTILIZE" },
        current = 20,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Bón Phân", description = "Bón phân cho hai mươi cây trồng.", info = "đã hoàn thành Bón Phân" } },
    },
    {
        id = "farming_plant_carrot",
        group = "farming",
        tracker = "plant_seed",
        params = { ["crop"] = "carrot", ["prefab"] = "carrot_seeds" },
        current = 20,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Gieo Cà Rốt", description = "Gieo hạt Cà Rốt trên luống.", info = "đã hoàn thành Gieo Cà Rốt" } },
    },
    {
        id = "farming_plant_pumpkin",
        group = "farming",
        tracker = "plant_seed",
        params = { ["crop"] = "pumpkin", ["prefab"] = "pumpkin_seeds" },
        current = 20,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Gieo Bí Ngô", description = "Gieo hạt Bí Ngô trên luống.", info = "đã hoàn thành Gieo Bí Ngô" } },
    },
    {
        id = "farming_plant_eggplant",
        group = "farming",
        tracker = "plant_seed",
        params = { ["crop"] = "eggplant", ["prefab"] = "eggplant_seeds" },
        current = 20,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Gieo Cà Tím", description = "Gieo hạt Cà Tím trên luống.", info = "đã hoàn thành Gieo Cà Tím" } },
    },
    {
        id = "farming_plant_dragonfruit",
        group = "farming",
        tracker = "plant_seed",
        params = { ["crop"] = "dragonfruit", ["prefab"] = "dragonfruit_seeds" },
        current = 20,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Gieo Thanh Long", description = "Gieo hạt Thanh Long trên luống.", info = "đã hoàn thành Gieo Thanh Long" } },
    },
    {
        id = "farming_plant_asparagus",
        group = "farming",
        tracker = "plant_seed",
        params = { ["crop"] = "asparagus", ["prefab"] = "asparagus_seeds" },
        current = 20,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Gieo Măng Tây", description = "Gieo hạt Măng Tây trên luống.", info = "đã hoàn thành Gieo Măng Tây" } },
    },
    {
        id = "farming_plant_tomato",
        group = "farming",
        tracker = "plant_seed",
        params = { ["crop"] = "tomato", ["prefab"] = "tomato_seeds" },
        current = 20,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Gieo Cà Chua", description = "Gieo hạt Cà Chua trên luống.", info = "đã hoàn thành Gieo Cà Chua" } },
    },
    {
        id = "farming_plant_potato",
        group = "farming",
        tracker = "plant_seed",
        params = { ["crop"] = "potato", ["prefab"] = "potato_seeds" },
        current = 20,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Gieo Khoai Tây", description = "Gieo hạt Khoai Tây trên luống.", info = "đã hoàn thành Gieo Khoai Tây" } },
    },
    {
        id = "farming_plant_garlic",
        group = "farming",
        tracker = "plant_seed",
        params = { ["crop"] = "garlic", ["prefab"] = "garlic_seeds" },
        current = 20,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Gieo Tỏi", description = "Gieo hạt Tỏi trên luống.", info = "đã hoàn thành Gieo Tỏi" } },
    },
    {
        id = "farming_plant_onion",
        group = "farming",
        tracker = "plant_seed",
        params = { ["crop"] = "onion", ["prefab"] = "onion_seeds" },
        current = 20,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Gieo Hành", description = "Gieo hạt Hành trên luống.", info = "đã hoàn thành Gieo Hành" } },
    },
    {
        id = "farming_plant_pepper",
        group = "farming",
        tracker = "plant_seed",
        params = { ["crop"] = "pepper", ["prefab"] = "pepper_seeds" },
        current = 20,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Gieo Ớt", description = "Gieo hạt Ớt trên luống.", info = "đã hoàn thành Gieo Ớt" } },
    },
    {
        id = "farming_plant_pomegranate",
        group = "farming",
        tracker = "plant_seed",
        params = { ["crop"] = "pomegranate", ["prefab"] = "pomegranate_seeds" },
        current = 20,
        coinget = 3,
        requires_tutien = false,
        strings = { vi = { name = "Gieo Lựu", description = "Gieo hạt Lựu trên luống.", info = "đã hoàn thành Gieo Lựu" } },
    },
    {
        id = "farming_harvest_crops",
        group = "farming",
        tracker = "harvest_crop",
        params = { ["action"] = "HARVEST" },
        current = 50,
        coinget = 5,
        requires_tutien = false,
        strings = { vi = { name = "Thu Hoạch Mùa Vụ", description = "Thu hoạch năm mươi cây trồng.", info = "đã hoàn thành Thu Hoạch Mùa Vụ" } },
    },
    {
        id = "combat_spider",
        group = "combat",
        tracker = "combat_event",
        params = { ["prefab"] = "spider" },
        current = 1,
        coinget = 5,
        requires_tutien = false,
        strings = { vi = { name = "Hạ Spider", description = "Đánh bại Spider.", info = "đã hoàn thành Hạ Spider" } },
    },
    {
        id = "combat_hound",
        group = "combat",
        tracker = "combat_event",
        params = { ["prefab"] = "hound" },
        current = 1,
        coinget = 5,
        requires_tutien = false,
        strings = { vi = { name = "Hạ Hound", description = "Đánh bại Hound.", info = "đã hoàn thành Hạ Hound" } },
    },
    {
        id = "combat_pigman",
        group = "combat",
        tracker = "combat_event",
        params = { ["prefab"] = "pigman" },
        current = 1,
        coinget = 5,
        requires_tutien = false,
        strings = { vi = { name = "Hạ Pigman", description = "Đánh bại Pigman.", info = "đã hoàn thành Hạ Pigman" } },
    },
    {
        id = "combat_mactusk",
        group = "combat",
        tracker = "combat_event",
        params = { ["prefab"] = "walrus" },
        current = 2,
        coinget = 5,
        requires_tutien = false,
        strings = { vi = { name = "Hai Lần Hạ MacTusk", description = "Đánh bại MacTusk hai lần.", info = "đã hoàn thành Hai Lần Hạ MacTusk" } },
    },
    {
        id = "combat_knight",
        group = "combat",
        tracker = "combat_event",
        params = { ["prefab"] = "knight" },
        current = 1,
        coinget = 5,
        requires_tutien = false,
        strings = { vi = { name = "Hạ Knight", description = "Đánh bại Knight.", info = "đã hoàn thành Hạ Knight" } },
    },
    {
        id = "combat_bishop",
        group = "combat",
        tracker = "combat_event",
        params = { ["prefab"] = "bishop" },
        current = 1,
        coinget = 5,
        requires_tutien = false,
        strings = { vi = { name = "Hạ Bishop", description = "Đánh bại Bishop.", info = "đã hoàn thành Hạ Bishop" } },
    },
    {
        id = "combat_rook",
        group = "combat",
        tracker = "combat_event",
        params = { ["prefab"] = "rook" },
        current = 1,
        coinget = 5,
        requires_tutien = false,
        strings = { vi = { name = "Hạ Rook", description = "Đánh bại Rook.", info = "đã hoàn thành Hạ Rook" } },
    },
    {
        id = "combat_depths_worm",
        group = "combat",
        tracker = "combat_event",
        params = { ["prefab"] = "worm" },
        current = 1,
        coinget = 5,
        requires_tutien = false,
        strings = { vi = { name = "Hạ Depths Worm", description = "Đánh bại Depths Worm.", info = "đã hoàn thành Hạ Depths Worm" } },
    },
    {
        id = "combat_slurtle",
        group = "combat",
        tracker = "combat_event",
        params = { ["prefab"] = "slurtle" },
        current = 1,
        coinget = 5,
        requires_tutien = false,
        strings = { vi = { name = "Hạ Slurtle", description = "Đánh bại Slurtle.", info = "đã hoàn thành Hạ Slurtle" } },
    },
    {
        id = "combat_tentacle",
        group = "combat",
        tracker = "combat_event",
        params = { ["prefab"] = "tentacle" },
        current = 1,
        coinget = 5,
        requires_tutien = false,
        strings = { vi = { name = "Hạ Tentacle", description = "Đánh bại Tentacle.", info = "đã hoàn thành Hạ Tentacle" } },
    },
    {
        id = "combat_shadow_creature",
        group = "combat",
        tracker = "combat_event",
        params = { ["prefabs"] = { "crawlinghorror", "terrorbeak" } },
        current = 1,
        coinget = 5,
        requires_tutien = false,
        strings = { vi = { name = "Hạ Shadow Creature", description = "Đánh bại Shadow Creature.", info = "đã hoàn thành Hạ Shadow Creature" } },
    },
    {
        id = "combat_clockwork",
        group = "combat",
        tracker = "combat_event",
        params = { ["prefabs"] = { "knight", "bishop", "rook", "knight_nightmare", "bishop_nightmare", "rook_nightmare" } },
        current = 1,
        coinget = 5,
        requires_tutien = false,
        strings = { vi = { name = "Hạ Clockwork", description = "Đánh bại Clockwork.", info = "đã hoàn thành Hạ Clockwork" } },
    },
    {
        id = "combat_treeguard",
        group = "combat",
        tracker = "combat_event",
        params = { ["prefabs"] = { "leif", "leif_sparse" } },
        current = 1,
        coinget = 5,
        requires_tutien = false,
        strings = { vi = { name = "Hạ Treeguard", description = "Đánh bại Treeguard.", info = "đã hoàn thành Hạ Treeguard" } },
    },
    {
        id = "combat_walrus",
        group = "combat",
        tracker = "combat_event",
        params = { ["prefab"] = "walrus" },
        current = 1,
        coinget = 5,
        requires_tutien = false,
        strings = { vi = { name = "Hạ Walrus", description = "Đánh bại Walrus.", info = "đã hoàn thành Hạ Walrus" } },
    },
    {
        id = "boss_deerclops",
        group = "boss",
        tracker = "kill_prefab",
        params = { ["prefab"] = "deerclops" },
        current = 1,
        coinget = 5,
        requires_tutien = false,
        strings = { vi = { name = "Hạ Deerclops", description = "Đánh bại Deerclops.", info = "đã hoàn thành Hạ Deerclops" } },
    },
    {
        id = "boss_bearger",
        group = "boss",
        tracker = "kill_prefab",
        params = { ["prefab"] = "bearger" },
        current = 1,
        coinget = 5,
        requires_tutien = false,
        strings = { vi = { name = "Hạ Bearger", description = "Đánh bại Bearger.", info = "đã hoàn thành Hạ Bearger" } },
    },
    {
        id = "boss_moose",
        group = "boss",
        tracker = "kill_prefab",
        params = { ["prefab"] = "moose" },
        current = 1,
        coinget = 5,
        requires_tutien = false,
        strings = { vi = { name = "Hạ Moose/Goose", description = "Đánh bại Moose/Goose.", info = "đã hoàn thành Hạ Moose/Goose" } },
    },
    {
        id = "boss_dragonfly",
        group = "boss",
        tracker = "kill_prefab",
        params = { ["prefab"] = "dragonfly" },
        current = 1,
        coinget = 5,
        requires_tutien = false,
        strings = { vi = { name = "Hạ Dragonfly", description = "Đánh bại Dragonfly.", info = "đã hoàn thành Hạ Dragonfly" } },
    },
    {
        id = "boss_beequeen",
        group = "boss",
        tracker = "kill_prefab",
        params = { ["prefab"] = "beequeen" },
        current = 1,
        coinget = 5,
        requires_tutien = false,
        strings = { vi = { name = "Hạ Bee Queen", description = "Đánh bại Bee Queen.", info = "đã hoàn thành Hạ Bee Queen" } },
    },
    {
        id = "boss_klaus",
        group = "boss",
        tracker = "kill_prefab",
        params = { ["prefab"] = "klaus" },
        current = 1,
        coinget = 5,
        requires_tutien = false,
        strings = { vi = { name = "Hạ Klaus", description = "Đánh bại Klaus.", info = "đã hoàn thành Hạ Klaus" } },
    },
    {
        id = "boss_antlion",
        group = "boss",
        tracker = "kill_prefab",
        params = { ["prefab"] = "antlion" },
        current = 1,
        coinget = 5,
        requires_tutien = false,
        strings = { vi = { name = "Hạ Antlion", description = "Đánh bại Antlion.", info = "đã hoàn thành Hạ Antlion" } },
    },
    {
        id = "boss_toadstool",
        group = "boss",
        tracker = "kill_prefab",
        params = { ["prefab"] = "toadstool" },
        current = 1,
        coinget = 5,
        requires_tutien = false,
        strings = { vi = { name = "Hạ Toadstool", description = "Đánh bại Toadstool.", info = "đã hoàn thành Hạ Toadstool" } },
    },
    {
        id = "boss_toadstool_dark",
        group = "boss",
        tracker = "kill_prefab",
        params = { ["prefab"] = "toadstool_dark" },
        current = 1,
        coinget = 5,
        requires_tutien = false,
        strings = { vi = { name = "Hạ Toadstool Dark", description = "Đánh bại Toadstool Dark.", info = "đã hoàn thành Hạ Toadstool Dark" } },
    },
    {
        id = "boss_fuelweaver",
        group = "boss",
        tracker = "kill_prefab",
        params = { ["prefab"] = "stalker_atrium" },
        current = 2,
        coinget = 5,
        requires_tutien = false,
        strings = { vi = { name = "Hai Lần Hạ Fuelweaver", description = "Đánh bại Ancient Fuelweaver hai lần.", info = "đã hoàn thành Hai Lần Hạ Fuelweaver" } },
    },
    {
        id = "boss_stalker",
        group = "boss",
        tracker = "kill_prefab",
        params = { ["prefab"] = "stalker" },
        current = 1,
        coinget = 5,
        requires_tutien = false,
        strings = { vi = { name = "Hạ Stalker", description = "Đánh bại Stalker.", info = "đã hoàn thành Hạ Stalker" } },
    },
    {
        id = "boss_stalker_atrium",
        group = "boss",
        tracker = "kill_prefab",
        params = { ["prefab"] = "stalker_atrium" },
        current = 1,
        coinget = 5,
        requires_tutien = false,
        strings = { vi = { name = "Hạ Stalker Atrium", description = "Đánh bại Stalker Atrium.", info = "đã hoàn thành Hạ Stalker Atrium" } },
    },
    {
        id = "boss_crabking",
        group = "boss",
        tracker = "kill_prefab",
        params = { ["prefab"] = "crabking" },
        current = 1,
        coinget = 5,
        requires_tutien = false,
        strings = { vi = { name = "Hạ Crab King", description = "Đánh bại Crab King.", info = "đã hoàn thành Hạ Crab King" } },
    },
    {
        id = "boss_malbat",
        group = "boss",
        tracker = "kill_prefab",
        params = { ["prefab"] = "malbatross" },
        current = 1,
        coinget = 5,
        requires_tutien = false,
        strings = { vi = { name = "Hạ Malbat", description = "Đánh bại Malbat.", info = "đã hoàn thành Hạ Malbat" } },
    },
    {
        id = "boss_minotaur",
        group = "boss",
        tracker = "kill_prefab",
        params = { ["prefab"] = "minotaur" },
        current = 1,
        coinget = 5,
        requires_tutien = false,
        strings = { vi = { name = "Hạ Minotaur", description = "Đánh bại Minotaur.", info = "đã hoàn thành Hạ Minotaur" } },
    },
    {
        id = "boss_spiderqueen",
        group = "boss",
        tracker = "kill_prefab",
        params = { ["prefab"] = "spiderqueen" },
        current = 1,
        coinget = 5,
        requires_tutien = false,
        strings = { vi = { name = "Hạ Spider Queen", description = "Đánh bại Spider Queen.", info = "đã hoàn thành Hạ Spider Queen" } },
    },
    {
        id = "boss_guardian",
        group = "boss",
        tracker = "kill_prefab",
        params = { ["prefab"] = "alterguardian_phase3" },
        current = 1,
        coinget = 5,
        requires_tutien = false,
        strings = { vi = { name = "Hạ Guardian", description = "Đánh bại Guardian.", info = "đã hoàn thành Hạ Guardian" } },
    },
    {
        id = "boss_eyeofterror",
        group = "boss",
        tracker = "kill_prefab",
        params = { ["prefab"] = "eyeofterror" },
        current = 1,
        coinget = 5,
        requires_tutien = false,
        strings = { vi = { name = "Hạ Eye of Terror", description = "Đánh bại Eye of Terror.", info = "đã hoàn thành Hạ Eye of Terror" } },
    },
    {
        id = "boss_twinofterror1",
        group = "boss",
        tracker = "kill_prefab",
        params = { ["prefab"] = "twinofterror1" },
        current = 1,
        coinget = 5,
        requires_tutien = false,
        strings = { vi = { name = "Hạ Twin of Terror 1", description = "Đánh bại Twin of Terror 1.", info = "đã hoàn thành Hạ Twin of Terror 1" } },
    },
    {
        id = "boss_twinofterror2",
        group = "boss",
        tracker = "kill_prefab",
        params = { ["prefab"] = "twinofterror2" },
        current = 1,
        coinget = 5,
        requires_tutien = false,
        strings = { vi = { name = "Hạ Twin of Terror 2", description = "Đánh bại Twin of Terror 2.", info = "đã hoàn thành Hạ Twin of Terror 2" } },
    },
    {
        id = "boss_ttk_boss_baihu",
        group = "boss",
        tracker = "kill_prefab",
        params = { ["prefab"] = "xd_baihu" },
        current = 1,
        coinget = 5,
        requires_tutien = true,
        strings = { vi = { name = "Bạch Hổ", description = "Đánh bại Bạch Hổ của Phàm Nhân.", info = "đã hoàn thành Bạch Hổ" } },
    },
    {
        id = "boss_ttk_boss_jfsn",
        group = "boss",
        tracker = "kill_prefab",
        params = { ["prefab"] = "xd_jfsn" },
        current = 1,
        coinget = 5,
        requires_tutien = true,
        strings = { vi = { name = "Kim Phượng", description = "Đánh bại Kim Phượng của Phàm Nhân.", info = "đã hoàn thành Kim Phượng" } },
    },
    {
        id = "boss_ttk_boss_qlch",
        group = "boss",
        tracker = "kill_prefab",
        params = { ["prefab"] = "xd_qlch" },
        current = 1,
        coinget = 5,
        requires_tutien = true,
        strings = { vi = { name = "Kỳ Lân", description = "Đánh bại Kỳ Lân của Phàm Nhân.", info = "đã hoàn thành Kỳ Lân" } },
    },
    {
        id = "boss_ttk_boss_spiderqueen",
        group = "boss",
        tracker = "kill_prefab",
        params = { ["prefab"] = "xd_spiderqueen" },
        current = 1,
        coinget = 5,
        requires_tutien = true,
        strings = { vi = { name = "Nữ Hoàng Ma Thù", description = "Đánh bại Nữ Hoàng Ma Thù.", info = "đã hoàn thành Nữ Hoàng Ma Thù" } },
    },
    {
        id = "boss_ttk_stalke_fuben",
        group = "boss",
        tracker = "kill_prefab",
        params = { ["prefab"] = "xd_stalke_fuben" },
        current = 1,
        coinget = 5,
        requires_tutien = true,
        strings = { vi = { name = "Hạ Thượng Cổ Hắc Ám", description = "Đánh bại Thượng Cổ Hắc Ám.", info = "đã hoàn thành Hạ Thượng Cổ Hắc Ám" } },
    },
    {
        id = "boss_ttk_boss_deerclops_ziyun",
        group = "boss",
        tracker = "kill_prefab",
        params = { ["prefab"] = "xd_deerclops_ziyun" },
        current = 1,
        coinget = 5,
        requires_tutien = true,
        strings = { vi = { name = "Hạ Hồn Phách Tinh Thể Hươu Một Mắt", description = "Đánh bại Hồn Phách Tinh Thể Hươu Một Mắt.", info = "đã hoàn thành Hạ Hồn Phách Tinh Thể Hươu Một Mắt" } },
    },
    {
        id = "boss_ttk_ziyunboss",
        group = "boss",
        tracker = "kill_prefab",
        params = { ["prefab"] = "xd_ziyunboss" },
        current = 1,
        coinget = 5,
        requires_tutien = true,
        strings = { vi = { name = "Hạ Tử Vân Ma Quân", description = "Đánh bại Tử Vân Ma Quân.", info = "đã hoàn thành Hạ Tử Vân Ma Quân" } },
    },
    {
        id = "boss_ttk_boss_ziyunwarg",
        group = "boss",
        tracker = "kill_prefab",
        params = { ["prefab"] = "xd_ziyunwarg" },
        current = 1,
        coinget = 5,
        requires_tutien = true,
        strings = { vi = { name = "Ziyunwarg", description = "Đánh bại Ziyunwarg.", info = "đã đánh bại Ziyunwarg" } },
    },
    {
        id = "boss_ttk_boss_jcbird",
        group = "boss",
        tracker = "kill_prefab",
        params = { ["prefab"] = "xd_jcbird" },
        current = 1,
        coinget = 5,
        requires_tutien = true,
        strings = { vi = { name = "Jcbird", description = "Đánh bại Jcbird.", info = "đã đánh bại Jcbird" } },
    },
    {
        id = "boss_ttk_boss_ziyunshadow",
        group = "boss",
        tracker = "kill_prefab",
        params = { ["prefab"] = "xd_deerclops_ziyun" },
        current = 2,
        coinget = 5,
        requires_tutien = true,
        strings = { vi = { name = "Hai Lần Hạ Hồn Phách Hươu", description = "Đánh bại Hồn Phách Tinh Thể Hươu Một Mắt hai lần.", info = "đã hoàn thành Hai Lần Hạ Hồn Phách Hươu" } },
    },
    {
        id = "boss_ttk_boss_gongdeshadow",
        group = "boss",
        tracker = "kill_prefab",
        params = { ["prefab"] = "xd_qxdx" },
        current = 1,
        coinget = 5,
        requires_tutien = true,
        strings = { vi = { name = "Thanh Tụ Đan Tiên", description = "Đánh bại Thanh Tụ Đan Tiên.", info = "đã hoàn thành Thanh Tụ Đan Tiên" } },
    },
    {
        id = "level_10",
        group = "level_rank",
        tracker = "level_reached",
        params = { ["level"] = 10 },
        current = 10,
        coinget = 10,
        requires_tutien = false,
        strings = { vi = { name = "Cấp độ 10", description = "Đạt cấp độ 10 trong mod Achivement.", info = "đã hoàn thành Cấp độ 10" } },
    },
    {
        id = "level_20",
        group = "level_rank",
        tracker = "level_reached",
        params = { ["level"] = 20 },
        current = 20,
        coinget = 10,
        requires_tutien = false,
        strings = { vi = { name = "Cấp độ 20", description = "Đạt cấp độ 20 trong mod Achivement.", info = "đã hoàn thành Cấp độ 20" } },
    },
    {
        id = "level_30",
        group = "level_rank",
        tracker = "level_reached",
        params = { ["level"] = 30 },
        current = 30,
        coinget = 10,
        requires_tutien = false,
        strings = { vi = { name = "Cấp độ 30", description = "Đạt cấp độ 30 trong mod Achivement.", info = "đã hoàn thành Cấp độ 30" } },
    },
    {
        id = "level_50",
        group = "level_rank",
        tracker = "level_reached",
        params = { ["level"] = 50 },
        current = 50,
        coinget = 10,
        requires_tutien = false,
        strings = { vi = { name = "Cấp độ 50", description = "Đạt cấp độ 50 trong mod Achivement.", info = "đã hoàn thành Cấp độ 50" } },
    },
    {
        id = "level_100",
        group = "level_rank",
        tracker = "level_reached",
        params = { ["level"] = 100 },
        current = 100,
        coinget = 10,
        requires_tutien = false,
        strings = { vi = { name = "Cấp độ 100", description = "Đạt cấp độ 100 trong mod Achivement.", info = "đã hoàn thành Cấp độ 100" } },
    },
    {
        id = "season_first_mission",
        group = "seasonal",
        tracker = "season_mission_completed",
        params = { ["milestone"] = 1 },
        current = 1,
        coinget = 8,
        requires_tutien = false,
        strings = { vi = { name = "Nhiệm Vụ Đầu Tiên", description = "Hoàn thành nhiệm vụ mùa đầu tiên.", info = "đã hoàn thành Nhiệm Vụ Đầu Tiên" } },
    },
    {
        id = "season_mission_five",
        group = "seasonal",
        tracker = "season_mission_completed",
        params = { ["milestone"] = 5 },
        current = 5,
        coinget = 8,
        requires_tutien = false,
        strings = { vi = { name = "Năm Nhiệm Vụ Mùa", description = "Hoàn thành năm nhiệm vụ mùa.", info = "đã hoàn thành Năm Nhiệm Vụ Mùa" } },
    },
    {
        id = "season_mission_ten",
        group = "seasonal",
        tracker = "season_mission_completed",
        params = { ["milestone"] = 10 },
        current = 10,
        coinget = 8,
        requires_tutien = false,
        strings = { vi = { name = "Mười Nhiệm Vụ Mùa", description = "Hoàn thành mười nhiệm vụ mùa.", info = "đã hoàn thành Mười Nhiệm Vụ Mùa" } },
    },
    {
        id = "season_mission_fifteen",
        group = "seasonal",
        tracker = "season_mission_completed",
        params = { ["milestone"] = 15 },
        current = 15,
        coinget = 8,
        requires_tutien = false,
        strings = { vi = { name = "Mười Lăm Nhiệm Vụ Mùa", description = "Hoàn thành mười lăm nhiệm vụ mùa.", info = "đã hoàn thành Mười Lăm Nhiệm Vụ Mùa" } },
    },
    {
        id = "season_mission_twenty",
        group = "seasonal",
        tracker = "season_mission_completed",
        params = { ["milestone"] = 20 },
        current = 20,
        coinget = 8,
        requires_tutien = false,
        strings = { vi = { name = "Hai Mươi Nhiệm Vụ Mùa", description = "Hoàn thành hai mươi nhiệm vụ mùa.", info = "đã hoàn thành Hai Mươi Nhiệm Vụ Mùa" } },
    },
    {
        id = "season_participate",
        group = "seasonal",
        tracker = "season_mission_assigned",
        params = { ["source"] = "seasonal" },
        current = 1,
        coinget = 8,
        requires_tutien = false,
        strings = { vi = { name = "Bước Vào Mùa", description = "Nhận một nhiệm vụ mùa đã phát hành.", info = "đã hoàn thành Bước Vào Mùa" } },
    },
    {
        id = "season_repeat",
        group = "seasonal",
        tracker = "season_mission_repeat",
        params = { ["source"] = "seasonal" },
        current = 1,
        coinget = 8,
        requires_tutien = false,
        strings = { vi = { name = "Kiên Trì Theo Mùa", description = "Hoàn thành nhiệm vụ mùa lặp lại.", info = "đã hoàn thành Kiên Trì Theo Mùa" } },
    },
    {
        id = "season_claim_reward",
        group = "seasonal",
        tracker = "season_mission_claimed",
        params = { ["source"] = "seasonal" },
        current = 1,
        coinget = 8,
        requires_tutien = false,
        strings = { vi = { name = "Nhận Thưởng Mùa", description = "Nhận phần thưởng của một nhiệm vụ mùa.", info = "đã hoàn thành Nhận Thưởng Mùa" } },
    },
    {
        id = "gacha_shop_spin_once",
        group = "gacha_shop",
        tracker = "slotmachine_spin",
        params = { ["prefab"] = "xd_choujiangji" },
        current = 1,
        coinget = 8,
        requires_tutien = true,
        strings = { vi = { name = "Lần Quay Đầu Tiên", description = "Quay Máy Rút Thưởng một lần.", info = "đã hoàn thành Lần Quay Đầu Tiên" } },
    },
    {
        id = "gacha_shop_spin_ten",
        group = "gacha_shop",
        tracker = "slotmachine_spin",
        params = { ["prefab"] = "xd_choujiangji" },
        current = 10,
        coinget = 8,
        requires_tutien = true,
        strings = { vi = { name = "Mười Lần May Mắn", description = "Quay Máy Rút Thưởng mười lần.", info = "đã hoàn thành Mười Lần May Mắn" } },
    },
    {
        id = "gacha_shop_buy_lingshi",
        group = "gacha_shop",
        tracker = "slotmachine_reward",
        params = { ["prefab"] = "xd_lingshi2" },
        current = 1,
        coinget = 8,
        requires_tutien = true,
        strings = { vi = { name = "Đổi Linh Thạch", description = "Mua Linh Thạch tại Máy Rút Thưởng.", info = "đã hoàn thành Đổi Linh Thạch" } },
    },
    {
        id = "gacha_shop_buy_pill",
        group = "gacha_shop",
        tracker = "slotmachine_reward",
        params = { ["kind"] = "pill", ["source"] = "xd_choujiangji" },
        current = 1,
        coinget = 8,
        requires_tutien = true,
        strings = { vi = { name = "Đổi Đan Dược", description = "Nhận một đan dược từ Máy Rút Thưởng.", info = "đã hoàn thành Đổi Đan Dược" } },
    },
    {
        id = "gacha_shop_buy_relic",
        group = "gacha_shop",
        tracker = "slotmachine_reward",
        params = { ["kind"] = "rare", ["source"] = "xd_choujiangji" },
        current = 1,
        coinget = 8,
        requires_tutien = true,
        strings = { vi = { name = "Báu Vật May Mắn", description = "Nhận phần thưởng hiếm từ Máy Rút Thưởng.", info = "đã hoàn thành Báu Vật May Mắn" } },
    },
    {
        id = "gacha_shop_buy_material",
        group = "gacha_shop",
        tracker = "slotmachine_reward",
        params = { ["kind"] = "material", ["source"] = "xd_choujiangji" },
        current = 1,
        coinget = 8,
        requires_tutien = true,
        strings = { vi = { name = "Nguyên Liệu May Mắn", description = "Nhận nguyên liệu từ Máy Rút Thưởng.", info = "đã hoàn thành Nguyên Liệu May Mắn" } },
    },
}
