-- Retired achievements. Legacy event hooks still reference these IDs, so
-- keep a denylist while their catalog and save entries are gone.
return {
    eatgear = true,          -- WX-78
    eatkitschyidol = true,  -- Woodie
    feedwebber = true,      -- Webber
    foodwarly = true,       -- Warly
    wickerbook = true,      -- Wickerbottom
    fullmighty = true,      -- Wolfgang
    fullsinginsp = true,    -- Wigfrid
    friendmerm = true,      -- Wurt
    friendclockwork = true, -- WX-78
    pipspook = true,        -- Wendy
    dodgecharlie = true,    -- Winona
    playwes = true,         -- Wes
    bernie = true,          -- Willow
    riderwoby = true,       -- Walter
    eatfavourite = true,
    feedplayer = true,
    feedlivinglog = true,
    diecharlie = true,
    diemeteor = true,
    dierose = true,
    diepoison = true,
    reviveeffigy = true,
    revivewanda = true,
    revive = true,
    healtillweed = true,
    healwortox = true,
    spore = true,
    cursedtrinket = true,
    equipingskin = true,
    darkheart = true,
    giantplant = true,
    oceanfish = true,
    havebird = true,
    glassmaker = true,
    craftnet = true,
    friendbunny = true,
    friendcat = true,
    friendrocky = true,
    mandrake = true,
    snowchester = true,
    smallbird = true,
    friendlylavae = true,
    pigkingtrading = true,
    icetrading = true,
    pearltrading = true,
    wagstafftrading = true,
    buygears = true,
    dance = true,
    floatparty = true,
    pearlparty = true,
    killhutch = true,
    killfriendlyfruitfly = true,
    killotterhouse = true,
    hitstagehand = true,
    hauntpig = true,
    passtrinket = true,
    waterballoon = true,
    vilewormwood = true,
    saladmander = true,
    vulture = true,
    moonfrog = true,
    darkcentipede = true,
    cavemite = true,
}
